### ISSUE TITLE
Ícone da estratégia errado 

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#1]
O ícone do card de estratégia está errado. O correto é o do cavalo.
![image](https://user-images.githubusercontent.com/41954965/106782504-fd571600-6628-11eb-8661-3a77add18bc2.png)

**Comment by vrcristo1980** [comment]
o icone do cavalo foi extinto - substituído pelo ícone  do compasso

**Comment by vdcordeiro** [comment]
> o icone do cavalo foi extinto - substituído pelo ícone do compasso

Isso só iria acontecer no ciclo 02, juntamente com a troca de nome Estratégia > Modelo de Plano.
Mas tudo bem, pode deixar o compasso mesmo.

**Comment by alanrodrigo** [comment]
Item verificado e corrigido
