### ISSUE TITLE
O sistema permite que o usuário exclua a si próprio (como administrador)

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#101]
Eu consegui excluir a minha própria permissão de administrador.
Na documentação, especificamos que:
`Não deve ser permitido ao administrador excluir sua própria permissão de administrador. No card com o seu nome, não haverá o menu com a opção delete;`

**Comment by camilaseasky** [comment]
O menu virá com a opção de exclusão desabilitada.

**Comment by vdcordeiro** [comment]
Verificado.
