### ISSUE TITLE
Termos CPI e SPI sem tradução

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#104]
Os termos CPI e SPI devem ser traduzidos. No caso, em português, fica respectivamente IDC e IDP.
![image](https://user-images.githubusercontent.com/41954965/157915153-1a456c9e-a910-4d5e-99e7-16c7e65fd7d4.png)

**Comment by camilaseasky** [comment]
Ajuste implementado. Estará disponível na versão a partir das 14:00h BRT (14/03/2022).

**Comment by vdcordeiro** [comment]
Ainda não conseguimos verificar a tradução no cartão, pois ainda não iniciamos os testes de linha de base. Entretanto pude verificar que o problema persiste no painel de controle (dashboard) do workpack.
![image](https://user-images.githubusercontent.com/41954965/160186779-225a1fe7-b6c1-4394-b42c-4511806ef65d.png)

**Comment by camilaseasky** [comment]
ajustado.

**Comment by msantosmarcos** [comment]
resolvida.
