### ISSUE TITLE
Botão [Adicionar Propriedade +] fica inativo

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#105]
Quando há um grupo de propriedades criado em um workpack model, sempre após adicionar e salvar uma nova propriedade no modelo de workpack, o botão **[Adicionar Propriedade +]** localizado dentro do grupo fica inativo, isto é, ao clicar nada acontece.
É necessário dar um refresh (F5) ou trocar o idioma para que o botão volte a funcionar.

**Comment by camilaseasky** [comment]
Bug corrigido. Estará disponível na versão a partir das 14:00h BRT (14/03/2022).
