### ISSUE TITLE
Sem data fim em cronograma de step único 

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#108]
Se o usuário criar um cronograma com um único step - por ex. com início e fim no mesmo mês - é impossível editar a data de fim, pois na edição do step só aparece a data de início.
![image](https://user-images.githubusercontent.com/41954965/158240361-9a1c8256-ddef-466e-a272-217352611b6e.png)

![image](https://user-images.githubusercontent.com/41954965/158240612-7505a291-64e1-4c4f-96e9-7371e6830f34.png)

**Comment by camilaseasky** [comment]
Ajustado. Será atualizado na próxima versão disponibilizada a partir das 14:00 h.

**Comment by vdcordeiro** [comment]
Ainda com problemas. A data de fim deveria ser editável.

**Comment by camilaseasky** [comment]
ajustado.

**Comment by msantosmarcos** [comment]
demanda resolvida

**Comment by msantosmarcos** [comment]
demanda resolvida
