### ISSUE TITLE
Erro ao excluir um centro de custos

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#11]
Na verdade o centro de custo foi excluído, no entanto continua sendo apresentado na tela conforme vídeo abaixo:

https://www.loom.com/share/236ebc1498494837868f7cb87ebe56dd

**Comment by vdcordeiro** [comment]
Parece que só faltou atualizar a lista de centros de custos após a exclusão.

**Comment by msantosmarcos** [comment]
demanda executada com sucesso
