### ISSUE TITLE
Plano aberto por último não é salvo em cookie

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#110]
Veja no vídeo abaixo que após fecharmos a guia do navegador e entrar de novo no sistema, é necessário reabrir o escritório e o plano novamente.
https://www.loom.com/share/767a522d57fb43929751fc56353d164a
Segundo a especificação, o sistema já deveria abrir posicionado dentro do plano, com o menu de workpacks (maleta) visível.

Parece que o salvamento do cookie está acontecendo no logout, pois só nesse caso o comportamento está correto. O cookie deve ser salvo na abertura do plano, para funcionar em todas as situações de saída.
https://www.loom.com/share/f6751e03e7444c1489c6c0fa233b8ace

**Comment by camilaseasky** [comment]
Estamos carregando gravando o último plano nos cookies, porém só carregamos este plano quando o usuário se loga e acessa a aplicação. Depois, ao navegar pelas telas e acessar a tela de listagem de offices, não vamos carregar o plano, senão ele nunca vai conseguir acessar outros offices e planos.

**Comment by camilaseasky** [comment]
Ajustado. Estará disponivel no dia 25/03.

**Comment by vdcordeiro** [comment]
Correção verificada.
