### ISSUE TITLE
Permissão para cookies

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#111]
![image](https://user-images.githubusercontent.com/41954965/158382736-f00b0ba1-7a9b-49ee-82ed-a68276048688.png)
Todos os dias é exibida essa mensagem de permissão para os cookies. Temos algumas questões a respeito:
- Essa deveria ser uma mensagem mais geral, para armazenamento das preferências do usuário;
- Falta o ponto de interrogação ao final do texto da mensagem.
- Deveria ser exibida logo na tela de login, pois será necessário armazenar o idioma selecionado;
- Está expirando muito rápido (24h?). O prazo de expiração ´deve ser o maior possível;

**Comment by camilaseasky** [comment]
Foram feitos os ajustes solicitados. O prazo para expiração solicitado foi de 60 dias. Mas isso pode ser alterado.

**Comment by vdcordeiro** [comment]
Correção verificada.
