### ISSUE TITLE
Impossível excluir workpack model reutilizado

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#112]
É impossível excluir um workpack model reutilizado, mesmo antes de criar workpacks com ele.
Há workpacks criados com o modelo original, o que deve estar causando equivocadamente o impedimento.
https://www.loom.com/share/d11761cb7d574c1996ce8e6e5a971883

**Comment by icaromartinss** [comment]
Corrigido.

**Comment by vdcordeiro** [comment]
Correção verificada.
