### ISSUE TITLE
Valor default obrigatório em propriedade de modelo de workpack

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#113]
Ao definir uma propriedade de um modelo de wp, o preenchimento do valor default é obrigatório. 
O valor default não deveria ser obrigatório nunca para nenhum tipo de propriedade. 
https://www.loom.com/share/e6a120374b1f4768a04f5b853db8494b

**Comment by camilaseasky** [comment]
Ajustado. Disponível para testes.

**Comment by vdcordeiro** [comment]
Correção verificada.
