### ISSUE TITLE
Impossível selecionar localidade ascendente sem selecionar descendentes

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#114]
Na seleção do valor default de uma propriedade tipo localidade, não é possível selecionar uma localidade (raiz por exemplo) sem auto-selecionar as suas localidades descendentes.
https://www.loom.com/share/1fb4701e72cc4c2185c13001da4c0152

Deveria ser possível selecionar uma localidade e **opcionalmente** selecionar as suas descendentes.

**Comment by vdcordeiro** [comment]
Observe abaixo a tela do protótipo que descreve o comportamento da propriedade na criação/edição do workpack:
https://huyi79.axshare.com/#id=5syi0k&p=edit_entrega&g=1&sc=1
![image](https://user-images.githubusercontent.com/41954965/158434059-93c3598c-98dc-4dc7-a356-a7213ef88be9.png)

**Comment by vdcordeiro** [comment]
Ainda falta acrescentar o "Select All" para que o comportamento fique correto e de acordo com o protótipo.

**Comment by msantosmarcos** [comment]
resolvido.
