### ISSUE TITLE
Nome do domínio aparecendo na lista de localidades

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#115]
Em um workpack contendo uma propriedade do tipo lista de seleção de localidades, o nome do domínio está aparecendo na lista como localidade selecionável.
![image](https://user-images.githubusercontent.com/41954965/158432820-d1803055-9cb9-4347-8a8a-ceecbbc9f16a.png)

**Comment by camilaseasky** [comment]
Ajuste realizado. Estará disponível a partir das 18h BRT (17/03)

**Comment by vdcordeiro** [comment]
Correção verificada
