### ISSUE TITLE
Localidades sem ordem alfabética

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#116]
A lista de seleção de localidades está sendo apresentada fora de ordem alfabética.
![image](https://user-images.githubusercontent.com/41954965/158435487-1bb09839-3e11-42f4-865a-3979bfc89aef.png)
Conforme o protótipo, esses elementos deveriam ser apresentados em ordem alfabética.
![image](https://user-images.githubusercontent.com/41954965/158435946-024d25d9-9a7f-43db-8d80-882284837338.png)

**Comment by msantosmarcos** [comment]
Esta faltando o "Select all" no componente de seleção.

**Comment by vdcordeiro** [comment]
A questão do "Select All" será tratada na issue #114.
Fechando esta issue #116, pois a ordem alfabética foi aplicada nas localidades.
