### ISSUE TITLE
Campos de telefone não aceitam telefones fixos

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#117]
**Todos os campos de telefone** do sistema apagam seu conteúdo após digitar, caso o número tenha menos de 11 dígitos. Sabemos que números de telefones fixos possuem um dígito a menos (10), no formato 2+8 : (dd) dddd-dddd.

A aplicação deveria aceitar tanto números no formato 2+9 quanto 2+8.

**Comment by camilaseasky** [comment]
Ajustado. Será atualizado hoje a partir das 18h BRT.

**Comment by vdcordeiro** [comment]
Correção verificada.
