### ISSUE TITLE
Erro crítico ao alterar a unidade de medida de uma entrega

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#118]
Ao alterar a unidade de medida de uma entrega, **somem todos os workpacks do plano!!!** 
https://www.loom.com/share/471e139f8d124bac81ac3e914f4ce8e6

Também não é possível mais criar novos workpacks nesse plano.

**Comment by msantosmarcos** [comment]
demanda resolvida.
