### ISSUE TITLE
List mode não funciona na página manter unidades de medida

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#119]
Na página Administração > Configurações > Unidades de Medida, somente a visão de cards está funcionando. Ao selecionar a visão em LIstas, nada acontece.

**Comment by camilaseasky** [comment]
Ajustado para web. Porém para o mobile, o list mode fica inviável, pois não é possível manter os inputs em linha.

**Comment by vdcordeiro** [comment]
Correção verificada. Quanto ao mobile, não haverá visão em lista.
