### ISSUE TITLE
Impossível criar workpack(programa ou projeto)

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#122]
O sistema não está criando workpack(programa ou projeto) conforme vídeo abaixo:

https://www.loom.com/share/26fc7ff19a92444fbd077a9f598571e0

**Comment by camilaseasky** [comment]
Este erro está ocorrendo quando o workpackModel tem grupos de properties.

**Comment by icaromartinss** [comment]
Corrigido.

**Comment by msantosmarcos** [comment]
resolvido.
