### ISSUE TITLE
Problemas ao inserir centro de custos e cronograma

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#123]
No card do centro de custo, ainda esta com short mode errado, tem que ser "m" e não "k" estou no idioma português.
A data fim do cronograma esta desabilitada, dependendo do mês adicionado a data inicio que será ocultada.
O sistema deixou salvar sem informar o centro custos, e ao salvar apagou toda a estrutura até o plano.

https://www.loom.com/share/4f2ab7eedd0e43978006eda65b4b8757

**Comment by camilaseasky** [comment]
1. O ajuste do short mode foi feito.
2. Quanto a data final desabilitada é porque este cronograma só tem um mês. O step não foi feito para ter duas datas. Neste caso estamos exibindo a data final do schedule somente para informação. Se quiser alterar a data final em um schedule de um step somente, então já estaria alterando o schedule e não foi implementada edição do schedule. Assim, neste caso, deve ser excluído o schedule e criado outro. Para os schedules com mais de um periodo, essa alteração funciona, pois exibimos a data inicial no step inicial e a data final no step final e elas podem ser alteradas normalmente.
3. Já foi ajustado também para não permitir salvar sem o centro de custo.
4. Sobre salvar  apagar os workpacks, já foi identificado que não é apagado, somente está perdendo o relacionamento. Isso será corrigido no card criado para o issue #118.

**Comment by msantosmarcos** [comment]
demanda resolvida.
