### ISSUE TITLE
As propriedades de Valor, Numero e Inteiro não estão obedecendo o idioma

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#125]
As propriedades de Valor, Numero e Inteiro não estão de acordo o idioma selecionado.

Se estiver em Inglês o formato é : 1,000
Se estiver em português o formato é : 1.000

https://www.loom.com/share/b2cd22f17eb84cdca33d8498c47324d7

**Comment by camilaseasky** [comment]
Ajustado e disponível para testes.

**Comment by camilaseasky** [comment]
poderia colocar um vídeo demonstrando, pois eu testei aqui e não aconteceu isso. O que aconteceu foi a substituição da ',' (pt) pelo '.' (en) e vice-versa.

**Comment by msantosmarcos** [comment]
resolvido.
