### ISSUE TITLE
Botões sem função na visão mobile

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#127]
No tamanho mobile, não temos as visões em lista, somente em cards. Os botões que efetuam a troca entre essas visões não deveriam ser exibidos, uma vez que não têm função. 
![image](https://user-images.githubusercontent.com/41954965/159754760-8de569e9-3371-4d45-90c8-90c07548a901.png)

**Comment by camilaseasky** [comment]
O modo list só não é aplicado para os cards de workpacks e unidades de medida no mobile. Para os demais é aplicado sim. Mesmo assim quer que retire os botões no mobile?

**Comment by camilaseasky** [comment]
Ajustado disponível para testes
