### ISSUE TITLE
Opções de stakeholders não traduzidos

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#128]
Ao criar um modelo de workpack padrão projeto, estando no idioma português, os papéis default de stakeholders não são traduzidos. Aparecem em inglês.

As legendas das propriedades são criadas corretamente em português.

![image](https://user-images.githubusercontent.com/41954965/159757725-bae284e6-0a25-490d-a495-29a2a3cb492a.png)

**Comment by camilaseasky** [comment]
Ajustado. Porém como estas propriedades podem ser alteradas pelo usuário, não temos como refazer a tradução depois que o valor foi carregado da primeira vez, pois os valores atribuídos aos inputs são os traduzidos e assim perdemos as chaves.

**Comment by msantosmarcos** [comment]
ok, é isso mesmo, só faltou a tradução do item "teamMember" para "membro da equipe"

![image](https://user-images.githubusercontent.com/41967259/160905917-15ac8d67-2450-4202-b75b-7630918350b4.png)

**Comment by msantosmarcos** [comment]
demanda resolvida.
