### ISSUE TITLE
Menu de administração inacabado na apresentação para celular

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#133]
Na apresentação para tamanhos reduzidos (celular), o menu da área de administração parece estar inacabado. 
Problemas encontrados:
1. O item **Plan Models** não funciona;
2. O item **More...** abre o popup, mas 
  2.1. Os subitens não funcionam;
  2.2. Falta o subitem **Pessoas**;

**Comment by camilaseasky** [comment]
Ajustado. Estará disponível no dia 25/03.

**Comment by vdcordeiro** [comment]
Correção verificada
