### ISSUE TITLE
Ao incluir/editar processo o campo anotação não deveria ser obrigatório

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#134]
O campo anotação está de preenchimento obrigatório. Deveria ser opcional.
![image](https://user-images.githubusercontent.com/41954965/159780150-309c2241-8a1f-426c-9137-1e6e2b2f8599.png)
Além disso, está faltando:
1. A unidade (dias) no campo "Permanência" e 
2. Traduzir a unidade (days) nos cartões do histórico.

**Comment by camilaseasky** [comment]
ajustado. Estará disponível no dia 28/03.

**Comment by msantosmarcos** [comment]
os problemas persistem.
