### ISSUE TITLE
Diário: Barra de rolagem adicional indesejada

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#139]
Na exibição da timeline do diário, é exibida uma barra de rolagem adicional, que não deveria estar ali (ver imagem). Já existe a barra de rolagem geral da aplicação. O painel Journal deve crescer o suficiente para abrigar a timeline inteira. O usuário deve utilizar a barra de rolagem geral da aplicação para visualizar a timeline. 

![image](https://user-images.githubusercontent.com/41954965/160000200-cb87ae26-a127-4869-b408-936a5a4423c9.png)

**Comment by msantosmarcos** [comment]
demanda resolvida.
