### ISSUE TITLE
O painel Stakeholders dos workpacks não aparece

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#14]
Como administrador:
1. Criei uma estratégia com diversos workpack models de padrões diferentes;
2. Em quase todos os workpack models, o seletor de stakeholder está habilitado;
3. Criei um plano baseado na estratégia e seus workpacks;
4. Em nenhum dos workpacks criados apareceu o painel de Stakeholders.

https://www.loom.com/share/2773ba68f7c94f03abda2dfeed42bbd3

**Comment by alanrodrigo** [comment]
Corrigido!

**Comment by vdcordeiro** [comment]
O Painel só não aparece para os administradores.

**Comment by msantosmarcos** [comment]
demanda executada.
