### ISSUE TITLE
Diário: Ao selecionar um tipo no filtro, o resultado é adicionado à lista

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#140]
Ao selecionar um tipo no filtro, o resultado da filtragem **é adicionado** ao resultado em exibição, quando o correto seria **substituir** o resultado em exibição.

https://www.loom.com/share/2285083eca584a01a4efb4fb7eb1e966

**Comment by msantosmarcos** [comment]
demanda resolvida.
