### ISSUE TITLE
Diário: Erro no console ao clicar em thumbnail de imagem (evidência)

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#141]
Ao clicar num thumbnail de imagem de uma informação do diário, a imagem não é exibida e um erro é exibido no console do navegador.
![image](https://user-images.githubusercontent.com/41954965/160001607-95af95fa-2706-4b0d-9ae3-c7d43a693e52.png)

**Comment by msantosmarcos** [comment]
problema continua

**Comment by vdcordeiro** [comment]
O problema persiste na release do dia 22/04:
![image](https://user-images.githubusercontent.com/41954965/164766551-9d2d620a-c835-4ba9-b520-379d9687ff21.png)

**Comment by msantosmarcos** [comment]
resolvido.
