### ISSUE TITLE
Erro no console ao criar workpack

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#142]
O erro abaixo ocorre no console do navegador ao criar qualquer workpack.

![image](https://user-images.githubusercontent.com/41954965/160182343-b5ed10b0-a16e-4f06-8f9a-bc019275f0d0.png)

**Comment by msantosmarcos** [comment]
problema continua

**Comment by msantosmarcos** [comment]
resolvido.
