### ISSUE TITLE
Valor limite do centro de custos não obedece internacionalização

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#143]
No card de Centro de Custos, o separador está sempre o ponto(.), independente do idioma selecionado. Quando o idioma é português, o separador deveria ser a vírgula.

![image](https://user-images.githubusercontent.com/41954965/160184938-353f5089-4839-4951-804d-293c12f46815.png)

**Comment by msantosmarcos** [comment]
agora, ficou o contrário. Em português colocar o "." , em inglês coloca a ",".

**Comment by msantosmarcos** [comment]
resolvido.
