### ISSUE TITLE
Títulos de configuração não são atualizados ao trocar de idioma

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#145]
Na página Configurações da administração, ao trocar de idioma, os títulos dos cartões não são atualizados para o idioma selecionado. 
![image](https://user-images.githubusercontent.com/41954965/160447046-50cb7d6d-330f-4290-8a37-f030d303a59a.png)

**Comment by camilaseasky** [comment]
Ajustado. Estará disponível a partir das 14h BRT (01/04)

**Comment by msantosmarcos** [comment]
demanda resolvida.
