### ISSUE TITLE
Nome do escritório não é exibido na página de configuração de plan models (modelos de plano)

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#146]
![image](https://user-images.githubusercontent.com/41954965/160447977-e216a30b-ab6a-4c73-a1e7-7eeb53d26f0e.png)

**Comment by camilaseasky** [comment]
Ajustado. Estará disponível no dia 04/04.

**Comment by msantosmarcos** [comment]
demanda resolvida.
