### ISSUE TITLE
Workpack recortado não fica disponível para colar em outro local

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#148]
No plano de testes, o modelo "Projeto" é reutilizado e pode aparecer em 3 posições diferentes na árvore do plano.

Ao recortar de uma posição e tentar colar em outra, não é exibida a opção de colar no popup do botão [+] .

https://www.loom.com/share/15c08942fc864c729fef5fcd9a4a9487

O mesmo ocorre ainda que seja na mesma posição do modelo, em um workpack pai diferente.

A opção de colar só aparece quando é dentro do mesmo pai, o que não faz nenhum sentido. Seria como recortar e colar no mesmo lugar! Veja no print abaixo:
![image](https://user-images.githubusercontent.com/41954965/160461673-3a382e83-f737-4818-9f2f-dcc18901d0e4.png)

**Comment by msantosmarcos** [comment]
problema continua.

**Comment by vdcordeiro** [comment]
resolvido
