### ISSUE TITLE
Mensagem não tratada na exclusão de workpack model

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#149]
Ao tentar excluir um modelo com workpack já criado, é exibida uma mensagem de erro não tratada. 
É correto exibir a mensagem, mas o texto deve ser significativo e corresponder ao evento.
![image](https://user-images.githubusercontent.com/41954965/160462735-765ed9a7-08d3-4fb2-a738-897594eba89a.png)

**Comment by camilaseasky** [comment]
Resolvido. Estará disponível a partir das 14h BRT (01/04)

**Comment by msantosmarcos** [comment]
demanda resolvida.
