### ISSUE TITLE
Status calculado errado no milestone

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#152]
Hoje é dia 29/**03**/2022, a data do milestone é 29/**04**/2022, não há linha de base e o card mostra o milestone como atrasado (LATE).

![image](https://user-images.githubusercontent.com/41954965/160633508-cae71e3a-1654-48ca-9c84-95c8f038ceac.png)

Deveria mostrar "No prazo" (On schedule).

**Comment by msantosmarcos** [comment]
problema continua.

**Comment by vdcordeiro** [comment]
O problema continua

**Comment by msantosmarcos** [comment]
resolvido.
