### ISSUE TITLE
Cartões de resumo agrupando por padrão de workpack model

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#153]
No dashboard, os cards de resumo estão contabilizando os workpacks por **padrão de** wp model. 
O correto seria agrupar por **workpack model**. 
Também deveria usar o nome do workpack model no plural, quando o contador der maior que 1.
![image](https://user-images.githubusercontent.com/41954965/160637727-79336db8-31ec-4362-b47a-8fe9e278c071.png)

**Comment by msantosmarcos** [comment]
demanda resolvida.
