### ISSUE TITLE
Label incorreto da Curva S

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#154]
No dashboard, o nome do gráfico de valor agregado é "**Curva S**" (S Curve) e deve ser posicionado acima do gráfico, conforme protótipo em https://huyi79.axshare.com/#id=jsc1he&p=edit_programa&sc=1&g=1
![image](https://user-images.githubusercontent.com/41954965/160639084-852b2bd1-632e-403d-894f-b742cb6c7093.png)

**Comment by msantosmarcos** [comment]
é "Curva S e não  é "S Curva".

**Comment by msantosmarcos** [comment]
resolvido
