### ISSUE TITLE
Dashboard: Valores de IDC, IDP, SV e CV não são apresentados

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#157]
![image](https://user-images.githubusercontent.com/41954965/162221415-35f9d4d6-a171-436d-bf64-b3ab31787301.png)

**Comment by camilaseasky** [comment]
Por favor colocar o id do workpack, id da baseline, office, plano para que possamos verificar a situação.

**Comment by camilaseasky** [comment]
o problema estava no steps.

**Comment by vdcordeiro** [comment]
Resolvido
