### ISSUE TITLE
 LB: Faltam sinalizadores nos cards dos workpacks com LB salva

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#158]
![image](https://user-images.githubusercontent.com/41954965/162223296-77e51434-edc3-45d9-b6e4-7dc28afca0cd.png)
![image](https://user-images.githubusercontent.com/41954965/162223650-c80c5fdc-1633-4cbf-98c1-3e6a6194ed46.png)
![image](https://user-images.githubusercontent.com/41954965/162223721-12cddfa1-f74f-4f66-8525-7f2bc7eb191c.png)

Conforme protótipo, os cards dos wp deveriam exibir CPI (IDC), SPI (IDP) e o ícone de LB:
![image](https://user-images.githubusercontent.com/41954965/162224202-8798867b-3579-4cd2-8a73-9ccddc87b60a.png)

**Comment by vdcordeiro** [comment]
![image](https://user-images.githubusercontent.com/41954965/163236422-a2917740-2fc1-4076-bf51-d2847b664f2e.png)
Um problema similar persiste, porém agora não vemos o gráfico de marcos críticos no portfolio, programa e projeto.
O ícone de LB aparece no programa e no projeto. Não aparece no portfolio. 
![image](https://user-images.githubusercontent.com/41954965/163237068-fc762654-1df6-43c9-9071-e129e64a7a22.png)
![image](https://user-images.githubusercontent.com/41954965/163237155-80620abd-cd55-485b-9c0b-272869724fd3.png)

**Comment by msantosmarcos** [comment]
resolvido.
