### ISSUE TITLE
Painel de cronograma não esta traduzindo o idioma corretamente

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#16]
Painel de cronograma não esta traduzindo o idioma corretamente conforme imagem abaixo:

![image](https://user-images.githubusercontent.com/41967259/107670640-b218b500-6c71-11eb-96b8-a9daafea1476.png)

**Comment by vdcordeiro** [comment]
A tradução só ocorre após o refresh da página, comportamento diferente dos demais labels, que trocam de idioma automaticamente.
Além disso, a tradução da palavra "actual" está errada. Actual em português não é atual, mas sim "Real", e no contexto de gerenciamento de projetos, é "**Realizado**".

**Comment by msantosmarcos** [comment]
Demanda resolvida
