### ISSUE TITLE
Deshboard: Projeto com LB salva não exibe os cards de custos, prazos e escopo

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#160]
![image](https://user-images.githubusercontent.com/41954965/162228519-08d6c859-f6e2-412e-a175-aec091e33a2d.png)

**Comment by vdcordeiro** [comment]
Isso ocorre quando a LB é proposta, mas ainda não foi aprovada. Nesse caso, a LB deve ser ignorada até que seja aprovada e o dashboard deve apresentar os gráficos considerando a LB vigente ou nenhuma LB, conforme for o caso.

**Comment by camilaseasky** [comment]
Por favor adicionar o id do workpack, linha de base, office e plano.

**Comment by vdcordeiro** [comment]
O problema foi observado no projeto ID 1457 (HVV). No entanto, após a aprovação da linha de base parou de ocorrer.
Criei um novo projeto (ID 1728) dentro do mesmo programa para tentar reproduzir o erro. O dashboard ficou um pouco diferente. Os gráficos de custo, prazo e escopo sumiram:
![image](https://user-images.githubusercontent.com/41954965/162748647-e9b9bede-2ab6-4d76-98c4-7d9fb0730239.png)

**Comment by vdcordeiro** [comment]
O Escopo Realizado continua não aparecendo para LB "proposta".
Quando a LB é "Aprovada", nenhum realizado aparece.
![image](https://user-images.githubusercontent.com/41954965/163238255-ae55636f-9dfd-463d-a294-d234777e23c9.png)
O mesmo ocorre em todos os workpacks ascendentes.

**Comment by vdcordeiro** [comment]
resolvido
