### ISSUE TITLE
Dashboard: Organizador e Entrega não exibem escopo realizado

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#161]
Identifiquei o problema nesses 2 tipos de wp, mas pode estar acontecendo em outros. Favor verificar.
![image](https://user-images.githubusercontent.com/41954965/162229043-ee37416c-9089-443b-a723-af64fd475c63.png)

**Comment by camilaseasky** [comment]
Por favor colocar id do workpack, linha de base, office e plano.

**Comment by vdcordeiro** [comment]
Ver issue #160

**Comment by vdcordeiro** [comment]
Não é um bug. Não havia escopo realizado nesse caso.
