### ISSUE TITLE
Login mobile: menu de idioma ultrapassa o limite da tela

### ISSUE THREAD

**Issue by alanrodrigo** [sep-es-br/openpmo-web#162]
Menu de idioma ultrapassa o limite da tela

https://user-images.githubusercontent.com/42146539/162284420-ca856873-6919-4083-9ac3-403a385d1a66.mp4

**Comment by alanrodrigo** [comment]
Menu de idioma ainda ultrapassando o limite da tela

![image](https://user-images.githubusercontent.com/42146539/163402857-1286f018-9689-44c0-a5ec-a3aa1494725a.png)

**Comment by vdcordeiro** [comment]
Resolvido
