### ISSUE TITLE
LB: Tradução incorreta para "proposer"

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#172]
O termo "proposer" está sendo traduzido incorretamente para "autor" no label do campo da mensagem. O correto é proponente, conforme o outro campo à direita.
![image](https://user-images.githubusercontent.com/41954965/162500524-2db52c89-18fb-4587-8093-451f7e31c311.png)

**Comment by msantosmarcos** [comment]
resolvido.
