### ISSUE TITLE
Layout se desconfigura ao afixar o menu

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#178]
Quando o menu é afixado e os painéis são expandidos, é adicionada uma barra de rolagem extra e o rodapé fica sobreposto ao conteúdo.
![image](https://user-images.githubusercontent.com/41954965/162986359-d390a34e-a6ed-4184-850f-08006eafa518.png)

**Comment by msantosmarcos** [comment]
resolvido.
