### ISSUE TITLE
Máscara de telefone se sobrepõe ao rótulo do campo

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#180]
A máscara deveria aparecer apenas quando o campo é selecionado e o rótulo sobe. Assim não ficaria sobreposta.
![image](https://user-images.githubusercontent.com/41954965/162997392-c7783480-5e4d-4ef9-a0a3-40895130589e.png)

**Comment by vdcordeiro** [comment]
O problema persiste
![image](https://user-images.githubusercontent.com/41954965/163191160-81fd3aac-02da-42c6-b245-fcaf3bc69805.png)

**Comment by msantosmarcos** [comment]
O problema persiste.

**Comment by msantosmarcos** [comment]
resolvido.
