### ISSUE TITLE
Plano > Permissões: Regiões sem ação do clique 

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#182]
Nos cards de permissões do plano, há regiões (sinalizadas abaixo) em que o clique não funciona, mas o mouse pointer 
(![image](https://user-images.githubusercontent.com/41954965/163025630-be9f5226-7283-4375-87ce-f767b3d76698.png)) aparece.
![image](https://user-images.githubusercontent.com/41954965/163021013-5130b1f1-076d-4169-836a-859e8a347c7f.png)

**Comment by msantosmarcos** [comment]
resolvido.
