### ISSUE TITLE
Impossível excluir projeto recém criado

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#184]
A opção Excluir não aparece no menu do projeto recém criado:
![image](https://user-images.githubusercontent.com/41954965/163024425-7abc2fe6-8e3d-4a52-af4e-66adffcef1ba.png)
O projeto não tem workpacks descendentes nem linha de base. Deveria ser possível excluí-lo.

**Comment by camilaseasky** [comment]
Precisamos saber qual será a regra, pois no prototipo, quando um card é um projeto não traz a opção de excluir e sim de cancelar. Quando um projeto poderá ser excluído?

**Comment by msantosmarcos** [comment]
resolvido.
