### ISSUE TITLE
Milestone: Na exibição de lista, não há status e os ícones estão cinza

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#187]
Lista:
![image](https://user-images.githubusercontent.com/41954965/163212014-d6216998-4526-4753-8375-b549e2186960.png)

Cards:
![image](https://user-images.githubusercontent.com/41954965/163212164-44343246-87a5-417f-b6ad-f8dabb798ef9.png)

**Comment by vdcordeiro** [comment]
Ainda incorreto.
- Não sinaliza os status concluídos;
- Na exibição de lista não exibe o label do status.
Favor verificar protótipo e documentação.

**Comment by vdcordeiro** [comment]
Ainda incorreto.

Não sinaliza os status concluídos;

Favor verificar protótipo e documentação.

![image](https://user-images.githubusercontent.com/41954965/164765136-8451455c-8fe1-4219-8672-97d39b3ff67c.png)

**Comment by camilaseasky** [comment]
Esse marco critico tem a propriedade status completed marcada? Consideramos um marco crítico concluído somente quando ele tem essa propriedade como true.

**Comment by vdcordeiro** [comment]
Sim. Está marcada.
![image](https://user-images.githubusercontent.com/41954965/166232812-4e490065-ca75-44a4-89e5-36464ec74942.png)

**Comment by vdcordeiro** [comment]
Na atualização de 03/05/2022 melhorou, já apresenta alguns marcos concluídos (corretos), mas ainda não mostra a sinalização dos concluídos com atraso, como é o caso do id 726:
![image](https://user-images.githubusercontent.com/41954965/166508616-8b7946b5-8053-4c29-8cd1-e37818bbd366.png)

**Comment by vdcordeiro** [comment]
Resolvido
