### ISSUE TITLE
Dashboard: Escala da Curva S apresenta unidades em inglês

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#191]
A escala da Curva S apresenta valores 20k, 30k, 40k...
No idioma português, esses valores são padronizados no OpenPMO como m (mil). 

![image](https://user-images.githubusercontent.com/41954965/163242389-5c399d57-90b4-42da-8d7b-bf1eec6f6ef3.png)

**Comment by vdcordeiro** [comment]
Outros elementos do dashboard também apresentam o mesmo erro:
![image](https://user-images.githubusercontent.com/41954965/163256717-076a2bfb-9a64-459b-9520-d0ca2204275e.png)

**Comment by msantosmarcos** [comment]
Em inglês tb esta incorreto no card schedule.
![image](https://user-images.githubusercontent.com/41967259/163828882-23d691b5-8238-4aa3-85e1-754174f47692.png)

**Comment by camilaseasky** [comment]
Esse 'm' no card schedule é de mês ou month...

**Comment by msantosmarcos** [comment]
é m (mil).

**Comment by vdcordeiro** [comment]
@camilaseasky está certa. O "m" do card do cronograma é de "mês" ou "month".
No entanto, as demais unidades continuam incorretas:
![image](https://user-images.githubusercontent.com/41954965/164318579-3af6b894-a24e-4095-815b-f632990059eb.png)

O título do cartão de custos também na foi traduzido.

**Comment by vdcordeiro** [comment]
resolvido
