### ISSUE TITLE
Dashboard: Escopo negativo

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#192]
Estranhamente a entrega ID 1248 apresenta escopo realizado percentual **negativo** no dashboard:
![image](https://user-images.githubusercontent.com/41954965/163257332-62d2f960-bbe1-48d0-8bec-3dbf11e86761.png)
O valor absoluto também parece não corresponder à realidade.

Note que a mesma entrega apresenta no cronograma um escopo realizado positivo:
![image](https://user-images.githubusercontent.com/41954965/163257536-975c4442-f1da-449c-87be-c0be294579d9.png)

**Comment by camilaseasky** [comment]
Por favor nos passar quais deveriam ser os valores no scope neste exemplo.

**Comment by msantosmarcos** [comment]
resolvido.
