### ISSUE TITLE
Mensagem improcedente ao colar workpack

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#197]
Ao tentar colar uma entrega dentro de outro projeto do mesmo modelo, a mensagem abaixo é exibida.
Os modelos são totalmente **compatíveis**. Na verdade os 2 projetos têm o mesmo modelo, com um só modelo de entrega descendente.

![image](https://user-images.githubusercontent.com/41954965/164323105-f20ef5f2-3511-4665-95af-fdc402cd58b3.png)

**Comment by vdcordeiro** [comment]
Depois de colar, a entrega desaparece:
![image](https://user-images.githubusercontent.com/41954965/164323716-5d8f739b-b746-44a5-933a-2828a43ca201.png)

Desaparece também do projeto original:
![image](https://user-images.githubusercontent.com/41954965/164323849-4cab4f18-a617-4abd-ba66-2e12d170a0ce.png)

**Comment by vdcordeiro** [comment]
A entrega continua desaparecida. Abaixo o print to erro no front:
![image](https://user-images.githubusercontent.com/41954965/164764648-7695565d-492a-4aa4-a8da-7648d6c96567.png)

**Comment by vdcordeiro** [comment]
Embora não haja mais a entrega no projeto original (Projeto P):
![image](https://user-images.githubusercontent.com/41954965/165565940-389a4d24-f1f1-421f-9046-837ade883f1d.png)

Seu dashboard continua apontando a existência das entregas, bem como o seu card.
![image](https://user-images.githubusercontent.com/41954965/165567083-ad51f0df-a15f-41fc-bf0a-7bf2209e593a.png)

![image](https://user-images.githubusercontent.com/41954965/165567066-f20ccd4e-37aa-4b85-8389-47306616d644.png)

**Comment by msantosmarcos** [comment]
A entrega foi recortada e colada corretamente em outro projeto, no entanto, o valor do custo do projeto de origem ainda esta considerando o valor da entrega que foi recortada no dashboard.

**Comment by vdcordeiro** [comment]
Ainda não foi corrigido

**Comment by camilaseasky** [comment]
Quando um workpack era recortado, não estava sendo recalculado o dashboard de onde ele foi recortado e de onde ele foi colado. Isso já foi ajustado, porém nestes casos que já haviam sido feitos, não temos como arrumar. Tentei encontrar esse office na base de vcs mas não existe mais. Se fizerem alguma alteração no realizado das entregas, os dashboards serão recalculados.
