### ISSUE TITLE
Processos: Dados apurados incorretamente

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#199]
1. No momento da captura abaixo não estou adicionando um processo. Estou editando.
2. A organização atual não é PRODEST, é SEP.
3. A permanência deve ser o tempo total desde que o processo chegou ao órgão atual até agora.
![image](https://user-images.githubusercontent.com/41954965/164775520-5b59d486-5c66-4daa-8946-60467eea5edc.png)
![image](https://user-images.githubusercontent.com/41954965/164775907-164d966a-cbb3-49ad-bbd3-ec9950c2cc54.png)
![image](https://user-images.githubusercontent.com/41954965/164776940-29f803df-95de-47ec-bc9f-da5ee7c4f17c.png)

**Comment by vdcordeiro** [comment]
Ainda incorreto:
![image](https://user-images.githubusercontent.com/41954965/170320052-96407e0c-cdc1-432e-89e3-a2e2bad8da0e.png)
Do dia 20/04 - 11:38 até hoje (25/05 - 14:00) são 35 dias, e não 34.

**Comment by vdcordeiro** [comment]
Considerando que diversos cenários do histórico dos processos não foram previstos na especificação e só foram identificados agora, estou alterando esta issue para enhancement.

**Comment by camilaseasky** [comment]
As especificações que foram mapeadas na reunião foram implementadas.

**Comment by icaromartinss** [comment]
Quando se trata de um tipo do modelo A, tenho que usar a localidade. Para isso, eu tenho que fazer a consulta pelo id da unidade? Ou usar apenas a sigla e o nome?
![image](https://user-images.githubusercontent.com/96549380/176177288-4bea20a9-49eb-4b8c-90f2-89eb3a6dc2b4.png)

Existe um ato de "Edicao" que não possui localização, mesmo estando como modelo A.
![image](https://user-images.githubusercontent.com/96549380/176177516-f71bec2a-8bdc-4d86-bb0e-feb2640d9432.png)

Quando tento chamar o endpoint `GET /v2/processos/{idProcesso}/sinalizacao`, ele me retorna a mensagem de que o endpoint não foi encontrado (status 404).
![image](https://user-images.githubusercontent.com/96549380/176177581-43738011-edf4-494c-8c81-ab7e52855155.png)

**Comment by vdcordeiro** [comment]
Os processos "ESTRATÉGICOS" não estão sendo reconhecidos como prioritários. Ver item (4) do nosso último comentário.

![image](https://user-images.githubusercontent.com/41954965/182387317-42ce015a-5cb5-4da4-bf8f-31bd5c40e3a2.png)

**Comment by vdcordeiro** [comment]
Corrigido após atualização do application.properties.
