### ISSUE TITLE
Erro ao listar planos e projetos (entregas também)

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#200]
Ao listar planos e listar os projetos o console do chrome esta apresentando um erro na chamada ao recurso de lista de planos, conforme vídeo abaixo:

https://www.loom.com/share/3536ae970ef54cddb6f874eac0891752

**Comment by vdcordeiro** [comment]
O erro aconteceu também ao listar as entregas do projeto "Projeto A":
![image](https://user-images.githubusercontent.com/41954965/166277142-cf58e8b5-c6ef-4602-a236-f390bc7a7c52.png)
![image](https://user-images.githubusercontent.com/41954965/166278409-26858245-094b-453d-89b8-cf207495f78d.png)
Esse projeto já tinha uma linha de base salva vigente com uma única entrega ("Entrega 01") dentro, que mostrava tudo normal. Depois eu:
1. Criei uma nova entrega "Entrega 02" no projeto "Projeto A";
2. Sem criar o cronograma, submeti nova linha de base do projeto;
3. Recusei a nova LB;
4. Criei o cronograma da "Entrega 02".
5. Retornei ao "Projeto A" e o erro acontece a partir daí;
