### ISSUE TITLE
Dashboard: Abreviações não traduzidas

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#203]
As abreviações (SIGLAS) da análise de valor agregado não foram traduzidas no português.
EV > VA
AC > CR
PV > VP
EAC > ENC
ETC > EPC
CV > VC
SV > VP

**Comment by vdcordeiro** [comment]
CV => VC
SV => VP

**Comment by camilaseasky** [comment]
Ajustado. Será atualizado as 14h BRT 03/05

**Comment by vdcordeiro** [comment]
Faltaram VC e VP
![image](https://user-images.githubusercontent.com/41954965/166693087-05accf37-a88c-41e7-bd77-d55d46b18a89.png)

**Comment by camilaseasky** [comment]
Ajustado. Será atualizado as 14h BRT 04/05
