### ISSUE TITLE
Dashboard: Valores de IDC e IDP limitados

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#207]
Os valores de IDC e IDP estão limitados a 2 no número do gráfico.
Embora se deva tomar a máxima escala de 2 como referência para o preenchimento do gráfico, o número apresentado deve ser o real, calculado em cada caso.

![image](https://user-images.githubusercontent.com/41954965/166244924-a9e8fca5-ee0d-497c-a41b-b138b2af7ee5.png)

**Comment by vdcordeiro** [comment]
Nesse caso,
IDP = 5,9M/2,5M = 2,36
IDC = 5,9M/1,7M = 3,47

**Comment by camilaseasky** [comment]
Corrigido. Será atualizado as 14h BRT 03/05

**Comment by vdcordeiro** [comment]
Resolvido
