### ISSUE TITLE
Dashboard: Melhorar visualização dos números

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#209]
No dashboard, onde os números forem apresentados em modo curto (short mode), exibir uma _tooltip_ no _mouse over_, com o número completo no padrão do idioma corrente.

**Comment by vdcordeiro** [comment]
Na tooltip, onde for valor monetário (indicados abaixo) exibir no formato x.xxx.xxx,xx. 
![image](https://user-images.githubusercontent.com/41954965/166694986-6c21c480-8545-45a2-9250-e0e12f88f5e8.png)

**Comment by alanrodrigo** [comment]
https://lgykza.axshare.com/#id=2nah7r&p=edit_programa

**Comment by vdcordeiro** [comment]
verificado
