### ISSUE TITLE
Tradução: Traduzir "issue" como "ocorrência"

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#212]
A tradução deve ser ajustada para todo o sistema.
![image](https://user-images.githubusercontent.com/41954965/167014035-2058fc2e-d186-4cd3-8ed3-2f1de9819c68.png)
![image](https://user-images.githubusercontent.com/41954965/167014274-790aebca-7dc3-4422-bc79-d00f3f7a8e2e.png)
![image](https://user-images.githubusercontent.com/41954965/167014421-0202e38f-c01b-4acb-8f87-24b4c2caa2ed.png)

**Comment by camilaseasky** [comment]
Ajustado. Estará disponível a partir do dia 16/06.

**Comment by msantosmarcos** [comment]
resolvido.
