### ISSUE TITLE
Pessoas: item duplicado

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#216]
![image](https://user-images.githubusercontent.com/41954965/167025251-7e310d38-5f4d-4e87-8c81-d7f1f6cf2996.png)

**Comment by icaromartinss** [comment]
Corrigido. O erro ocorre por que a Person possui dois avatares no banco: relacionamento `IS_A_PORTRAIT_OF.` Por favor, remover um dos avatares da Person "Vagner Cordeiro."
