### ISSUE TITLE
Erro na configuração do dashboard

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#217]
Ao alterar o idioma do sistema na Administração do portifólio a propriedade partes interessadas esta se perdendo (ao mudar para o idioma inglês) conforme vídeo abaixo:

https://www.loom.com/share/9e193170cced4fa98c318d0453ec4eb3

**Comment by icaromartinss** [comment]
Resolvido. Para corrigir o problema de agora, exclua todos os stakeholders da lista, salve, depois selecione todos os stakeholders e salve novamente.

**Comment by msantosmarcos** [comment]
resolvido.
