### ISSUE TITLE
Permissions: Escrever o papel em múltiplas linhas

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#220]
Nos cartões de permissões, o papel não pode ser truncado, pois fica impossível distinguir um do outro, como no exemplo abaixo:
![image](https://user-images.githubusercontent.com/41954965/167200683-a72bbac8-69c5-4c2e-9ced-fcd9f55840b9.png)

Seguir o exemplo do protótipo:
![image](https://user-images.githubusercontent.com/41954965/167200426-6e166ebd-da9d-4913-8d7e-b90c11ed68a0.png)

**Comment by camilaseasky** [comment]
Na época da implementação foi conversado sobre isso e definido que fossem usadas as reticências, pois ao quebrar em várias linhas quebra  o layout dos cards.

**Comment by vdcordeiro** [comment]
OK. Classificando como melhoria, pois a solução gerou um problema pior. O que vamos fazer:
1. Deixar exibir em até 3 linhas, reduzindo um pouco o tamanho da fonte, para ficar como o protótipo. Se chegar ao final da 3a linha, truncar com reticências.
2. Se necessário, aumentar a altura do card.
3. Exibir o nome completo em _tooltip_ no "_mouse over_".

**Comment by msantosmarcos** [comment]
resolvido.
