### ISSUE TITLE
Admin: Menu Modelos de Plano não funciona

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#221]
Ao clicar no item de menu Modelos de Plano, nada acontece.
![image](https://user-images.githubusercontent.com/41954965/167419370-52234834-9bd5-459e-a1ef-6e951995b58d.png)
... e o erro abaixo é exibido no console:
![image](https://user-images.githubusercontent.com/41954965/167419912-c897a012-d6dc-4a6d-b167-4393d908d380.png)

**Comment by msantosmarcos** [comment]
resolvido.
