### ISSUE TITLE
Menu da página administradores

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#225]
A página "Administradores" abaixo está relacionada ao sistema como um todo. Não é específica de um escritório, portanto não deve ter no menu lateral os itens de configuração de escritório. O primeiro item, de seleção do escritório, deve ser mantido.
![image](https://user-images.githubusercontent.com/41954965/167711727-0de459bc-c512-40f0-9791-503bcf769611.png)

Issue aberta como melhoria, uma vez que o protótipo está incorreto.

**Comment by msantosmarcos** [comment]
resolvido.
