### ISSUE TITLE
Profile: Qual é a "Plan Permission"?

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#226]
O texto "Plan Permission" é exibido sem um valor. Se o usuário não tem uma permissão direta no plano, esse texto nem devia ser exibido.
![image](https://user-images.githubusercontent.com/41954965/167849003-b8ae8da7-5a40-4a37-951a-d6de2b2c0a3c.png)

**Comment by msantosmarcos** [comment]
resolvido.
