### ISSUE TITLE
Riscos ficam listados para os wp ascendentes

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#231]
Tenho um programa que contém projetos. Ambos têm gestão de riscos habilitada.
Bug: Todos os riscos criados no projeto aparecem na lista de riscos do programa (pai) como se fossem riscos do programa. Na verdade são do projeto.
Entendo que esteja correto contabilizar os riscos de toda a árvore de descendentes no gráfico do painel de controle e sinalizadores dos cards, mas na lista de riscos do programa, deve aparecer apenas os riscos criados no programa.
![image](https://user-images.githubusercontent.com/41954965/167874913-5c8c3518-bb14-4ea1-87ba-fdf0cdc64ddb.png)
![image](https://user-images.githubusercontent.com/41954965/167875760-98eaf676-d388-435a-9773-1dad2e236954.png)

**Obs.:** O oposto - riscos do ascendente aparecerem nos descendentes - não acontece, o que está correto.

**Comment by msantosmarcos** [comment]
resolvido
