### ISSUE TITLE
Admin: consulta People não exibe informações de permissão

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#233]
Nas permissões do escritório pode-se ver a permissão do usuário Hanailsom:
![image](https://user-images.githubusercontent.com/41954965/170335661-3a1d86ce-d886-4b01-82e2-0ed556c89ffe.png)
Porém, na exibição do perfil, a partir da página People, as permissões não aparecem. Dá um erro de requisição no Chrome:
![image](https://user-images.githubusercontent.com/41954965/170336787-535efa26-15a9-4dbf-840c-db901dd4470d.png)

**Comment by camilaseasky** [comment]
Problema resolvido. Disponível para teste a partir das 12h BRT (08/06)

**Comment by camilaseasky** [comment]
Por um erro de mapeamento do office, estavam sendo excluídos os relacionamentos de contact_book das persons com o mesmo. Assim,  não trazia a person na tela de listagem. O problema foi corrigido, mas as persons precisam ser retiradas e colocadas novamente nas permissions, stakeholders... para recriar o relacionamento com o office.

**Comment by vdcordeiro** [comment]
Segui as orientações acima, mas o erro permanece. Testei ainda pelo pelo postman. Mesmo erro 500 no request https://hom.pmo.es.gov.br/openpmo/persons/1198/office/431.

{
    "erro": "erro.negocio$Incorrect result size: expected at most 1"
}

**Comment by icaromartinss** [comment]
Resolvido.
![image](https://user-images.githubusercontent.com/96549380/173661894-ecea10eb-c616-491b-b8d1-a6d8a5f066ab.png)

**Comment by vdcordeiro** [comment]
Ainda não foi totalmente corrigido. As informações aparecem para alguns, mas não aparecem para outros. Concedi permissões a uma pessoa totalmente nova no sistema (Andressa Leal Santos), mas suas informações não carregam.
![image](https://user-images.githubusercontent.com/41954965/173932294-60082c40-5d28-438f-a359-ff4b607e234a.png)
![image](https://user-images.githubusercontent.com/41954965/173932385-6fc51277-48d7-45c5-b13f-36ba4f3143a1.png)
![image](https://user-images.githubusercontent.com/41954965/173932505-6ec566bc-90fe-4970-a419-5c531ab1c9b1.png)

**Comment by camilaseasky** [comment]
Você concedeu qual tipo de permission? Office, plan ou workpack?
Dei permissão em um plano para ela e ficou tudo ok na consulta. Este erro me pareceu erro de acesso ao acesso cidadão...

**Comment by vdcordeiro** [comment]
Concedi permissão no escritório apenas. Veja o vídeo:

https://user-images.githubusercontent.com/41954965/175402352-703ee9a1-b2f6-4d58-b38f-7c83b71b5895.mp4

**Comment by icaromartinss** [comment]
Provavelmente, não foi feita uma atualização do `openpmo-web` nem do `openpmo-api`, pois não foi possível reproduzir os erros, mesmo usando o banco enviado pelo cliente.

**Comment by vdcordeiro** [comment]
Resolvido
