### ISSUE TITLE
Filtros com regras salvos incorretamente

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#235]
https://user-images.githubusercontent.com/41954965/173608648-ec278be3-2ecd-4f05-ac0a-e0fbd37b4bb9.mov

**Comment by vdcordeiro** [comment]
https://user-images.githubusercontent.com/41954965/173612685-351e71e4-0097-4890-968f-a0bf0ab31d53.mov

**Comment by vdcordeiro** [comment]
Problema resolvido parcialmente apenas. No primeiro cenário (reinserido abaixo), embora o salvamento do filtro seja efetuado corretamente, o filtro não funciona. Na lista de escritórios, ao criar um filtro com a simples regra nome = CGTI, não retorna nenhum escritório.
https://user-images.githubusercontent.com/41954965/173608648-ec278be3-2ecd-4f05-ac0a-e0fbd37b4bb9.mov

**Comment by icaromartinss** [comment]
Provavelmente, não foi feita uma atualização do `openpmo-web` nem do `openpmo-api`, pois não foi possível reproduzir os erros, mesmo usando o banco enviado pelo cliente.

**Comment by vdcordeiro** [comment]
resolvido
