### ISSUE TITLE
Cancelamento de Workpack: opção no menu

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#238]
A opção de cancelar um workpack está condicionada à existência de linha de base para aquele workpack.
A aplicação parece adotar outro critério para exibir a opção no menu do card, pois há workpacks COM LB e SEM a opção cancelar e também há workpack SEM LB e COM a opção cancelar.

https://user-images.githubusercontent.com/41954965/173634360-f4d5725c-6bd7-4911-a2a1-e2bb3958f823.mov

**Comment by icaromartinss** [comment]
Um dos pontos que foram descritos na documentação diz que a opção que permite cancelar um projeto só deve aparerer caso ele não possua nenhuma proposta de cancelamento ou linha de base pendente.

> Cenário: <#C23.5> - <Propor cancelamento de projeto>
Menu -> WBS → [Workpack X ->]* menu do card Project Z → Cancelar
Dado que o usuário logado possua permissão de acesso como Administrador ou User com Permissão de Edit no Workpack, e
Dado que o Workpack é do padrão project, e 
Dado que o Workpack possui uma baseline vigente, e
Dado que o Workpack não possui nenhuma proposta de cancelamento ou linha de base pendente
Quando clicar no menu do card do projeto → Cancelar
Então o sistema deverá permitir que o usuário proponha ao CCB o cancelamento do projeto

Que é o caso do "Projeto P":
![image](https://user-images.githubusercontent.com/96549380/173679439-74645c5e-eff2-4cf3-ad62-444d7555bb88.png)

[Link da documentação](https://totemti.atlassian.net/wiki/spaces/OPMO/pages/1955692595/Manter+Pacote+de+Trabalho+-+Projeto+Linha+de+Base+Baseline+-+RELEASE+2.0)

**Comment by vdcordeiro** [comment]
A explicação do @icaromartinss esclarece a questão dos workpacks COM LB e SEM a opção cancelar. De acordo.

Quanto à questão dos workpacks SEM LB e COM a opção cancelar (Entrega fase 2 do exemplo), era realmente um bug, que foi corrigido e verificado. Por isso estou fechando a issue e mantendo a tag bug.
