### ISSUE TITLE
Cancelamento de projeto não se efetiva

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#239]
Após o cancelamento de um projeto, ele continua editável e sendo exibido como se não estivesse cancelado.

https://user-images.githubusercontent.com/41954965/173636922-fb260a46-5f2d-489d-adc8-342bb058cb41.mov

**Comment by vdcordeiro** [comment]
Agora, na aprovação do cancelamento dá uma mensagem de erro (não tratada) e é impossível aprovar o cancelamento.
![image](https://user-images.githubusercontent.com/41954965/173924676-599f0692-5db2-45c3-8282-2ec7ff784c90.png)
Só é possível rejeitar o cancelamento.

**Comment by vdcordeiro** [comment]
Ainda não cancela. Acessei o CCB para tentar aprovar o cancelamento do mesmo projeto "Liberdade" e a mesma mensagem acima é exibida. Rejeitei o cancelamento e retornei ao projeto para tentar fazer nova proposta de cancelamento. O item Cancelar sumiu do menu:
![image](https://user-images.githubusercontent.com/41954965/175388608-c92dbd05-fe7b-4237-a3ff-263f7a3f632e.png)

**Comment by icaromartinss** [comment]
Provavelmente, não foi feita uma atualização do `openpmo-web` nem do `openpmo-api`, pois não foi possível reproduzir os erros, mesmo usando o banco enviado pelo cliente.

**Comment by vdcordeiro** [comment]
Resolvido
