### ISSUE TITLE
Barra de rolagem desnecessária

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#241]
Essa barra de rolagem é desnecessária. Se houver uma quantidade excessiva de itens, aí sim, será exibido a barra de rolagem.

workpack
![image](https://user-images.githubusercontent.com/41967259/173917414-63be6edf-d979-4288-9ac7-b5e14e431701.png)
workpackModel
![image](https://user-images.githubusercontent.com/41967259/173918200-3b0a2e6d-a71b-492f-8889-9c0ba5ff52ed.png)

**Comment by camilaseasky** [comment]
Ajustado. Estará disponível a partir do dia 16/06.

**Comment by msantosmarcos** [comment]
resolvido.
