### ISSUE TITLE
 Aba Linha de Base não aparece em projeto específico

### ISSUE THREAD

**Issue by helenafig** [sep-es-br/openpmo-web#243]
No página do projeto Bolsa Técnica, a Aba "Linha de Base" deveria aparecer após a aba "Partes Interessadas e Permissões". 
Porém, funcionalidade não aparece ao navegar no projeto

Projeto Bolsa Técnica:[link homologação]( https://hom.pmo.es.gov.br/#/workpack?id=1931)
![Linha de base - bolsa técnica](https://user-images.githubusercontent.com/60613757/182668048-e1c8e589-7a86-46fc-8c5d-95c365943fa8.jpg)

**Comment by vdcordeiro** [comment]
Corrigido
