### ISSUE TITLE
Ambiguidade e erro ao indicar o Marco Crítico como concluído

### ISSUE THREAD

**Issue by helenafig** [sep-es-br/openpmo-web#244]
O sistema mostra duas maneiras de marcar o Marco Crítico (Toggle abaixo da data, e Checkbox no canto superior direito).

Link exemplo: [https://hom.pmo.es.gov.br/#/workpack?id=1143&idPlan=2026](https://hom.pmo.es.gov.br/#/workpack?id=1143&idPlan=2026)
![MC concluído toggle](https://user-images.githubusercontent.com/60613757/182673029-523c5aa5-76b1-41a3-ae12-e79ec28f7444.jpg)

Ao selecionar Concluído pelo Toggle a informação não é registrada, e o marco continua como atrasado. 

![MC concluído continua atrasado](https://user-images.githubusercontent.com/60613757/182673070-9bcbf727-d3d1-4a26-b456-319c27889768.jpg)

Se o MC é marcado no check box do lado direito como Concluído, a visualização da página da etapa é alterada para concluido.
Além disso, ao clicar no checkbox não aparece a opção de Salvar, apenas se tiramos e recolocamos a seleção do toggle Concluído.

![MC concluído checkbox](https://user-images.githubusercontent.com/60613757/182673087-15e01db6-9808-497e-b4f6-0ec76c49f910.jpg)

![MC concluído certo](https://user-images.githubusercontent.com/60613757/182673095-025845d1-b3ad-477b-8365-90d331868b05.jpg)

**PONTO DE ATENÇÃO:** ter dois botões para marcação de concluído pode confundir os usuários e levar a marcações erradas.

**Comment by vdcordeiro** [comment]
Temos 2 problemas:
1. A propriedade configurável "Concluído" (toggle) deve ser excluída da configuração do modelo padrão "Marco Histórico", uma vez que já temos esse controle obrigatório nesse padrão, que é a check box "Concluído", exibido no alto do painel.

2. Quanto à questão do botão salvar, percebi que a atualização está sendo aplicada no clique da check box, o que está fora do padrão do sistema, que é: Sempre que houver alteração de propriedade, o botão save sobe e as alterações são aplicadas apenas se/quando o usuário clicar no botão.

**Comment by vdcordeiro** [comment]
Resolvido

**Comment by helenafig** [comment]
A dupla seleção de Concluído ainda está disponível no sistema 
![image](https://user-images.githubusercontent.com/60613757/184136569-140f10a0-9bec-4c3d-ae03-7ce0702d9b9f.png)
