### ISSUE TITLE
Erro ao inserir anexo no Diário do Projeto

### ISSUE THREAD

**Issue by helenafig** [sep-es-br/openpmo-web#245]
Página do projeto testado: [https://hom.pmo.es.gov.br/#/workpack?id=2047](https://hom.pmo.es.gov.br/#/workpack?id=2047)

Anexo inserido nas informações do diário não aparece na página principal do projeto

Texto inserido: “Testando a funcionalidade de diário” 

![Anexo diário](https://user-images.githubusercontent.com/60613757/182674087-27ee7cda-2466-45e0-964c-eb67328ee1e4.jpg)

![Diário sem anexo](https://user-images.githubusercontent.com/60613757/182674096-d6faaf57-e3fa-42f4-9fb5-605a6aa9dcd7.jpg)

**Comment by icaromartinss** [comment]
As evidencias estão aparecendo normalmente.

![image](https://user-images.githubusercontent.com/96549380/183755931-278721fa-d352-487e-81d5-6836e352c2f0.png)

**Comment by vdcordeiro** [comment]
Corrigido
