### ISSUE TITLE
 Ao clicar no centro de custo de entrega, sistema redireciona a página do projeto

### ISSUE THREAD

**Issue by helenafig** [sep-es-br/openpmo-web#246]
Ao clicar no centro de custo da entrega “Implantação da Estratégia Estadual de Carbono” o sistema retorna a página do projeto “Reflorestar”.
Link testado:
[https://hom.pmo.es.gov.br/#/workpack?id=2202&idPlan=2026](https://hom.pmo.es.gov.br/#/workpack?id=2202&idPlan=2026)

O certo seria entrar na propriedades do Centro de Custo para realizar edição

![Redirecionamento errado](https://user-images.githubusercontent.com/60613757/182674616-9dcac4fc-718a-4380-967a-b7a453540976.jpg)

**Comment by vdcordeiro** [comment]
Realmente me parece um bug. Observe entretanto que este Centro de Custo é do projeto (e não da entrega). Ele só é exibido na entrega, para facilitar a sua utilização no cronograma, uma vez que diversas entregas de um mesmo projeto podem obter recursos de um mesmo centro de custos.
O clique, no entanto, deveria direcionar para a página ... (Programa) > (Projeto) > **(Centro de Custos)**. Está direcionando para ... (Programa) > **(Projeto)**

**Comment by vdcordeiro** [comment]
Resolvido
