### ISSUE TITLE
Visualização cortada de textos das propriedades do projeto

### ISSUE THREAD

**Issue by helenafig** [sep-es-br/openpmo-web#247]
Link teste: [https://hom.pmo.es.gov.br/#/workpack?id=2047](https://hom.pmo.es.gov.br/#/workpack?id=2047)

Campos de texto longos são cortados na visualização das propriedades. Leitura e visualização da descrição do projeto ficam prejudicados.

![Descrição projeto cortada](https://user-images.githubusercontent.com/60613757/182675321-139c89b0-3cf5-49c0-8b03-eb91dfe0eb21.jpg)

**Comment by vdcordeiro** [comment]
Isso não é um bug, mas uma configuração inadequada.

Campos onde se espera a inserção de textos mais longos devem ser configurados como propriedades do tipo "Área de Texto" (e não "Texto").
![image](https://user-images.githubusercontent.com/41954965/182678093-14b9eceb-bcd7-41d7-965b-11f104da1611.png)
Esse tipo de propriedade permite a criação de campos de texto com múltiplas linhas, permitindo inclusive a definição do número de linhas exibido em tela.

**Comment by vdcordeiro** [comment]
Corrigido
