### ISSUE TITLE
Impossível consumir projeto compartilhado

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#248]
O projeto P1, do escritório "CGTI" foi compartilhado como edição com o escritório "Consumidor":
![image](https://user-images.githubusercontent.com/41954965/182937293-777d6e60-eb7a-4d07-9931-1a301e6c6e8b.png)

Problemas:
1. A partir do escritório "Consumidor", ao clicar no card [+], só aparece a opção "Novo". Não exibe a possibilidade de consumir o projeto compartilhado.
![image](https://user-images.githubusercontent.com/41954965/182937871-66daa52b-c39b-4958-8eaf-2d692aa76fc8.png)

2. Ao clicar no botão {+] da barra superior, o submenu com as opções nem é exibido e abre direto a página de criação do projeto.
![image](https://user-images.githubusercontent.com/41954965/182939091-a681abff-88e2-4d2e-8a1a-8a823b493b49.png)

**Comment by vdcordeiro** [comment]
Passou a aparecer, mas ainda com erros:
1. O nome do escritório que aparece entre parêntesis deveria ser o do escritório de origem. Está aparecendo o nome do escritório consumidor.
![Captura de Tela 2022-08-09 às 14 41 31](https://user-images.githubusercontent.com/41954965/183723010-484f7c8a-f06b-4756-9261-32ef293964ed.png)

2. Ao clicar no botão de adição menor, do alto do painel, a popup não é exibida.
![Captura de Tela 2022-08-09 às 14 43 05](https://user-images.githubusercontent.com/41954965/183723230-27453b1a-835e-4b45-a82f-21d50f891502.png)

**Comment by vdcordeiro** [comment]
Melhorou, mas ainda com problemas:
1. Ao selecionar a opção Consumir..., Não aparece o nome do projeto. Aparece o nome do modelo (Projeto). Deveria aparecer o nome de cada projeto compartilhado com o escritório. O nome do escritório original entre parêntesis está aparecendo corretamente.
2. Ao selecionar o Projeto, a página do programa não carrega e dá um erro na console:
`Request URL: https://hom.pmo.es.gov.br/openpmo/workpack/linked/2663?id-workpack-model=2844&id-plan=470
Request Method: GET
Status Code: 500 
Remote Address: 201.62.46.102:443
Referrer Policy: strict-origin-when-cross-origin`
`"erro.negocio$ModelMapper mapping errors:\r\n\r\n1) Failed to instantiate instance of destination br.gov.es.openpmo.dto.workpackmodel.params.properties.PropertyModelDto. Ensure that br.gov.es.openpmo.dto.workpackmodel.params.properties.PropertyModelDto has a non-private no-argument constructor.\r\nCaused by: java.lang.InstantiationException\r\n\tat sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)\r\n\tat java.lang.reflect.Constructor.newInstance(Constructor.java:423)\r\n\tat 
...`
Obs.: O projeto é consumido assim mesmo.
3. Clicando no botão menor, a popup que aparece é diferente (não devia) e é impossível clicar na opção "Novo".

**Comment by camilaseasky** [comment]
Por favor enviar um print do item 3. Não entendi qual é a diferença.

**Comment by vdcordeiro** [comment]
Embora o projeto seja consumido e apareça na lista de projetos do programa, ao clicar no projeto dá uma tela branca com o erro: {"erro":"token.not.found"}

Na inspeção do navegador, aba network:
```
https://hom.pmo.es.gov.br/openpmo/workpack/linked/2663?id-workpack-model=2844&id-plan=2818

erro.negocio$ModelMapper mapping errors:\r\n\r\n1) Failed to instantiate instance of destination br.gov.es.openpmo.dto.workpackmodel.params.properties.PropertyModelDto. Ensure that br.gov.es.openpmo.dto.workpackmodel.params.properties.PropertyModelDto has a non-private no-argument constructor.
Caused by: java.lang.InstantiationException
...
```

**Comment by camilaseasky** [comment]
Como o menu do card principal é um menu que expande para a direita e o do card do header não teria espaço para fazer isso, eu ajustei para ficarem iguais, porém o do header vai ser um slide menu, que carregas as opções no próprio panel. Veja se pode ficar assim por favor.

**Comment by vdcordeiro** [comment]
Corrigido. Ficou ótimo. Até melhor que o outro :)
