### ISSUE TITLE
Editar perfil: Ao adicionar imagem o perfil já é salvo e desfaz outras edições

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#251]
A exclusão ou inclusão da imagem deve ser considerada como edição de um campo. O botão Salvar deve subir nesse momento, para permitir o salvamento do perfil, e não salvar o perfil direto, pior ainda perdendo as edições anteriores da tela.

**Comment by alanrodrigo** [comment]
https://www.loom.com/share/a03c65518b6b479b9e0a504dcaeee7e2

**Comment by vdcordeiro** [comment]
Corrigido
