### ISSUE TITLE
Marcos Críticos: Barra horizontal não exibe "Concluídos com Atraso"

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#253]
![Captura de Tela 2022-08-10 às 16 20 53](https://user-images.githubusercontent.com/41954965/184002432-01c6f182-249d-4ec2-a6b5-706370114515.png)

**Comment by camilaseasky** [comment]
No protótipo só são exibidos os marcos críticos concluidos, atrasados e no prazo nesta barra. Então entendi que não deveria exibir os concluídos com atraso...

**Comment by msantosmarcos** [comment]
resolvido.
