### ISSUE TITLE
Compartilhamento de Workpack: Não exclui do menu nem do painel

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#254]
Mesmo após ter excluído o compartilhamento do projeto, ele continua sendo exibido no menu e no painel de controle:
![Captura de Tela 2022-08-10 às 16 45 08](https://user-images.githubusercontent.com/41954965/184006858-169dd0ed-0038-4827-a47f-9d57489562d3.png)

**Comment by vdcordeiro** [comment]
O problema persiste

**Comment by camilaseasky** [comment]
Por favor baixar a última atualização feita as 13:50h

**Comment by vdcordeiro** [comment]
resolvido
