### ISSUE TITLE
Erro ao alterar situação do projeto 

### ISSUE THREAD

**Issue by helenafig** [sep-es-br/openpmo-web#256]
Ao alterar situação do projeto, não aparece a opção de salvar. Dessa forma não é possivel realizar a mudança de status.

projeto testado: https://hom.pmo.es.gov.br/#/workpack?id=2047

Tentativa de alterar de Execução para Estrauturação
![image](https://user-images.githubusercontent.com/60613757/184137063-27ae9aae-f0e8-4b9d-89ab-341a60d2c43e.png)

**Comment by camilaseasky** [comment]
Por favor anexe um vídeo para que possamos entender o que está acontecendo, pois alteramos a situação de um projeto e o botão salvar subiu.

**Comment by helenafig** [comment]
Segue o video de demonstração do erro
https://user-images.githubusercontent.com/60613757/184202221-d4db1367-8b0d-4222-b339-327b592bde23.mp4

**Comment by msantosmarcos** [comment]
demanda resolvida
