### ISSUE TITLE
Erro ao criar cronograma de entrega sem custo

### ISSUE THREAD

**Issue by helenafig** [sep-es-br/openpmo-web#257]
Ao criar o cronograma de uma entrega sem custo, somente com os valores do físico, não aparece a opção de salvar o cronograma. 
Dessa forma não é possóvel criá-lo.

Entrega testada: [https://hom.pmo.es.gov.br/#/workpack/schedule?idWorkpack=1284&unitMeansureName=%25](https://hom.pmo.es.gov.br/#/workpack/schedule?idWorkpack=1284&unitMeansureName=%25)

![image](https://user-images.githubusercontent.com/60613757/184137878-b0812f0f-b405-46b1-8225-413a11ae2e43.png)

**Comment by helenafig** [comment]
Mesmo alocando um centro de custos, não é possível salvar com o custo zerado.

![image](https://user-images.githubusercontent.com/60613757/184197504-5551580e-ab40-4a30-b7a8-28f8c8e8809d.png)

**Comment by vdcordeiro** [comment]
Resolvido
