### ISSUE TITLE
Não é possível excluir centro de custo atrelado ao projeto

### ISSUE THREAD

**Issue by helenafig** [sep-es-br/openpmo-web#258]
Ao tentar excluir o centro de custo abaixo (PSA SESA $65M), aparece a seguinte mensagem de erro:

Erro
messages.error.cost-account.delete.relationship.error

![image](https://user-images.githubusercontent.com/60613757/184239206-c056d2dd-757f-4a33-8e28-d949774425b1.png)

Link:[https://hom.pmo.es.gov.br/#/workpack?id=2047]( https://hom.pmo.es.gov.br/#/workpack?id=2047 )

Pensei que poderia ser algo relacionado ao modo execução do Projeto. Porém, nessa situação ainda é permitido criar novos centros de custos.

**Comment by camilaseasky** [comment]
Vamos ajustar a mensagem, porém não permite porque deve existir algum cronograma nos workpacks descendente associado á esse centro de custo.

**Comment by vdcordeiro** [comment]
Resolvido
