### ISSUE TITLE
Cronograma: botão salvar some se alterar propriedade

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#259]
Ao criar ou editar um cronograma, após vincular um centro de custos, se alterar algum campo das propriedades do cronograma, o botão salvar some.

**Comment by camilaseasky** [comment]
Não consegui simular este problema. Poderia gravar um vídeo por favor?

**Comment by vdcordeiro** [comment]
https://user-images.githubusercontent.com/41954965/184681373-0b98a336-8975-4d40-b873-f3660201240a.mp4

**Comment by camilaseasky** [comment]
Corrigido. Atualização feita as 17:35h BRT

**Comment by vdcordeiro** [comment]
Resolvido

**Comment by vdcordeiro** [comment]
Resolvido
