### ISSUE TITLE
problema ao desafixar menu lateral

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#261]
Não estou conseguindo retirar o menu fixo lateral, conforme vídeo abaixo:
https://www.loom.com/share/303c3443f64a4cd98f9bbfd1cf0a94cd

**Comment by camilaseasky** [comment]
Acessei o ambiente de vc e não consigo simular este erro no menu.

**Comment by camilaseasky** [comment]
Neste vídeo ele já começa com o menu fixo. Poderiam gravar o vídeo desde o momento antes de fixar o menu por favor?

**Comment by msantosmarcos** [comment]
Camila, limpei os cookies do meu navegador e voltou a funcionar.
