### ISSUE TITLE
Linha de Base: Não persiste chaves do painel ATUALIZAÇÕES

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#263]
Ao salvar um rascunho de LB, as chaves desmarcadas do painel ATUALIZAÇÕES não são persistidas. O problema ocorre tanto na edição quanto na criação da LB. 
https://user-images.githubusercontent.com/41954965/184942671-1d75917f-6fa6-42d3-8ea1-7c132e4a70b3.mov

Se ao criar nova LB ou editar um rascunho, tentamos submeter com algumas atualizações desmarcadas, dá uma mensagem de erro e não submete. Salva um rascunho.
https://user-images.githubusercontent.com/41954965/184943932-cac17358-3063-40aa-a411-9dbb26a53b2c.mov

**Comment by camilaseasky** [comment]
Sobre esse item: Ao salvar um rascunho de LB, as chaves desmarcadas do painel ATUALIZAÇÕES não são persistidas. O problema ocorre tanto na edição quanto na criação da LB.
Não é salva a parte das atualizações que serão gravadas na baseline, pois quando está na situação de draft ainda não tem os snapshots criados e não tem onde salvar essa informação.

**Comment by vdcordeiro** [comment]
> Sobre esse item: Ao salvar um rascunho de LB, as chaves desmarcadas do painel ATUALIZAÇÕES não são persistidas. O problema ocorre tanto na edição quanto na criação da LB. Não é salva a parte das atualizações que serão gravadas na baseline, pois quando está na situação de draft ainda não tem os snapshots criados e não tem onde salvar essa informação.

Tem razão. O comportamento do primeiro cenário tem que ser assim mesmo. Resta portanto apenas o segundo cenário:
Se ao criar nova LB ou editar um rascunho, tentamos submeter com algumas atualizações desmarcadas, dá uma mensagem de erro e não submete. Salva um rascunho.
https://user-images.githubusercontent.com/41954965/184943932-cac17358-3063-40aa-a411-9dbb26a53b2c.mov

**Comment by msantosmarcos** [comment]
resolvido.
