### ISSUE TITLE
Projeto: É possível editar projeto cancelado

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#264]
Os grupos de propriedades do projeto permanecem editáveis, mesmo após o cancelamento.
Pude identificar o problema em pelo menos os itens abaixo.
- Centro de Custos (edit), 
- Partes Interessadas (new, edit), 
- Marco Crítico (edit -> check box "Concluído"),
- Entrega (edit -> cronograma, partes interessadas, processos, diário... verificar outros),
- Processos (new, edit),
- Diário (new, edit),
- Checar ocorrências, riscos...

**Comment by vdcordeiro** [comment]
Ainda é possível editar o físico realizado no cronograma:
![image](https://user-images.githubusercontent.com/41954965/185153393-35971ca1-abce-442c-8526-9e652adf61cf.png)

**Comment by msantosmarcos** [comment]
RESOLVIDO.
