### ISSUE TITLE
Projeto: Erro sem sentido ao colar projeto

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#265]
Uploading Gravação de Tela 2022-08-16 às 15.12.38.mov…

**Comment by camilaseasky** [comment]
Não veio a gravação...

**Comment by vdcordeiro** [comment]
https://user-images.githubusercontent.com/41954965/185514002-afd055d7-d489-4fac-9eec-cee9d4829231.mov

**Comment by msantosmarcos** [comment]
resolvido.
