### ISSUE TITLE
Menu: Seleção sincronizada com a página

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#267]
O menu lateral deveria indicar (realçar) o escritório, plano e workpack que estão sendo exibidos na página, independentemente se a navegação ocorreu através do menu ou diretamente na página.
A indicação deve estar presente sempre que o menu estiver visível.

**Comment by vdcordeiro** [comment]
O menu está aparecendo vazio!

https://github.com/sep-es-br/openpmo-web/assets/41954965/81854e4e-402e-4039-a068-5eb9e3d5611e

**Comment by camilaseasky** [comment]
Por favor verificar novamente depois da atualização de hoje, pois isso não está acontecendo em nosso ambiente.
