### ISSUE TITLE
Centro de Custos: Alocação superior ao limite

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#268]
Conforme especificação (ciclo 1) em https://totemti.atlassian.net/wiki/spaces/OPMO/pages/1342275909/Manter+Pacote+de+Trabalho+-+Entrega,

`Lançamentos planejado acima do limite da conta contábil não serão permitidos `

O sistema permitiu planejamento superior ao limite:
![image](https://user-images.githubusercontent.com/41954965/185158816-5dd560d4-8c73-4441-aad1-94a3e2287a1c.png)

**Comment by camilaseasky** [comment]
Foi definido que não seria feito esse controle. Apenas seria demonstrado através das barras de progresso.

**Comment by vdcordeiro** [comment]
Onde está demonstrado?

**Comment by camilaseasky** [comment]
Está demontrado pela barra que exibe o valor e que pode ser comparado com o limite do centro de custo. Foi implementado conforme documentação e protótipo.

**Comment by vdcordeiro** [comment]
- Representar o limite no gráfico.
- Exibir o saldo na página de edição de estimado e realizado.
- Impedir ultrapassar o limite no custo estimado e no realizado. Nesse caso exibir mensagem, informando que o limite atingido e que para aplicar aquele valor, deve ser atualizado o limite no centro de custos.

Protótipo: https://lgykza.axshare.com/

**Comment by alanrodrigo** [comment]
Protótipo:
https://lgykza.axshare.com/#id=upcrsa&p=centro_de_custo
https://lgykza.axshare.com/#id=bg2zro&p=edit_new_schedule&g=1

**Comment by vdcordeiro** [comment]
verificado
