### ISSUE TITLE
Dataview: Layout diferente do protótipo

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#269]
Aplicação:
![image](https://user-images.githubusercontent.com/41954965/185169383-1e44bbae-617b-4586-bf69-cf3121d18a81.png)

Protótipo (https://huyi79.axshare.com/#id=qb1abw&p=dataview__workpacks_e_list_card__&g=1&sc=1):
![image](https://user-images.githubusercontent.com/41954965/185169681-977f188c-d5ad-4533-8f50-14ffa74b7b76.png)

**Comment by camilaseasky** [comment]
Em conversa sobre estes cards do tipo list, foi combinado que a data estava muito ruim sozinha lá na direita e então acordamos de colocar tudo junto em linha.

**Comment by vdcordeiro** [comment]
OK, mas a data precisava ficar pelo menos alinhada. 
E quanto ao status? Não ficaria em baixo? Da mesma forma, deveria ficar alinhado.

**Comment by camilaseasky** [comment]
Está alinhado (centralizado na horizontal). Foi combinado que ficaria tudo na mesma linha para que o card fique o mais compacto possível.

**Comment by vdcordeiro** [comment]
OK, então só alinhar verticalmente

**Comment by msantosmarcos** [comment]
resolvido.
