### ISSUE TITLE
Projeto: Campo escopo completo está editável

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#272]
O campo escopo completo está editável no projeto, ainda que possua entregas com cronogramas.
Ver exemplo em CGTI > Plano 2022 > Carteira a > ES Urgente > Projeto P 
(https://hom.pmo.es.gov.br/#/workpack?id=1183&idPlan=1001)

Segundo regras definidas na especificação (https://totemti.atlassian.net/wiki/spaces/OPMO/pages/3031957887/Situa+o+Projeto+Entrega+-+Conclu+do+Encerrado+Release+2.0), 

> 3. Com o cronograma a toggle será calculada e setada pela aplicação, a cada alteração do físico realizado, conforme regras e o campo fica readonly para o usuário. 
> 4. Com o cronograma desativado, a toggle fica liberada para o usuário alterar livremente. 
> 
> Regra para setar a situação como concluída ou não automaticamente: Essa condição será calculada para cada entrega e apurada para os elementos superiores (projeto, programa...)

**Comment by vdcordeiro** [comment]
Nota do protótipo:
```
Campo calculado automaticamente de acordo com o cronograma, caso não haja cronograma o campo pode ser manipulado manualmente. 
Havendo cronograma o campo so é exibido se concluído e fica read only
Não havendo cronograma é sempre visivel e editável
```

**Comment by msantosmarcos** [comment]
resolvido.
