### ISSUE TITLE
Entrega sem cronograma não exibe o campo "Escopo Completo"

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#273]
Ver exemplo em CGTI > Plano 2023 > Portifólio ES > Programa Saúde > Projeto Saúde > Entrega: teste
(https://hom.pmo.es.gov.br/#/workpack?id=3274&idPlan=571)
Conforme especificação em https://totemti.atlassian.net/wiki/spaces/OPMO/pages/3031957887/Situa+o+Projeto+Entrega+-+Conclu+do+Encerrado+Release+2.0,

> 4. Com o cronograma desativado, a toggle fica liberada para o usuário alterar livremente.

**Comment by msantosmarcos** [comment]
resolvido.
