### ISSUE TITLE
Workpack não esta sendo apresentado

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#275]
Erro ao consultar o workpack, conforme vídeo abaixo:

https://www.loom.com/share/582d16ca5a744697bc4caeb304756402

**Comment by camilaseasky** [comment]
Este workpack está sem properties. Não conseguimos identificar porque isso aconteceu. Ele foi recortado e colado?

**Comment by msantosmarcos** [comment]
Camila, não sei ao certo, foi um servidor da SUBEPP.

**Comment by vdcordeiro** [comment]
Parou de acontecer. Caso retorne, reabrimos a issue em garantia.
