### ISSUE TITLE
Adição de legendas no gráfico de barras

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#279]
Adicionar as legendas no gráfico de barras (popup).
ex.: a barra verde e azul representam quais valores, conforme imagem abaixo:

![image](https://user-images.githubusercontent.com/41967259/186257578-44ca2f0f-9fd9-4d8d-96cd-9523d6aeba21.png)

Utilizar a mesma legenda do painel de controle

**Comment by vdcordeiro** [comment]
Implementado.
