### ISSUE TITLE
Entrega: Impossível retomar a gestão

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#284]
A opção está desabilitada no menu

![Captura de Tela 2022-08-25 às 09 34 33](https://user-images.githubusercontent.com/41954965/186666248-71a95d3d-2e51-45c5-923c-13719fa2346d.png)

**Comment by camilaseasky** [comment]
Como todas as entregas estão encerradas, o projeto também deve estar. Então vc não consegue fazer nada dentro dele. Tem que voltar no programa, e então retomar o projeto para então habilitar a retomada das entregas.

**Comment by vdcordeiro** [comment]
Pelo que entendo, o projeto encerrado é uma consequência automática do encerramento de todas as suas entregas. 
Por isso não existe a opção "retomar projeto". Veja print abaixo.
![image](https://user-images.githubusercontent.com/41954965/186730208-84f5fabc-e645-4231-b62e-3509fc21af68.png)

**Comment by msantosmarcos** [comment]
resolvido.
