### ISSUE TITLE
Erro ao consultar linha de base

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#287]
Erro ao consultar linha de base, conforme vídeo abaixo:

https://www.loom.com/share/720f2f1d4f084c2493ffb10e5e4ba077

**Comment by vdcordeiro** [comment]
Aconteceu ao submeter: https://www.loom.com/share/285883fb88b643159240f95d4463c844

**Comment by vdcordeiro** [comment]
Mesma origem do #292
