### ISSUE TITLE
Adicionar informações da LB n cronograma e no marco crítico

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#293]
Faltou adicionar os campos  físico planejado (base line) e financeiro planejado(base line) na criação e na edição do cronograma, bem como também a data da LB vigente e os dias de diferença em relação à data do MC, conforme protótipo.

**Comment by alanrodrigo** [comment]
Protótipo: https://lgykza.axshare.com/#id=bg2zro&p=edit_new_schedule

**Comment by vdcordeiro** [comment]
A parte do MC foi implementada no ciclo 03.
A parte do schedule será implementada no ciclo 4.

**Comment by vdcordeiro** [comment]
verificado
