### ISSUE TITLE
Cronograma desaparece ao adicionar novos meses

### ISSUE THREAD

**Issue by helenafig** [sep-es-br/openpmo-web#296]
Ao adicionar novos meses no cronograma existente, o cronograma da entrega não fica mais vísivel.

Posteriormente, ao tentar adicionar um novo cronograma aparece a mensagem de erro dizendo que não é possível criar, pois já temos um existene.

Segue o link do vídeo abaixo:

https://www.loom.com/share/d381641b93534b3a8d5b84cc50dd27a6

Entrega testada: https://hom.pmo.es.gov.br/#/workpack?id=8329&idPlan=2026

**Comment by vdcordeiro** [comment]
resolvido
