### ISSUE TITLE
Erro ao submeter Linha de Base

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#303]
O erro abaixo é exibido ao tentar submeter a primeira linha de base de um projeto, com uma entrega e um marco crítico.
O salvamento da linha de base em rascunho funcionou, mas a submissão deu o mesmo erro antes e após o salvamento em rascunho.

![image](https://user-images.githubusercontent.com/41954965/215827933-12877dc1-ada9-48e1-9bb7-dc3d0f5f276e.png)

![image](https://user-images.githubusercontent.com/41954965/216049246-f354bb26-bed0-473f-9379-b9d627f08656.png)

LB: 10682
Projeto: 10613

**Comment by camilaseasky** [comment]
Poderiam passar o id do projeto onde está a linha de base por favor?

**Comment by vdcordeiro** [comment]
O erro parou de ser exibido, mas o comportamento piorou. 
Na interface, ao retornar da submissão, nenhuma linha de base é exibida, nem no painel de LB do projeto e nem na do CCB. Após sucessivas tentativas, nada aparece, no entanto ao verificar no banco de dados, podemos encontrar vários snapshots para o projeto em questão:

https://user-images.githubusercontent.com/41954965/216441674-5e419432-2b45-41e6-9cab-c13b0e47e93a.mp4

![image](https://user-images.githubusercontent.com/41954965/216433263-a3a9c40a-d3ff-4907-b9cf-aa929a5ad69b.png)

**Comment by vdcordeiro** [comment]
Alguns relacionamentos eram perdidos após o processo de submissão da LB.
Adicionado um reparo dos relacionamentos ao final do método.
