### ISSUE TITLE
Responsividade incorreta ao fixar menu lateral

### ISSUE THREAD

**Issue by TiagoTSR** [sep-es-br/openpmo-web#306]
Ao fixar o menu a responsividade não funciona de forma adequada, conforme vídeo abaixo:
https://www.loom.com/share/9c7da06c3cd54c1cb48721f701cb6a71

**Comment by vdcordeiro** [comment]
Embora a responsividade esteja funcionando, em algumas situações o efeito de arrastar a barra divisória não está funcionando:

https://user-images.githubusercontent.com/41954965/236312063-bcf56ed3-062b-4aaa-95ff-91dd47e37798.mp4

**Comment by vdcordeiro** [comment]
verificado
