### ISSUE TITLE
Impossível alterar propriedades do Escritório

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#308]
Uma vez criado um escritório, não foi possível alterar as suas propriedades, nos cenários:
- Quando o usuário é um editor do escritório, ele não tem permissão para editar as propriedades do escritório
- Quando o usuário é administrador, ele consegue alterar o nome, mas não consegue alterar o nome completo.

**Comment by icarosbmartins** [comment]
O primeiro cenário foi resolvido. No segundo cenário, a propriedade é alterada no banco e retornada corretamente pela api. O problema ocorre por conta do espelhamento da propriedade `name` na propriedade `fullName`, que dá a impressão de que a propriedade não foi alterada. Esse espelhamento foi implementado no front pelo cliente.
