### ISSUE TITLE
Inserir icone worckpack model

### ISSUE THREAD

**Issue by alanrodrigo** [sep-es-br/openpmo-web#31]
Para adicionar ícone ao workpack model, deve inserir o código do ícone do fontwesome conforme protótipo abaixo:

Protótipo:
![image](https://user-images.githubusercontent.com/42146539/108540816-69d84300-72c0-11eb-9a9d-1af10be0f028.png)

Aplicação:
![image](https://user-images.githubusercontent.com/42146539/108540898-88d6d500-72c0-11eb-9ea0-e2dc67721303.png)

**Comment by vrcristo1980** [comment]
Inserir o código do ícone no campo abre brecha de segurança.
