### ISSUE TITLE
Sinalizadores desalinhados na EAP

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#310]
![image](https://user-images.githubusercontent.com/41954965/234003571-f9c63697-88da-4f32-a927-a147e34c300a.png)

**Comment by vdcordeiro** [comment]
Verificado na maioria dos casos, mas o desalinhamento permanece em alguns casos: 
https://hom.pmo.es.gov.br/#/workpack?id=8992&idPlan=8939
![image](https://user-images.githubusercontent.com/41954965/234966277-0851d029-85c5-40dd-b3e5-65c4420eb4a3.png)
![image](https://user-images.githubusercontent.com/41954965/234966485-7498ce4e-203a-482c-b3c3-08c847722bc8.png)

**Comment by camilaseasky** [comment]
Puxar versão atualizada hoje.

**Comment by vdcordeiro** [comment]
Verificado
