### ISSUE TITLE
Após uma edição, o foco muda de aba

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#312]
https://user-images.githubusercontent.com/41954965/234009631-301e6e67-0e95-4c5b-aded-67b78badfd13.mp4

**Comment by vdcordeiro** [comment]
O item foi resolvido para todas as abas exceto as das listas de submodelos:
https://user-images.githubusercontent.com/41954965/236305764-bf3b92e7-f57a-4821-86d7-8a3b6f34cca7.mp4

**Comment by camilaseasky** [comment]
Quando ele entra em um submodelo, as abas são exibidas novamente, então o processo de armazenar em que aba está é reiniciado. Achei que não fosse necessário armazenar todo os histórico de abas selecionadas na hierarquia, uma vez que a queixa era em relação ás telas onde depois que o processo de salvar é executado, voltam para a tela do workpack de onde foi chamada... Vc quer realmente que toda a hierarquia de workpacks da estrutura de navegação que for percorrida fique armazenada com a respectiva tab selecionada?

**Comment by vdcordeiro** [comment]
Verificado
