### ISSUE TITLE
Multiselect: Linha inteira

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#318]
Embora esteja configurado para o controle ocupar a "Linha inteira", na exibição do controle isso não ocorre:
![image](https://user-images.githubusercontent.com/41954965/234031283-b174d314-0683-4ec3-aed6-b3fe5dda12c2.png)

**Comment by camilaseasky** [comment]
Essa configuração da linha inteira estabelece se o input vai ficar em uma linha sozinho e não que ele vai ocupar a linha toda. Quando o check de linha inteira não está marcado, então exibimos vários inputs que não tenham linha inteira na mesma linha.
Vc quer que esse comportamento seja diferente somente para o input do tipo seleção multipla?

**Comment by vdcordeiro** [comment]
> Essa configuração da linha inteira estabelece se o input vai ficar em uma linha sozinho e não que ele vai ocupar a linha toda. Quando o check de linha inteira não está marcado, então exibimos vários inputs que não tenham linha inteira na mesma linha. Vc quer que esse comportamento seja diferente somente para o input do tipo seleção multipla?

Tem razão, isso então não é um bug.
Nos campos Select Linha Inteira:
- quando for seleção única, vamos ajustar a largura de acordo com a opção mais longa, limitado à largura da página.
- quando for multiselect, vamos ajustando de acordo com os chips selecionados. Ao final da página, pula linha.

É possível fazer isso?

**Comment by vdcordeiro** [comment]
Verificado
