### ISSUE TITLE
Tradução não funciona

### ISSUE THREAD

**Issue by alanrodrigo** [sep-es-br/openpmo-web#32]
Tradução não esta funcionando conforme figura abaixo:

![image](https://user-images.githubusercontent.com/42146539/108542080-0a7b3280-72c2-11eb-88eb-c3a872db1bb8.png)

**Comment by vrcristo1980** [comment]
Nós não traduzimos os valores que são inputados pelos usuários. Neste caso são properties que foram inseridas com um valor default quando o sistema estava em ingles. Daí, se mudar para português, elas não serão traduzidas, pois já foram inseridas.
