### ISSUE TITLE
Exibição da lista não respeita ordem definida por numero de ordenação

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#326]
Em um workpack model, criamos uma propriedade inteiro para ser o número de ordenação e a selecionamos como "ordem".
As listagens desse modelo de workpack deveriam ser ordenadas pelo valor da propriedade de cada item, o que não está ocorrendo.

**Comment by vdcordeiro** [comment]
https://github.com/sep-es-br/openpmo-web/assets/41954965/e115dd0b-4f03-4b98-aba3-4373a686401f

**Comment by vdcordeiro** [comment]
![chrome_akWztGKG8M](https://github.com/sep-es-br/openpmo-web/assets/41954965/e0cf4f8f-2017-40f5-866f-a659b8f0e368)

**Comment by vdcordeiro** [comment]
![chrome_NLdj3c4zhP](https://github.com/sep-es-br/openpmo-web/assets/41954965/6c31ff0e-5a17-4dd1-ba02-73dd548f5c13)
![chrome_aGDCCR1da0](https://github.com/sep-es-br/openpmo-web/assets/41954965/909b4e7b-4e28-49e4-923e-06f6fae4fb9a)

**Comment by da0hn** [comment]
Caso o erro persista verificar se não foi criado vários relacionamentos do tipo `IS_SORTED_BY` relacionado ao `WorkpackModel` testado.

```sql

match (model:WorkpackModel)-[isSortedBy:IS_SORTED_BY]->(sorterModel:PropertyModel)
with *, count(isSortedBy) as relations
where relations > 1
return model, isSortedBy, sorterModel

```

**Comment by vdcordeiro** [comment]
Verificado
