### ISSUE TITLE
Cronograma: edição fora de padrão

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#334]
Em todo o sistema, todas as edições são aplicadas via botão [Salvar]. Na edição do cronograma pelos cartões esse padrão foi quebrado. O salvamento ocorre na edição de cada campo. Isso certamente confundirá o usuário e pode também gerar perda de informação, uma vez que fica impossível desistir da edição, uma vez que é iniciada.
Já temos um padrão de edição direta no cartão, como é o caso do cadastro de unidades de medida, que sá são salvas após o clique em [Salvar].

**Comment by camilaseasky** [comment]
Isso não é bug, pois foi definido desde a implementação inicial do cronograma, quando alterávamos somente o físico. A justificativa era que o usuário queria uma edição rápida.

**Comment by vdcordeiro** [comment]
Verificado
