### ISSUE TITLE
Marco Crítico: Justificativa exigida sem linha de base

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#335]
Na edição da data do MC pelo card, a justificativa é exigida mesmo quando o MC não está na linha de base. (nesse caso, deve esperar o clique no botão [save] para salvar).
MC sem linha de base deve permitir alteração de data livremente, como ocorre corretamente na edição via página de edição.

**Comment by camilaseasky** [comment]
Neste caso, quando a data for alterada no card do marco crítico, vamos exibir o botão salvar e cancelar no próprio como é feito quando ele digita a justificativa? Pois as alterações feitas nos cards das listagens não são salvas com o botão salvar do workpack em momento algum no sistema. Ficaria bem fora de padrão, pois o botão salvar do workpack é referente as properties do workpack que está sendo editado e não de workpacks filhos que estão nas listagens.

**Comment by vdcordeiro** [comment]
Seguir como é feito no cadastro de unidade de medida. Ao editar, sobe o botão de salvar. Só salva quando clicar no botão e salva todos os MCs da lista. No caso de MC com LB fica como está, pois já temos o botão salvar da justificativa.

**Comment by vdcordeiro** [comment]
Verificado
