### ISSUE TITLE
Erro na console parado na página depois da carga

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#352]
Nessa página:
![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/00aca62d-acd5-44d9-8976-b2fec7559488)

![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/1b8b8876-13ab-4f82-9562-7d1dd8ebfad5)

![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/ced32690-09d4-417d-80e7-7f781a1ebaa8)

**Comment by camilaseasky** [comment]
Esse erro é do primeng overlayPanel... já existem issues criadas e não tem uma sugestão de correção. Porém não afeta em nada o funcionamento do sistema.

**Comment by vdcordeiro** [comment]
OK, explicação aceita, porém ainda assim é um bug. Só não será corrigido, pelas razões descritas.
Fechando a issue como bug, wontfix.
