### ISSUE TITLE
Popups de IDC e IDP incompletos

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#353]
Não aparece o gráfico do indice, apenas da variação.
![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/b7721423-bdbf-4a0e-8cb6-bb188b5c45bb)

**Comment by camilaseasky** [comment]
Não foi possível simular o erro em nosso ambiente.

**Comment by vdcordeiro** [comment]
Vamos deixar aberto por um tempo, para ver se conseguimos repetir.

**Comment by camilaseasky** [comment]
Não entendi. O problema acontece de forma consistente, mas ainda não conseguiram testar...

**Comment by nandobrazil** [comment]
A versão acaba de ser atualizada.

**Comment by vdcordeiro** [comment]
Verificado
