### ISSUE TITLE
Portfolio não carrega na produção

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#357]
Esse problema só ocorreu na produção. Ao abrir o único plano cadastrado, não aparece nenhum portfólio no painel de portfolios, embora o portfólio "Realiza+ 2023-2026" apareça listado no menu lateral.
Ao clicar no portfolio no menu, nem a eap nem o painel de controle carregam. O spinner fica girando para sempre e dá uma mensagem de erro na console do navegador.

**Comment by da0hn** [comment]
O erro acontece ao excluir todos os Steps de um Schedule. Isso corrompe toda a estrutura de Workpacks por que o cálculo dos dashboards considera que um Schedule sempre terá Steps relacionados.


A correção consiste em:


* Se o Schedule não está em uma Baseline ATIVA, então ao excluir o último Step o Schedule deve ser excluído

* Se o Schedule está em uma Baseline ATIVA, então deve aparecer uma mensagem de erro e o usuário não pode excluir o último Step

**Comment by vdcordeiro** [comment]
Verificado
