### ISSUE TITLE
Dashboard - Partes Interessadas: Ordem dos papéis não é respeitada

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#374]
Ordem da configuração:
![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/4e638261-a843-4988-b3f0-5fb695d95752)

Painel:
![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/8f155b75-f042-46b5-9f68-5b6cd9a31007)

**Comment by camilaseasky** [comment]
A ordem deve ser a da listagem dos papeis no item partes interessadas e não a da seleção de quais partes interessadas serão exibidas no dashboard?

**Comment by vdcordeiro** [comment]
Tem razão... Não tinha percebido que a ordem podia ser alterada no campo _Exibir partes interessadas_. O correto é seguir a ordem desse campo e só exibir os papéis que estiverem lá.

**Comment by vdcordeiro** [comment]
Verificado
