### ISSUE TITLE
Dashboard: Código de cores trocado

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#375]
Nos gráficos dos indicadores IDC e IDP, quando o valor é igual ou superior a 1, deve ficar em azul. Quando for inferior a 1 deve ficar em vermelho.
![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/b20eafaa-af92-400f-a1c7-1eb77c014e64)

Caso similar ocorre com as variações VC e VP, quando VC ou VP for maior ou igual a zero, deve ficar em azul, quando for menor que zero em vermelho.

Lembrando que sempre que uma variação for negativa, o seu índice correspondente será menor que 1. Mesmo que este seja arredondado para 1 no gráfico, deve ficar em vermelho. 
Caso a variação seja zero, o índice será 1 e deve ficar em azul, assim como nos casos de variação positiva e índice maior que 1.

**Comment by vdcordeiro** [comment]
Tem essa situação que está sendo interpretada errada:
![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/47033e17-9460-4dc6-ab07-d91555e2bb74)
Nesse caso o CR é zero. O backend está mandando um IDC = zero, porque não tem como mandar _**infinito**_, que seria o valor correto para o IDC. Lembrando que IDC = VA/CR. Se CR = 0, IDC => infinito.
Quando não temos como calcular o IDC, o correto é o frontend não apresentar valor nenhum para ele, deixando o gauge sem valor e cinza. Assim: ![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/914db9dc-f87a-4ff4-9613-25ab75a5e214)

O mesmo deve ocorrer com o IDP quando o VP for zero.

**Comment by vdcordeiro** [comment]
verificado

**Comment by vdcordeiro** [comment]
Os índices favoráveis ainda aparecem verdes na EAP:
![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/12ae4a25-b533-4890-bcf5-363f3370385b)

**Comment by camilaseasky** [comment]
Versão atualizada neste momento.

**Comment by vdcordeiro** [comment]
verificado
