### ISSUE TITLE
CCB: Exibindo status 2 vezes e projeto nenhuma

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#378]
No CCB, conforme o protótipo, os cards das LB devem ser agrupados por status e exibir o nome do projeto em cada card:
**Protótipo**:
![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/389add7f-531b-4a2f-84ba-59eafc22b510)

A aplicação está agrupando corretamente por status, mas também está exibindo o status nos cards. Deveria ser o nome do projeto.
![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/efb58742-2a54-42ca-9051-a655a68ff6b1)

**Comment by vdcordeiro** [comment]
Continua sem aparecer o nome do projeto:
![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/4bd861b5-4b4e-4145-8d5c-e552dc5a9851)

**Comment by camilaseasky** [comment]
Atualizada a correção em uma nova versão que acabamos de subir.

**Comment by vdcordeiro** [comment]
Verificado
