### ISSUE TITLE
Rodapé desloca quando o menu é afixado

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#379]
![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/ec1a31f2-554b-438a-aed3-1eb1ee00ac7f)

**Comment by vdcordeiro** [comment]
Parou de deslocar, mas ficou sempre visível. Comportamento diferente de quando o menu está desafixado

**Comment by camilaseasky** [comment]
Atualizada a correção em uma nova versão que acabamos de subir.

**Comment by vdcordeiro** [comment]
verificado
