### ISSUE TITLE
Formato de datas

### ISSUE THREAD

**Issue by alanrodrigo** [sep-es-br/openpmo-web#38]
Ao alterar o idioma para português, deve alterar o formato de data para o padrão brasileiro.

![image](https://user-images.githubusercontent.com/42146539/108556570-fb05e480-72d5-11eb-8b29-b349768908b9.png)

**Comment by alanrodrigo** [comment]
Item verificado e corrigido na release 22/02/2021

**Comment by vdcordeiro** [comment]
Esse mesmo problema foi identificado no painel de cronograma.
![image](https://user-images.githubusercontent.com/41954965/111485844-bd9a4880-8715-11eb-951c-a7a60cf75db4.png)

**Comment by vdcordeiro** [comment]
Resolvido
