### ISSUE TITLE
Partes Interessadas: Pessoa não-usuário só exibe primeiro nome

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#383]
Ao adicionar uma pessoa Não-usuário como parte interessada, tanto no card quanto no dashboard só aparece o primeiro nome. Deveria aparecer o nome completo.

**Comment by vdcordeiro** [comment]
O método de correção foi equivocado: passou a exibir o nome completo no card. Assim o usuário perdeu a funcionalidade de escolher o nome de exibição.

O certo seria na criação aplicar o nome completo ao nome de exibição, e sempre mostrrar o nome de exibição.

**Comment by camilaseasky** [comment]
Foi ajustado para que ao criar a person que não é um usuário do acesso cidadão, será gravado o nome completo no atributo name (que esquivale a como vc quer ser chamado do acesso cidadão).
Nos cards será exibido o name como já estava anteriormente.
Quando for alterado o como vc quer ser chamado nas configurações de person, este será gravado e exibido nos cards normalmente.

**Comment by vdcordeiro** [comment]
Verificado
