### ISSUE TITLE
Erro ao executar relatório - property 0. Number

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#386]
Erro ao executar relatório com a property Number, conforme vídeo abaixo:

https://www.loom.com/share/e8c74dad89964cf685f6368ce4e6ac79

**Comment by camilaseasky** [comment]
Por favor nos envie o arquivo do modelo jrxmlm que está sendo usado.

**Comment by msantosmarcos** [comment]
[entregasNumber.zip](https://github.com/sep-es-br/openpmo-web/files/11940250/entregasNumber.zip)

**Comment by msantosmarcos** [comment]
demanda resolvida
