### ISSUE TITLE
Erro ao executar relatório - property Date

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#387]
Erro ao executar relatório, conforme vídeo abaixo:

https://www.loom.com/share/bef8470180ae4779920e2261c6c79b07

**Comment by camilaseasky** [comment]
Por favor nos envie o arquivo do modelo jrxmlm que está sendo usado.

**Comment by msantosmarcos** [comment]
[entregasDate.zip](https://github.com/sep-es-br/openpmo-web/files/11940257/entregasDate.zip)

**Comment by msantosmarcos** [comment]
demanda resolvida
