### ISSUE TITLE
Diário Evidências: Impossível abrir documento baixado

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#388]
Quando um usuário (não administrador) baixa um ducumento que é uma evidência do diário:
- Se o documento foi enviado pelo mesmo usuário, abre corretamente,
- Se o documento foi enviado por outro usuário, baixa, mas não abre.

**Comment by camilaseasky** [comment]
Fizemos testes aqui e os documentos baixam e abrem normalmente. Mesmo quando um documento está sendo aberto por outro usuário. Por favor coloque um exemplo em vídeo.

**Comment by vdcordeiro** [comment]
O problema aconteceu durante o treinamento na última sexta-feira(30). Refiz o teste hoje e não consegui repetir. 
Vou fechar pois parece que já foi corrigido junto com outra correção.
