### ISSUE TITLE
Entrega: Erro na criação

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#391]
Ao criar uma entrega, quando não preencho os campos não obrigatórios, embora suba o botão salvar e o salvamento aconteça, dá algum erro que impede a mensagem de sucesso e a carga das demais guias da entrega. Fica parecendo que não salvou.

https://github.com/sep-es-br/openpmo-web/assets/41954965/d00ddb29-78d0-4220-a7d7-092a7fbf3267

**Comment by camilaseasky** [comment]
Testei a criação da entrega com as mesmas propriedades no workpackModel em nosso ambiente e salva normalmente mesmo não preenchendo os itens obrigatórios.
Vamos precisar do seu banco para verificar o que está ocorrendo.

**Comment by vdcordeiro** [comment]
[openpmo-p.zip](https://github.com/sep-es-br/openpmo-web/files/11949573/openpmo-p.zip)

**Comment by camilaseasky** [comment]
Versão com a correção atualizada agora.

**Comment by vdcordeiro** [comment]
Testei agora e o problema persiste
