### ISSUE TITLE
Novo cronograma: Não posso vincular os custos primeiro.

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#392]
Durante o preenchimento do formulário, tenho que informar o escopo antes de vincular os custos, o que não faz sentido, já que as informações são independentes. Está correta a obrigatoriedade do escopo para gerar o cronograma, mas posso fazer o seu preenchimento antes ou depois dos custos.

https://github.com/sep-es-br/openpmo-web/assets/41954965/b4de036a-90f3-40a2-8bd3-0ddb25d83b87

**Comment by camilaseasky** [comment]
corrigido. Versão atualizada agora.

**Comment by vdcordeiro** [comment]
Verificado
