### ISSUE TITLE
Cronograma: a redistribuição não considera os vínculos múltiplos

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#393]
Quando a redistribuição dos custos age sobre meses com múltiplos vínculos, os valores ficam inconsistentes. Deveria distribuir proporcionalmente entre os centros de custos vinculados para manter a consistência com o total apresentado no mês.
https://github.com/sep-es-br/openpmo-web/assets/41954965/d3f143a0-4e73-404a-8ace-c12211c42b10

**Comment by camilaseasky** [comment]
Isso já foi ajustado. A versão foi atualizada hoje pela manhã.

**Comment by vdcordeiro** [comment]
A regra deve ser:
- para cada mês: se aquele mês possui vinculo com o centro de custos realizado, aplica a diferença sobre ele, senão aplica proporcionalmente aos centros de custos vinculados.

**Comment by camilaseasky** [comment]
Versão atualizada neste momento.

**Comment by vdcordeiro** [comment]
Verificado
