### ISSUE TITLE
Mensagens replicantes

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#394]
Em alguns casos, especialmente quando a seção expira, são exibidas diversos popups replicados da mesma mensagem informando que a seção expirou. Deveria aparecer apenas uma vez.

**Comment by camilaseasky** [comment]
Isso acontece porque conforme a tela acessada, são feitas várias requisições em paralelo para a api e ambas são respondidas pela mesma simultaneamente.

**Comment by vdcordeiro** [comment]
Sim, eu sei porque acontece, mas temos que ter uma forma de impedir.

**Comment by nandobrazil** [comment]
A versão acaba de ser atualizada.

**Comment by vdcordeiro** [comment]
Verificado
