### ISSUE TITLE
Labels trocados no título e tooltip

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#4]
Nos títulos de todas as entidades (Escritório, Plano, Workpack) está sendo exibido o Full Name. O correto seria exibir o Name.
Nas tooltips do breadcrumb está sendo exibido o Name. O correto seria exibir o Full Name, já que o nome já está no breadcrumb.
![image](https://user-images.githubusercontent.com/41954965/106802355-9f82f800-6641-11eb-953c-8ccf5db76688.png)

**Comment by alanrodrigo** [comment]
Item verificado e corrigido na release 22/02/2021
