### ISSUE TITLE
Delimitar corretamente o foco do botão

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#402]
Delimitar de forma correta o foco do botão do gerar relatório:
Exibir a lista de extensões quando clicar exatamente na setinha, conforme vídeo abaixo:

https://www.loom.com/share/3e303e1e7a0e43c1aeccca7c47b3957b

**Comment by nandobrazil** [comment]
A versão acaba de ser atualizada

**Comment by vdcordeiro** [comment]
Verificado
