### ISSUE TITLE
Exclusão de projeto

### ISSUE THREAD

**Issue by takimyns** [sep-es-br/openpmo-web#405]
Não está sendo possível a exclusão de um determinado projeto, conforme vídeo abaixo:

https://www.loom.com/share/cd4db37a879647358955c2668243a46f

**Comment by camilaseasky** [comment]
A opção excluir no menu do projeto só será exibida se este não tiver nenhuma baseline PENDENTE, ATIVA ou PROPOSTA DE CANCELAMENTO. Poderia verificar neste projeto se existe alguma baseline PROPOSTA ou em RASCUNHO...?

**Comment by takimyns** [comment]
Não se encontra nenhuma baseline pendente no momento , todas encontram-se excluídas.

**Comment by vdcordeiro** [comment]
Havia uma baseline proposta, que para ser visualizada deve ser acionado o botão "Exibir inativas"
