### ISSUE TITLE
Título não traduzido na tooltip do gráfico de marcos críticos

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#409]
O título aparece como MILESTONES no idioma portugues.

![chrome_CyQqATKoo8](https://github.com/sep-es-br/openpmo-web/assets/41954965/c1905df6-0969-4265-821b-8e6d7660f7c1)
![chrome_7EtNOz8ye3](https://github.com/sep-es-br/openpmo-web/assets/41954965/f4381682-17fa-4872-b59e-bcb5a8ab7c8d)

**Comment by camilaseasky** [comment]
Versão atualizada neste momento.

**Comment by vdcordeiro** [comment]
O problema persiste na EAP

**Comment by nandobrazil** [comment]
Versão atualizada.
