### ISSUE TITLE
Erro ao passar o cursor no IDP

### ISSUE THREAD

**Issue by takimyns** [sep-es-br/openpmo-web#412]
Ao passar o cursor em cima do ícone Índice de desempenho de Prazo(IDP) o mesmo apresentou um erro no código fonte da página, segue abaixo o vídeo:

https://www.loom.com/share/2d5ae6b0edb045c19fa562c408e82ee9

**Comment by vdcordeiro** [comment]
Por ser um bug na biblioteca e inofensivo, não será corrigido.
