### ISSUE TITLE
Erro ao entrar nos projetos

### ISSUE THREAD

**Issue by takimyns** [sep-es-br/openpmo-web#413]
Erro ao entrar nos projetos ele em momentos aparece e outros não, se apresentou dois erro no código fonte da página, segue abaixo o vídeo:
https://www.loom.com/share/e7e446b467ac455cac16215353d4e808

**Comment by nandobrazil** [comment]
Versão atualizada.

**Comment by takimyns** [comment]
continua persisti

**Comment by takimyns** [comment]
verificado com sucesso
