### ISSUE TITLE
Erro ao ao listar as entregas 

### ISSUE THREAD

**Issue by takimyns** [sep-es-br/openpmo-web#415]
Ao da entrada nas entregas que estão nas (etapas)->(projeto: Implantação das Bases de Teleflagrante - PEM e DHPP)->(Área Temática:SPJ) o mesmo apresentou um erro no código fonte da página, segue abaixo o vídeo:

https://www.loom.com/share/eea596a6fcb74aab86369c65d4426f95

**Comment by da0hn** [comment]
Corrigido na mesma versão que #413

**Comment by takimyns** [comment]
verificado
