### ISSUE TITLE
Permissão 

### ISSUE THREAD

**Issue by takimyns** [sep-es-br/openpmo-web#416]
Tem-se permissão para acessar apenas o Eixo 13, no entanto, na Estrutura Analítica do Projeto (EAP), ele consegue visualizar e ter acesso a todos os outros eixos, segue o vídeo: 

https://www.loom.com/share/286c994f59d94716b0829b9233dc57fe

**Comment by takimyns** [comment]
o erro foi verificado mas apresenta o desaparecimento da eap.

https://github.com/sep-es-br/openpmo-web/assets/136747672/337d2291-b846-40af-b38c-1f8adb3deaf9

**Comment by da0hn** [comment]
Poderia enviar um video com a aba `network` aberta?

**Comment by vdcordeiro** [comment]
Na verdade a aba só desaparece quando o usuário clica nela.

**Comment by da0hn** [comment]
Ajustado.

**Comment by takimyns** [comment]
https://github.com/sep-es-br/openpmo-web/assets/136747672/50137693-baaa-491f-bbab-914ee191ab31

**Comment by takimyns** [comment]
verificado com sucesso
