### ISSUE TITLE
Entrega não esta sendo apresentada no front end

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#419]
Na semana passada, cadastrei um projeto (Novo Caminhos - Ampliação de Vagas de Trabalho) no Open PMO (ambiente de Produção) . com 2 etapas e 3 entregas.

Na etapa 1: uma entrega
Na etapa 2: duas entregas

Estou tentando acessar a entrega da etapa 1 para editar o cronograma, porém no painel de controle aparece que tem 1 entrega, mas quando clico na aba entregas, não aparece nenhuma:

![image](https://github.com/sep-es-br/openpmo-web/assets/41967259/aed6651b-2d1b-4906-a035-3add5aa91297)

![image](https://github.com/sep-es-br/openpmo-web/assets/41967259/08123e27-18ca-422b-a9a7-4d36905a28fb)

obs: esta entrega de id(11054) encontra-se no banco, no entanto não esta sendo apresentada na interface.

**Comment by da0hn** [comment]
O erro aconteceu devido a mais de um `Dashboard` relacionado ao mesmo `Workpack`.

**Comment by msantosmarcos** [comment]
resolvido

**Comment by msantosmarcos** [comment]
resolvido
