### ISSUE TITLE
Ao excluir a origem de um reuso o sistema esta excluindo tb o próprio reuso

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#421]
Ao excluir a origem de um reuso o sistema esta excluindo tb o próprio reuso, conforme vídeo abaixo:
https://github.com/sep-es-br/openpmo-web/assets/41967259/38bc8d28-1b0f-40c9-98ef-00d799deee5d

**Comment by da0hn** [comment]
Aguardando reprodução do bug mencionado.

**Comment by vdcordeiro** [comment]
Na verdade, o bug foi capturado corretamente na reprodução acima. Conforme a especificação estabelecida no ciclo 2, ao excluir um modelo reutilizado, somente o relacionamento deve ser excluído. No caso, foi excluído o workpack model.
![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/5d0a909e-c208-4955-85f7-732052850d39)

**Comment by da0hn** [comment]
O WorkpackModel excluído no video não é o que foi reutilizado e sim um WorkpackModel neto do reutilizado.

![image](https://github.com/sep-es-br/openpmo-web/assets/40874826/4eef1fc2-dba6-4b97-9a0e-9774752154d9)
![image](https://github.com/sep-es-br/openpmo-web/assets/40874826/0524aa08-0baf-4f01-a608-8386c9406232)
![image](https://github.com/sep-es-br/openpmo-web/assets/40874826/3f7689dd-cc8f-4ba4-a148-cadc7215a283)

**Comment by vdcordeiro** [comment]
que também foi reutilizado

**Comment by da0hn** [comment]
No video fornecido o WorkpackModel reutilizado é o Projeto e a exclusão é feita em um WorkpackModel descendente Entrega e Marco Crítico. O comportamento do video está correto, pois não foi excluído o WorkpackModel reutilizado.

**Comment by vdcordeiro** [comment]
Entendi. Vamos testar de novo excluindo o modelo reutilizado

**Comment by msantosmarcos** [comment]
demanda resolvida
