### ISSUE TITLE
Lentidão no fluxo principal do workpack

### ISSUE THREAD

**Issue by takimyns** [sep-es-br/openpmo-web#422]
Lentidão excessiva no carregamento dos portfólios e eixos, conforme vídeo abaixo:

https://github.com/sep-es-br/openpmo-web/assets/136747672/a6fc2c04-7d57-4ad5-8907-e9e6609bec2f

**Comment by msantosmarcos** [comment]
com alteração implementada notamos uma redução no tempo resposta de 15 sg pra 6 sg aproximadamente.

**Comment by msantosmarcos** [comment]
Fizemos um teste com 10 acessos simultâneos utilizando um servidor de quatro núcleos e ficou constatado que com os acessos simultâneos o consumo da CPU ficou em 100% por 30 segundos, causando lentidão similar a travamento.
Estamos providenciando incremento de recursos dos servidores para minimizar o efeito, porém acreditamos que o tempo de resposta precisa ser reduzido em pelo menos 3 segundos para evitar lentidão/travamento.

**Comment by efeguri** [comment]
Ciclo 5 esta com esse ajuste de performance, assim como também foi demonstrado em reunião sobre o ajuste de ambiente que necessita ser implantado.

**Comment by vdcordeiro** [comment]
Os ajustes e incrementos de ambiente foram implementados pela equipe da SEP na produção. 
A nova VM dispõe atualmente de 14 CPUs virtuais e 24GB de RAM. Possui os serviços da api, front e banco de dados implantados em contêiners Docker separados.
Segundo análise do consumo dos recursos após turbinar o ambiente, mas ainda na versão do ciclo 4 do software, tanto o banco de dados quanto o frontend e demais conteiners consomem muito pouco dos recursos. Já a API, quando o sistema está em uso por algumas poucas (5 ou mais) pessoas chega a ocupar todas as CPUs em altos níveis por vários segundos (10s ou mais).
Os ajustes no ambiente amenizaram um pouco o problema em relação ao que tínhamos antes, pois os travamentos se tornaram mais raros. Porém a lentidão na carga, especialmente do dashboard e da EAP permanece, bem como a alta ocupação dos recursos com poucos usuários conectados, tornando bem difícil a navegação entre os workpacks da aplicação.
Um vídeo do impacto da utilização do sistema por 1 usuário (eu).

https://github.com/sep-es-br/openpmo-web/assets/41954965/25a85d93-f430-4d16-8ad4-e236c23514fd

**Comment by vdcordeiro** [comment]
Retirei o fixed até a entrega do ciclo 5 ou a correção de outra forma.

**Comment by vdcordeiro** [comment]
Fechando essa issue, pois boa parte dos problemas gerais de lentidão foram resolvidos. O problemas pontuais ainda restantes estão reportados em issues específicas.
