### ISSUE TITLE
Restringir edição de modelo de relatório a admins

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#423]
Administração: Somente admins devem ter poder de edição (criar, alterar, compilar arquivos, excluir) no painel "Modelos de Relatórios". Editores do escritório ainda poderão visualizar os modelos do painel e até fazer download dos arquivos jrxml.

Obs.: A restrição deve ser aplicada tanto no frontend quanto no backend.

**Comment by msantosmarcos** [comment]
O editor de escritório não consegue visualizar o relatório em nenhuma situação, conforme vídeo abaixo:

obs.: coloquei o usuário como parte interessado de um projeto do escritório (PMO-ES)

https://github.com/sep-es-br/openpmo-web/assets/41967259/832fd375-46d9-4fe4-b21d-8b4563c76a30
