### ISSUE TITLE
Ao retornar, o usuário deve ser posicionado sempre no último workpack acessado.

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#424]
Atualmente, é gravado em cookie o último plano acessado pelo usuário, de forma que quando ele retorna ao sistema utilizando o mesmo computador, o sistema o reposiciona naquele plano. Ocorre que quando o usuário acessa de outro computador ou após uma limpeza de histórico do navegador ou até de uma janela anônima, não temos mais essa informação e ele precisa navegar a partir do escritório. Além do mais, mesmo quando é feito do mesmo computador, ele nunca retorna ao workpack, o que seria o ideal.

A proposta aqui é guardar no banco o escritório, plano e workpack acessado sempre que o usuário visualiza um escritório, plano ou workpack na área de trabalho e utilizar essa informação em todo novo login. Dessa forma em qualquer retorno daquele usuário, não importa por onde, ele voltará ao último escritório, plano e workpack visualizado.

Como essa não é uma informação de negócio, mas sim de auxílio à navegação, sugiro que sejam guardados os ids dos últimos escritório, plano e workpack como propriedades do nó person do usuário. Creio que adicionar relacionamentos nesse caso, poluiria o modelo de negócio com informaçãode menor importância.

Regras:
- Caso tenha acessado por último um workpack, retornaremos àquele workpack. 
- Caso tenha acessado por último um plano, retornaremos ao plano, 
- Caso tenha acessado por último um escritório, retornaremos ao escritório. 
- Caso não tenha acessado nenhum dos 3 acima ou tenha visualizado por último a lista de escritórios, retornaremos na lista de escritórios (início).
- Caso tenha acessado por último qualquer outro elemento (ex.: perfil, CCB, administração), retornaremos ao último workpack, plano, escritório ou início visualizado conforme situações acima.
- Caso o id salvo do workpack não seja encontrado, não seja um workpack ou o usuário não tenha mais permissão para visualizá-lo, retornaremos ao plano.
- Caso o id salvo do plano não seja encontrado, não seja um plano ou o usuário não tenha mais permissão para visualizá-lo, retornaremos ao escritório.
- Caso o id salvo do escritório não seja encontrado, não seja um escritório ou o usuário não tenha mais permissão para visualizá-lo, retornaremos ao início (lista de escritórios).

**Comment by msantosmarcos** [comment]
Feito.
