### ISSUE TITLE
Exclusão dos escritórios

### ISSUE THREAD

**Issue by takimyns** [sep-es-br/openpmo-web#428]
Não consigo excluir o escritório "teste Tiago", este apresenta que há pendências mas não encontro apenas nos persons onde já foi excluído apresenta o ocorrido no vídeo a abaixo:

https://github.com/sep-es-br/openpmo-web/assets/136747672/c5f44392-0164-46f5-a7db-9359068ce2c9

**Comment by icarosbmartins** [comment]
A listagem de plano exige que o escritório possua ao menos um modelo de plano. O escritório possui um plano que não está vinculado com nenhum modelo de plano. Teria que verificar o que gerou a exclusão deste modelo de plano, que é a causa do bug. Para esse cenário, a exclusão deste escritório deve ser feita pelo banco de dados devido a esta inconsistência.

**Comment by msantosmarcos** [comment]
concluída
