### ISSUE TITLE
Atualização da Navegação da Árvore

### ISSUE THREAD

**Issue by takimyns** [sep-es-br/openpmo-web#429]
O menu da arvore de navegação está sendo atualizado de forma tardia, este que apresenta os itens já excluídos e que podem ainda sim ser acessados mesmo não encontrando o modelo do pacote de trabalho . Segue a baixo o vídeo:

https://github.com/sep-es-br/openpmo-web/assets/136747672/64ae14a4-b6d3-439d-8b7e-ca449f03f4a3

**Comment by camilaseasky** [comment]
Versão atualizada agora.

**Comment by takimyns** [comment]
Verificado com sucesso
