### ISSUE TITLE
Filtragem de busca

### ISSUE THREAD

**Issue by takimyns** [sep-es-br/openpmo-web#431]
É feito a busca pelas 3 principais iniciais de um nome e não é feita a busca de forma correta ele retorna a nada. Segue o vídeo abaixo:

![msedge_K421G33rvJ](https://github.com/sep-es-br/openpmo-web/assets/136747672/df0b767b-f505-4bd3-abf6-4053cbe92584)

**Comment by da0hn** [comment]
A consulta é feita utilizando o `algoritmo de levenshtein` que exige um score de corte informado via arquivo de configuração. Se a pesquisa não está retornando o valor esperado, é necessário alterar o score de corte para deixá-lo mais preciso.

**Comment by msantosmarcos** [comment]
resolvida

**Comment by takimyns** [comment]
verificado com sucesso
