### ISSUE TITLE
Não esta sendo possível a visualização da subetapa 

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#433]
Hoje pela manhã, comecei a cadastrar o projeto Escola Pública de Trânsito o
Eixo 1, área temática Segurança Pública e Justiça -> projeto solto. 

Cadastrei a etapa 1 pela manhã, e agora retornei e cadastrei a subetapa 1.
Porém quando volto para cadastrar a entrega, a subetapa "sumiu" só aparece no
painel, no EAP e na aba dela não aparece.

**Comment by da0hn** [comment]
O Workpack id: 25296 possuia uma Etapa id: 25434 com dois Dashboards. Isso é um estado inválido, pois todo Workpack deve possuir apenas 1 Dashboard

![image](https://github.com/sep-es-br/openpmo-web/assets/40874826/7d827db7-6fd8-411d-8687-875638cb308d)


![image](https://github.com/sep-es-br/openpmo-web/assets/40874826/b4186ff4-f5fd-4ad7-aaec-635df73f9b20)

Foi necessária a exclusão manual de um dos nós do Dashboard para que o sistema funcionasse corretamente.

**Comment by msantosmarcos** [comment]
Cadê o script para exclusão?

**Comment by msantosmarcos** [comment]
não foi resolvido.

**Comment by msantosmarcos** [comment]
Sim, esse problema é recorrente e muito grave, a única forma de identificar é aplicando pontos de log na API.
Emir, esse problema (parecido) aconteceu no Participe e o Gabriel adicionou pontos de log no código da API para identificar em que ponto estava passando objetos inconsistentes para  banco. Em alguns casos esses objetos estão deletando relacionamentos e até mesmo duplicando relacionamentos no banco.
O Gabriel tem que identificar qual ou quais sãos os controles para aplicar esses logs. Presumo que seja no  WorkpackController.java.
Com relação ao script de deleção: nós sabemos fazer.

**Comment by msantosmarcos** [comment]
Emir, o problema voltou acontecer agora, o usuário não consegue enxergar a entrega cadastrada.
O usuários não vão mais inserir registros no sistema, enquanto não for resolvido, ou seja, o sistema vai ser paralisado.

**Comment by efeguri** [comment]
Marcos, a avaliação que temos que fazer (sua parte nesse momento), acontece com todos os usuários? Se sim, consegue reproduzir?
Caso não, vc precisa entender o que o usuário ta fazendo, de preferencia com um projeto criado do zero. 
Referente ao projeto Participe foi uma operação conjunta e o erro foi identificado logo após usuário realizar uma ação no sistema e notificar, somente dessa forma soubemos onde colocar os logs. 
Enfim, o que precisa ser realizado agora, e reproduzir esse bug, enquanto não for reproduzido não tem como atender a demanda de correção.

**Comment by msantosmarcos** [comment]
Preciso falar com um dos seus dev no skype

**Comment by msantosmarcos** [comment]
![image](https://github.com/sep-es-br/openpmo-web/assets/41967259/2f9399fe-e1f3-4a35-979d-35b8d738b58d)

**Comment by da0hn** [comment]
O erro acontecia provavelmente devido à atualização de dados de múltiplos `Steps` ativando o cálculo do `Dashboard`. Ao ativar o cálculo executava uma linha que verificava a existência do `Dashboard`, caso não existisse criava. [Esse comando estava sendo executado independente da verificação de existência do `Dashboard`](https://github.com/sep-es-br/openpmo-api/commit/8ae6d0746af138c57f316217dc4efa4cd23d40d5).

O script abaixo apaga os Dashboards extras que tinham sido criados.

```sql
match (d:Dashboard) where id(d) in [48741, 48742] detach delete d
match (d:Dashboard) where id(d) in [28466] detach delete d
match (d:Dashboard) where id(d) in [28086] detach delete d
```

**Comment by msantosmarcos** [comment]
O problema foi resolvido na origem?

**Comment by da0hn** [comment]
Sim, tinha sido resolvido durante a refatoração do `Dashboard` que foi pedido no novo ciclo e a versão anterior não foi atualizada com essa correção.

**Comment by msantosmarcos** [comment]
resolvido.
