### ISSUE TITLE
Admin - Pessoas: Requisição muito longa ao buscar por nome

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#436]
https://github.com/sep-es-br/openpmo-web/assets/41954965/6ce8c43f-434a-404d-8f8d-7ca912353b13

**Comment by da0hn** [comment]
Esse erro acontece antes de chegar no backend. Como a árvore do Escritório é muito profunda e o escopo não foi alterado para ser mais específico a url gerada possui todos os ids dos Workpacks e isso gera o [código de erro 414](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/414) provido do proxy reverso que está limitando o tamanho da URL.

**Comment by vdcordeiro** [comment]
Não há a necessidade de passar todos os itens de escopo selecionados. Apenas os "pais", uma vez que nesse caso não é possível selecionar um pai sem selecionar os seus filhos. Além disso, no backend a verificação de escopo a partir de uma lista gigante, como é feito atualmente, é mais custosa do que identificar se há um caminho no grafo até algum elemento que conste em uma lista curta. Esse foi um erro de implementação, que deve ser corrigido, pois gera impactos como o da presente issue e da issue #437. 
Como solução paleativa, **mas não definitiva**, sugiro que essa lista de ids seja passada no "body" da requisição, que permite até 9GB.

**Comment by nandobrazil** [comment]
Front - versão atualizada

**Comment by msantosmarcos** [comment]
resolvido.
