### ISSUE TITLE
Lentidão excessiva ao carregar listas longas

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#437]
A paginação não está surtindo o efeito pretendido de acelerar a carga , pois só ocorre no frontend. 

https://github.com/sep-es-br/openpmo-web/assets/41954965/0d984565-db5f-4e76-ae32-b71b697bfd75

**Comment by msantosmarcos** [comment]
Não há a necessidade de passar todos os itens de escopo selecionados. Apenas os "pais", uma vez que nesse caso não é possível selecionar um pai sem selecionar os seus filhos. Além disso, no backend a verificação de escopo a partir de uma lista gigante, como é feito atualmente, é mais custosa do que identificar se há um caminho no grafo até algum elemento que conste em uma lista curta. Esse foi um erro de implementação, que deve ser corrigido, pois gera impactos como o da presente issue e desta issue.

**Comment by msantosmarcos** [comment]
falta ordenar corretamente e falta também desabilitar os controles de paginação e exibir o spinner enquanto carrega a nova página.
Falta exibir o id dos cartões como é padrão do sistema.

**Comment by efeguri** [comment]
Marcos, referente exibir o spinner enquanto carrega a nova página, corrigimos porque entendemos que é bug. O restante é melhoria conforme o comentários realizado pela Camila. Caso deseje que o item seja resolvido, colocar no próximo ciclo.

**Comment by camilaseasky** [comment]
Não é padrão do component de paginação fazer essa desabilitação. Eu alterei para não exibir os controles enquanto estiver carregando. Puxe a nova versão por favor.

**Comment by msantosmarcos** [comment]
resolvido
