### ISSUE TITLE
URGENTE: Projeto inacessível na produção

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#438]
Na produção, o projeto Seger digital sumiu da aba PROJETOS. Continua na EAP, mas ao clicar, não é exibido. Dá um erro.

https://github.com/sep-es-br/openpmo-web/assets/41954965/82ef0bbb-4c0c-4616-be4c-1c3ca42aa209

**Comment by msantosmarcos** [comment]
correção efetuado no banco, no entanto não foi identificado a causa do problema.
