### ISSUE TITLE
Apresentação de carregamento da página errado

### ISSUE THREAD

**Issue by takimyns** [sep-es-br/openpmo-web#440]
Ao entrar no portfólio nos planos ele apresenta a frase "Não há registros a serem exibidos" que é apresentado de forma errônea, logo após há o carregamento do painel de controle. Segue abaixo o vídeo:
![chrome_ejoUek7vVh](https://github.com/sep-es-br/openpmo-web/assets/136747672/3a0e2974-566d-403a-b20e-0a20218a61a3)

**Comment by msantosmarcos** [comment]
resolvido
