### ISSUE TITLE
Erro ao consultar diário

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#441]
Ao consultar o diário de um determinado projeto esta apresentando o erro conforme vídeo abaixo:

https://github.com/sep-es-br/openpmo-web/assets/41967259/adc9f171-3946-4951-a661-76cfaef53a1a

![image](https://github.com/sep-es-br/openpmo-web/assets/41967259/0db77328-4a39-404b-9a3a-d7bde2206bfc)

**Comment by da0hn** [comment]
Ajuste feito #[f469010](https://github.com/sep-es-br/openpmo-web/commit/f469010e777f1c754045ef2249e0960c97ecece1)
