### ISSUE TITLE
Navegação entre abas vertical

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#442]
Quando retornamos para um nível anterior o estado da última seleção não esta sendo respeitado, conforme vídeo abaixo:

https://github.com/sep-es-br/openpmo-web/assets/41967259/9df32099-7b2d-48a6-b88a-30e8d0071e7f

**Comment by efeguri** [comment]
Precisamos que seja melhor detalhado sobre o problema, pois resolvemos o item. Precisamos que coloque um video, explique com melhores detalhes, porque dessa forma não fica claro o que ficou de pendência.

**Comment by msantosmarcos** [comment]
Emir, quando o usuário navega do eixo para a área temática e queira retornar para o eixo, o sistema tem que retornar exatamente no ponto em que ele estava antes.
exemplo: ele clicou na aba propriedades do eixo quando retornar da área para  eixo, o sistema tem que voltar na aba de propriedades e assim sucessivamente para todos os workpack's

**Comment by camilaseasky** [comment]
Ele não vai retornar para a aba propriedades, pois para ir do eixo para a área temática, ele clicou na aba Área Temática, então ao retornar, ele vai para essa aba novamente.

**Comment by msantosmarcos** [comment]
Camila, o sistema sempre esta retornando para a aba Painel de controle.

**Comment by vdcordeiro** [comment]
Esse problema regrediu. Essa navegação já funcionou antes. Veja no vídeo, que não importa a aba selecionada anteriormente, que sempre abre o Painel de Controle.
https://github.com/sep-es-br/openpmo-web/assets/41954965/b5297fc6-b925-4820-8814-6c0cd81c5ee3

**Comment by nandobrazil** [comment]
Boa tarde, segue abaixo vídeo demonstrativo do funcionamento 100%, verificar por favor se em HOM está atualizado com a branch aqui do Github.
OBS.: O teste abaixo foi realizado com o repositório daqui do github (este repositório), e subi um pequeno commit pra gente testar se está refletindo os arquivos no ambiente de HOM.

https://github.com/sep-es-br/openpmo-web/assets/90648889/8f646070-857a-4373-b660-da34f75a4bca

**Comment by msantosmarcos** [comment]
Fernando, vc não entendeu o problema, me liga no skype.

**Comment by nandobrazil** [comment]
Versão atualizada, gostaria de testar no ambiente de vocês a solução que implementamos, como o problema não acontecia localmente, implementamos mais uma solução, então quando rodar o jenkins nos avise aqui por favor!

**Comment by msantosmarcos** [comment]
executado, pode testar.

**Comment by msantosmarcos** [comment]
resolvido.
