### ISSUE TITLE
Busca não esta funcionando corretamente

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#443]
A busca no card de permissões não esta funcionando corretamente, conforme vídeo abaixo:

https://github.com/sep-es-br/openpmo-web/assets/41967259/afa266c5-a200-4d82-be75-0d35a68ff311

**Comment by vdcordeiro** [comment]
O problema também ocorre nas permissões do workpack:

https://github.com/sep-es-br/openpmo-web/assets/41954965/ae803357-de70-4e3b-8f66-330850df913f

**Comment by msantosmarcos** [comment]
O comportamento de busca ainda esta confuso, conforme vídeo abaixo:

https://github.com/sep-es-br/openpmo-web/assets/41967259/37a16238-9df7-43ca-9fe8-af4d99012021

**Comment by da0hn** [comment]
Poderia informar qual é o valor da propriedade `app.searchCutOffScore` definida no `application.properties`. O resultado da pesquisa irá depender do valor setado sendo ele próximo de 0 estará menos preciso e próximo de 1 mais preciso.

O `algoritmo de levenshtein` utilizado na busca textual compara a quantidade de operações que devem ser executadas para transformar uma palavra em outra, por causa disso quanto menor a quantidade de caracteres fornecidos menor é a chance de achar o texto desejado.

**Comment by msantosmarcos** [comment]
app.searchCutOffScore=0.4

**Comment by da0hn** [comment]
Tente diminuir o valor dessa propriedade, é possível verificar qual é o score de cada pessoa retornado olhando o inspecionar. Essa propriedade deve ser calibrada conforme a precisão desejada na pesquisa 

![image](https://github.com/sep-es-br/openpmo-web/assets/40874826/994827fe-c0ef-4447-8c68-e6d4dab0cbf6)


![image](https://github.com/sep-es-br/openpmo-web/assets/40874826/3522454b-45ea-484e-a36b-cbe4e65f637d)

**Comment by msantosmarcos** [comment]
esta faltando ordenar corretamente também.

**Comment by camilaseasky** [comment]
"falta ordenar corretamente e falta também desabilitar os controles de paginação e exibir o spinner enquanto carrega a nova página." Isso já foi feito ontem. Puxar a nova versão.

**Comment by msantosmarcos** [comment]
Ainda não entendi essa busca, o Gabriel me explicou que existe uma variável "app.searchCutOffScore=0.1" no application.properties em que quanto menor o valor mais aproximada fica a busca.
Além disso os controles de paginação não estão desabilitando quando a paginação esta em processamento.
https://github.com/sep-es-br/openpmo-web/assets/41967259/cbaebc01-4967-4f5c-a8b4-efb74a94dad6

**Comment by camilaseasky** [comment]
"Além disso os controles de paginação não estão desabilitando quando a paginação esta em processamento." Não é padrão do component de paginação fazer essa desabilitação. Eu alterei para não exibir os controles enquanto estiver carregando. Puxe a nova versão por favor.
