### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#447]
Curva S "caindo" o VA. Isso não faz sentido, uma vez que os valores da Curva S são acumulados mês a mês. Não há valor negativo no cronograma.
![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/b3464438-7ea4-4691-a4fa-7a1ea52d9645)

![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/764f3cf0-e4f7-465f-9801-0ade567d2f9a)

Além disso, ao passar o mouse sobre os pontos da curva S, aparecem valores com formatação incorreta. Por exemplo: 2.348.000.02,00

**Comment by efeguri** [comment]
Precisamos saber qual deveria ser o valor agregado correto nos meses de julho e agosto.

**Comment by vdcordeiro** [comment]
> Precisamos saber qual deveria ser o valor agregado correto nos meses de julho e agosto. Também vamos precisar de um dump para analisarmos o exemplo mencionado.

Lembrando que a curva S apresenta valores acumulados mês a mês. Não fiz as contas para saber o valor agregado dos meses, mas para a curva "descer" como está no gráfico, os valores mensais tem que ser negativos, o que certamente está errado, já que não temos custos negativos e nem escopo negativo na entrega.
Vamos mandar um dump da homologação.

**Comment by camilaseasky** [comment]
Tem que ser feita alguma alteração para forçar o recálculo dos valores do dashboard.

**Comment by msantosmarcos** [comment]
foi um equivoco

**Comment by msantosmarcos** [comment]
fizemos uma alteração e ainda não funcionou corretamente a disposição do gráfico.

**Comment by camilaseasky** [comment]
por favor colocar o print de como ficou.

**Comment by efeguri** [comment]
Marcos, precisamos de detalhes para que possamos entender o que de fato esta ocorrendo, uma vez que ajustamos o bug e colocarmos o fixed na Issues.
Precisamos de mais detalhes em todos as Issues.

**Comment by msantosmarcos** [comment]
Lembrando que a curva S apresenta valores acumulados mês a mês. Não fiz as contas para saber o valor agregado dos meses, mas para a curva "descer" como está no gráfico, os valores mensais tem que ser negativos, o que certamente está errado, já que não temos custos negativos e nem escopo negativo na entrega.
Vamos mandar um dump da homologação.

![image](https://github.com/sep-es-br/openpmo-web/assets/41967259/251f8b12-2ae5-48be-973c-de10feae1be7)

**Comment by camilaseasky** [comment]
aguardando o dump.

**Comment by da0hn** [comment]
Ajustado no [commit](https://github.com/sep-es-br/openpmo-api/commit/8ae6d0746af138c57f316217dc4efa4cd23d40d5)

**Comment by msantosmarcos** [comment]
resolvido.
