### ISSUE TITLE
Problema ao inserir informação no Diário

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#448]
Estou tendo esse problema no momento de inserir uma informação no Diário, contendo arquivos. Conforme imagem abaixo:

![WhatsApp Image 2023-08-21 at 12 21 07](https://github.com/sep-es-br/openpmo-web/assets/41967259/44f42d01-7a6b-400a-9156-e4675f840c3a)

**Comment by icarosbmartins** [comment]
Poderia me passar o usuário que você está usando? Vamos verificar as permissões que ele tem.

**Comment by icarosbmartins** [comment]
Poderia também enviar um dump do banco?

**Comment by msantosmarcos** [comment]
[openpmo-p.zip](https://github.com/sep-es-br/openpmo-web/files/12422129/openpmo-p.zip)

**Comment by camilaseasky** [comment]
Problema resolvido. Precisa puxar a versão do front e atualizar.

**Comment by msantosmarcos** [comment]
Camila, o que de fato estava acontecendo no código do front para causar esse problema?

**Comment by vdcordeiro** [comment]
Camila, você conseguiu reproduzir o erro aí? É que esse problema foi reportado pela produção e não sabemos se ocorria em qualquer situação ou em alguma específica.

**Comment by camilaseasky** [comment]
Conseguimos reproduzir. Esse problema era intermitente, pois ocorria na passagem de parâmetro pela inputProperty para o component. Em alguns momentos não atualizava. Corrigimos o problema e não deve mais ocorrer.

**Comment by msantosmarcos** [comment]
resolvido
