### ISSUE TITLE
Imagem corrompida na tela de login

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#449]
Na página de login, a logo do OpenPMO foi alterada e as letras "n" e "P" estão se sobrepondo.

![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/31fd6a83-f8c8-414d-b9ec-908fea56191f)

**Comment by nandobrazil** [comment]
O problema ocorre na imagem SVG que vocês colocaram na branch aqui do github, no nosso ambiente não temos como reproduzir:
![image](https://github.com/sep-es-br/openpmo-web/assets/90648889/95ab9932-2d2c-4605-9651-f25b6d1c65c1)

Verifiquei que a imagem está desse jeito mesmo no projeto, não sendo um problema de estilização ou estrutura.

**Comment by msantosmarcos** [comment]
Essa não é a fonte correta. Esse SVG esta pegando a fonte errada, verifique a fonte no código do svg e a instale na sua máquina pra visualizar o problema da sobreposição. Note que o PNG apresenta a fonte correta

**Comment by vdcordeiro** [comment]
Srs, sugiro que quando a "question" não for resolvida aqui de primeira, seja feito contato telefonico, para agilizar a solução.

Não tem alteração de fonte. A fonte utilizada pelo .svg é e continuará sendo a "Days One", como se pode ver no código do .svg. O desenvolvedor que tirou o print do svg não deve ter percebido que está sem essaa fonte instalada na máquina dele para a correta visualização. Daí quando ele abre o svg, na aplicação de edição, parece que está correto, pois na falta da fonte na máquina, a aplicação pega alguma fonte padrão e exibe o svg com ela. Nos navegadores não é necessário instalar a fonte, pois é uma fonte padrão para todos eles.
Certamente isso aconteceu com alguém aí no passado e a pessoa acabou alterando o arquivos achando que iria corrigir o problema. Sem a fonte correta, as letras ficaram muito espaçadas e a pessoa as juntou, sem perceber que na fonte correta estava certo e agora ficou sobrepondo.

Emir, eu consertar isso em 1 minuto, mas combinamos de que a nossa equipe não iria mexer no código.

**Comment by nandobrazil** [comment]
Versão atualizada.

**Comment by msantosmarcos** [comment]
resolvido.

**Comment by vdcordeiro** [comment]
Não está resolvido. As letras continuam sobrepostas em máquinas que possuem a fonte correta: Days One. Em clientes que não possuem a fonte Days One instalada, como é o caso da máquina do Marcos e também a do Fernando(provavelmente), as letras não se sobrepõem, mas são exibidas em outra fonte.

Avaliando melhor, percebi que na verdade a fonte Days One não está presente por default nos navegadores. Para solucionar o problema, ao invés de incluir o svg, a página precisa incluir a imagem utilizando o arquivo png, já disponível e correto no projeto em src/assets/images/logo-openpmo-horizontal.png.
![logo-openpmo-horizontal](https://github.com/sep-es-br/openpmo-web/assets/41954965/7af7046d-86c3-4861-9f41-de79b6ba7319)

**Comment by msantosmarcos** [comment]
resolvido.
