### ISSUE TITLE
Identificamos um Person vazio(com as propriedades vazias)

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#450]
Identificamos um Person vazio(com as propriedades vazias), conforme vídeo abaixo:

https://github.com/sep-es-br/openpmo-web/assets/41967259/007f224f-58c4-442f-b6c2-02bba3f74fa6

**Comment by msantosmarcos** [comment]
Como isso era possível, já que o nome vem do acesso cidadão? 
O acesso cidadão esta enviando vazio?

**Comment by camilaseasky** [comment]
Na visualização das persons que são usuários também estava permitindo gravar o nome pelo qual deseja ser chamado com espaços em branco somente.

**Comment by msantosmarcos** [comment]
resolvido.
