### ISSUE TITLE
O programa e seus respectivos projetos sumiram do sistema

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#451]
O programa: "Empregar ES" não esta sendo mais exibido no sistema com seus respectivos projetos:
1. Crédito para empreender
2. Inova Mercado
3. Capacitar para empreender

**Comment by camilaseasky** [comment]
Precisamos do dump do banco para verificarmos.

**Comment by icarosbmartins** [comment]
Fizemos os testes no nosso ambiente com o dump recebido e verificamos que o programa "Empregar ES" com os seus respectivos projetos estão sendo exibidos normalmente. Usamos um usuário administrador. Qual o tipo de usuário vocês estão usando para testar? Caso este usuário não seja administrador, onde ele tem permissão (Office, Plan, Workpack)?

**Comment by msantosmarcos** [comment]
cancelada, não houve erro.
