### ISSUE TITLE
Menu vertical não esta carregando.

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#452]
Ao navegar no sistema o menu vertical não esta sendo atualizado, quando o usuário tem permissão apenas em um projeto, 
conforme vídeo abaixo: 
O problema não ocorre com usuários administradores ou com permissões no escritório.

https://github.com/sep-es-br/openpmo-web/assets/41967259/ae0a66b9-b01c-44a8-ac8c-0d1901049479

**Comment by camilaseasky** [comment]
Testamos aqui com um usuário que tem acesso somente ao projeto e carregou o menu normalmente. Por favor, faça um desde o início da navegação, quando o usuário acessa o plano e verifique a aba console e a aba network.

**Comment by camilaseasky** [comment]
Isso está acontecendo em qual ambiente?

**Comment by msantosmarcos** [comment]
na produção

**Comment by camilaseasky** [comment]
Essa situação está acontecendo na homologação também?

**Comment by msantosmarcos** [comment]
não, só acontece na produção. vi agora.

**Comment by efeguri** [comment]
Precisa verificar se os ambientes estão com a mesma versão, pois temos corrigido várias issues e provavelmente esta no seu ambiente de homologação.

**Comment by takimyns** [comment]
Segue abaixo o vídeo:
![chrome_RLvG9nEb2F](https://github.com/sep-es-br/openpmo-web/assets/136747672/9f29afe2-f1fe-4122-8070-8e69ae95e3b6)

**Comment by msantosmarcos** [comment]
Emir, agora consegui reproduzir o mesmo erro no ambiente de homologação, ou seja, também acontece neste ambiente.
Para o erro acontecer o usuário tem permissão somente em um projeto.

**Comment by camilaseasky** [comment]
Marcos, não estamos conseguindo simular esse erro em nosso ambiente. Poderia me dar acesso na homologação ao mesmo projeto que vc de para este usuário?
Outra pedido: preciso que vc abra a aba de network antes de clicar no plano. Esse é o momento em que ele faz a requisição para trazer o menu. Quero ver se ele está fazendo ou não. A url é /menus/portfolio

**Comment by msantosmarcos** [comment]
preciso do seu CPF

**Comment by camilaseasky** [comment]
87742411172
Por favor passe o usuário que estava dando o erro neste banco de produção que vc anexou anteriormente.

**Comment by takimyns** [comment]
![chrome_JGruqdfRqI](https://github.com/sep-es-br/openpmo-web/assets/136747672/738df68c-723d-4e43-99b9-7a08577d123c)

**Comment by msantosmarcos** [comment]
https://hom.pmo.es.gov.br/

**Comment by icarosbmartins** [comment]
Por favor passe o usuário que estava dando o erro neste banco de produção que vc anexou anteriormente.

**Comment by vdcordeiro** [comment]
Todos os usuários com as características de permissões descritas estão apresentando esse erro.
Assumindo um modelo de plano como a da homologação, com portfólio > Área > Programa > Projeto > ...
O problema ocorre com qualquer usuário que não têm outras permissões em níveis superiores, apenas num projeto.

**Comment by icarosbmartins** [comment]
Por favor, atualizem o backend.

**Comment by takimyns** [comment]
verificado com sucesso.
