### ISSUE TITLE
Pessoas: Lentidão e timeout na carga

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#453]
A consulta de pessoas do escritório demora tanto na produção, que a requisição cai por timeout. 
https://github.com/sep-es-br/openpmo-web/assets/41954965/0d864833-8a8e-44fe-a821-6b8751f62f55

A busca por um nome específico está levando mais de 40 segundos:
https://github.com/sep-es-br/openpmo-web/assets/41954965/9878e474-615d-4bcf-9da5-6d42afa574d3

**Comment by da0hn** [comment]
Antes:

![image](https://github.com/sep-es-br/openpmo-web/assets/40874826/f61bfc17-f1cf-4f2b-89e5-58741c16c92a)

Depois:

![image](https://github.com/sep-es-br/openpmo-web/assets/40874826/4227f9f0-3faf-4dcd-9e54-fae44da1fc89)

Foi feita a alteração das queries nos dois endpoints para diminuir o tempo de resposta, porém não foi possível diminuir o tempo de resposta do endpoint que retorna a lista de pessoas para menos de 12s sendo esse o tempo de resposta do banco de dados.

**Comment by vdcordeiro** [comment]
12 seg ainda é muito alto para esse tipo de consulta.
Se o banco de dados está consumindo todo esse tempo, é porque tem algo errado na query cypher.

Se a query que está sendo usada é a  List<AllPersonInOfficeQuery> findAllFilteringBy(), realmente tem muita coisa errada. Pelo código dá para ver que está ineficiente.
- Está fazendo verificação id por id numa lista que pode ser gigante (linha 109). Deveria verificar numa lista de ids pais somente.
- Não está fazendo paginação
- Alguns "OPTIONAL MATCHES" (linhas 51, 52 e 53) e variáveis em "WITH" (linhas 56, 57, 58) me parecem desnecessários:

**Comment by da0hn** [comment]
A paginação não está sendo feita na `query` por que o tempo de execução sai de 12~13s para 22s já que tem que executar a `query` e a `countQuery`. Ao invés de utilizar a paginação embutida do Spring estou utilizando o objeto `Streamable` que trabalha com `stream` de dados e não traz todas as informações assim que a `query` é chamada sendo possível paginar sem carregar todo o resultado da consulta no java.

Outro detalhe importante é que não há `optional match` nessa consulta, ao invés de filtrar os dados no `where` estou coletando com o operador `collect` e aplicando um filtro nos registros coletados visto que utilizando o profiling do Neo4j ele está agregando milhões de registros e só existem 435 pessoas nesse escritório.

Ao carregar a página pela primeira vez não é informado os escopos de `plano` e `workpack` e os outros parâmetros são enviados para não filtrar a pessoa por algum parâmetro especifico.


![image](https://github.com/sep-es-br/openpmo-web/assets/40874826/2e69c793-a57e-466e-b441-7fa91419676f)

```sql
:params 
{
  "officeScope": 2,
  "name": null,
  "userFilter": 'ALL',
  "stakeholderFilter": 'ALL',
  "ccbMemberFilter": 'ALL',
  "workpackScope": [],
  "planScope": []
}
```

```sql
PROFILE
MATCH (person:Person)-[isInContactBookOf:IS_IN_CONTACT_BOOK_OF]->(office:Office)<-[:IS_ADOPTED_BY]-(plan:Plan)<-[:BELONGS_TO]-(workpack:Workpack)
WHERE id(office)=$officeScope 
WITH person, office, isInContactBookOf, plan, workpack, collect(distinct person) as personList
UNWIND personList as uniquePerson
WITH office, uniquePerson, isInContactBookOf, plan, workpack
WHERE 
    ( 
        toLower(uniquePerson.fullName) CONTAINS toLower($name) OR 
        toLower(uniquePerson.name) CONTAINS toLower($name) OR 
        $name IS NULL 
    ) 
    AND 
    ( 
        ('ALL'=$userFilter OR $userFilter IS NULL) OR 
        ('USER'=$userFilter AND exists((uniquePerson)-[:IS_AUTHENTICATED_BY]->(:AuthService))) OR 
        ('NON_USER'=$userFilter AND NOT exists((uniquePerson)-[:IS_AUTHENTICATED_BY]->(:AuthService))) 
    ) 
    AND 
    ( 
      ('ALL'=$stakeholderFilter OR $stakeholderFilter IS NULL) OR 
      ('STAKEHOLDER'=$stakeholderFilter AND exists((uniquePerson)-[:IS_STAKEHOLDER_IN]->(workpack))) OR 
      ('NON_STAKEHOLDER'=$stakeholderFilter AND NOT exists((uniquePerson)-[:IS_STAKEHOLDER_IN]->(:Workpack))) 
    ) 
    AND 
    ( 
      ('ALL'=$ccbMemberFilter OR $ccbMemberFilter IS NULL) OR 
      ('CCB_MEMBERS'=$ccbMemberFilter AND exists((uniquePerson)-[:IS_CCB_MEMBER_FOR]->(workpack))) OR 
      ('NON_CCB_MEMBERS'=$ccbMemberFilter AND NOT exists((uniquePerson)-[:IS_CCB_MEMBER_FOR]->(:Workpack))) 
    ) 
    AND 
    ( 
        ( 
            ( 
                $workpackScope IS NULL OR $workpackScope = [] AND 
                (exists((person)-[:IS_STAKEHOLDER_IN]->(workpack)) OR exists((uniquePerson)-[:IS_CCB_MEMBER_FOR]->
(workpack))) 
            ) 
            OR 
            ( 
                $workpackScope IS NOT NULL OR $workpackScope <> [] 
                AND 
                (exists((uniquePerson)-[:IS_STAKEHOLDER_IN]->(workpack)) OR exists((uniquePerson)-[:IS_CCB_MEMBER_FOR]->
(workpack))) 
                AND 
                id(workpack) IN $workpackScope 
            ) 
        ) 
        OR 
        ( 
            ( 
                $planScope IS NULL OR $planScope = [] AND 
                exists((uniquePerson)-[:CAN_ACCESS_PLAN]->(plan)) 
            ) 
            OR 
            ( 
                $planScope IS NOT NULL OR $planScope <> [] AND 
                exists((uniquePerson)-[:CAN_ACCESS_PLAN]->(plan)) AND 
                id(plan) IN $planScope 
            ) 
        ) 
        OR 
        ( 
            ( 
                $workpackScope IS NULL OR $workpackScope = [] AND 
                exists((uniquePerson)-[:CAN_ACCESS_WORKPACK]->(workpack)) 
            ) 
            OR 
            ( 
                $workpackScope IS NOT NULL OR $workpackScope <> [] AND 
                exists((uniquePerson)-[:CAN_ACCESS_WORKPACK]->(workpack)) AND 
                id(workpack) IN $workpackScope 
            ) 
        ) 
        OR 
        ( 
            exists((uniquePerson)-[:CAN_ACCESS_OFFICE]->(office)) 
        ) 
    ) 
RETURN DISTINCT uniquePerson, isInContactBookOf, office, [
  [ [ (uniquePerson)<-[isPortraitOf:IS_A_PORTRAIT_OF]-(avatar:File) | [isPortraitOf, avatar] ] ] 
] 
```

**Comment by vdcordeiro** [comment]
O collect é um procedimento muito custoso. Não pode ser usado para filtrar grandes quantidades de nós. 
A seleção deve ser feita nos matches com expressões tipo ()-[]->(). 
Hoje à tarde vou estudar essa query e a ferramenta de paginação do neo4j e depois volto a comentar aqui.

**Comment by vdcordeiro** [comment]
Tenta algo assim: (retornou em 135 ms)

```
CALL {
with 
    'ALL' as _userFilter,
    'ALL' as _stakeholderFilter,
	'ALL' as _ccbMemberFilter,
	2 as _office, 
	[2,182,2572] as _list, 
	null as _name
	MATCH (p:Person)-[:IS_IN_CONTACT_BOOK_OF]->(o:Office)
	MATCH (p)-[:CAN_ACCESS_OFFICE|CAN_ACCESS_PLAN|CAN_ACCESS_WORKPACK|IS_STAKEHOLDER_IN|IS_CCB_MEMBER_FOR]->()-[:IS_IN*0..]->(e)
	WHERE id(o)=_office and id(e) in _list
	and (_name is null or
		(apoc.text.clean(p.name) contains apoc.text.clean(_name) or apoc.text.clean(p.fullName) contains apoc.text.clean(_name))
	)
	and 
		( 
			('ALL'=_userFilter OR _userFilter IS NULL) OR 
			('USER'=_userFilter AND exists((p)-[:IS_AUTHENTICATED_BY]->(:AuthService))) OR 
			('NON_USER'=_userFilter AND NOT exists((p)-[:IS_AUTHENTICATED_BY]->(:AuthService))) 
		)
	AND 
	( 
		('ALL'=_stakeholderFilter OR _stakeholderFilter IS NULL) OR 
		('STAKEHOLDER'=_stakeholderFilter AND exists((p)-[:IS_STAKEHOLDER_IN]->()) OR 
		('NON_STAKEHOLDER'=_stakeholderFilter AND NOT exists((p)-[:IS_STAKEHOLDER_IN]->())) 
		)
	)
	AND 
	( 
		('ALL'=_ccbMemberFilter OR _ccbMemberFilter IS NULL) OR 
		('CCB_MEMBERS'=_ccbMemberFilter AND exists((p)-[:IS_CCB_MEMBER_FOR]->())) OR 
		('NON_CCB_MEMBERS'=_ccbMemberFilter AND NOT exists((p)-[:IS_CCB_MEMBER_FOR]->())) 
	) 
	return distinct p
	order by apoc.text.clean(p.name)
	skip 0 limit 30
}
OPTIONAL MATCH (p)<-[isPortraitOf:IS_A_PORTRAIT_OF]-(avatar:File)
return p, avatar
```

**Comment by msantosmarcos** [comment]
Camila,  a edição esta caindo por time-out,  conforme imagem e vídeo abaixo
https://github.com/sep-es-br/openpmo-web/assets/41967259/03020e07-3c1b-4ce3-8f36-f953d9b33eea

![image](https://github.com/sep-es-br/openpmo-web/assets/41967259/e5e8c4f4-bd2f-4776-9272-f095e2c1f86b)

**Comment by msantosmarcos** [comment]
Resolvido.
