### ISSUE TITLE
Menu lateral: Erros ao afixar o menu

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#459]
https://github.com/sep-es-br/openpmo-web/assets/41954965/b4a33eb4-299c-4cd8-9fcd-19ba74cd75ff

https://github.com/sep-es-br/openpmo-web/assets/41954965/25b59b37-c573-469d-8fc8-17f2fbe935d2

**Comment by camilaseasky** [comment]
Versão do front atualizada.

**Comment by msantosmarcos** [comment]
Comportamento ainda não esta adequado, conforme vídeo abaixo:
https://github.com/sep-es-br/openpmo-web/assets/41967259/11381968-6989-4036-a602-8235b806335d

**Comment by vdcordeiro** [comment]
Além de não aparecer os itens do menu ao afixar, como no video do Marcos acima, ao afixar e desafixar o menu, todas as rquisições são refeitas, o que é desnecessário e compromete ainda mais a lentidão já observada no sistema (#422).
