### ISSUE TITLE
Propriedades com poucos metadados não expandem para a linha inteira

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#46]
Na criação/edição de modelo de pacote de trabalho, ao expandir uma propriedade, a área da propriedade deve ocupar todo o espaço horizontal, alinhada com as demais. Isso não ocorre com as propriedades com poucos metadados.  
https://www.loom.com/share/59ff5b7c91df4125b369a6339ac58eae

**Comment by vdcordeiro** [comment]
https://www.loom.com/share/52b7b97ce0cf47e0875e0694c494082d

**Comment by alanrodrigo** [comment]
Altura dos quadrinhos diferentes.

![image](https://user-images.githubusercontent.com/42146539/111326895-b27ae600-864b-11eb-99f0-cba6bd42217d.png)

**Comment by vdcordeiro** [comment]
Resolvido
