### ISSUE TITLE
Erro ao gerar relatório 

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#460]
Erro ao gerar relatório no ambiente de homologação, conforme vídeo abaixo:

obs.:
 {
    "erro": "erro.negocio$Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class net.sf.jasperreports.engine.util.JRStyledTextParser"
}

https://github.com/sep-es-br/openpmo-web/assets/41967259/7f978e67-fc57-48ab-b4a4-36bfe466be08

**Comment by efeguri** [comment]
Marcos, 

Verificar no arquivo dockerfile a existência dessa linha: RUN apk add --no-cache fontconfig ttf-dejavu

Caso não, favor inclui-la. E refazer o teste novamente. Caso a linha estiver, por favor enviar os seguintes itens:

- Arquivo que utilizou para fazer o relatório
- banco de dados (dump)

**Comment by msantosmarcos** [comment]
resolvido.
