### ISSUE TITLE
Lentidão na carga do Dashboard

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#463]
3.1. Calcular e listar no menu provisoriamente considerando apenas workpacks originais
        - Enviada à equipe query para o cálculo rápido de "todos" os workpacks, não apenas os originais, agrupados por modelo.
        - Enviada à equipe exemplo de query que retorna os nós filhos e netos. Ordenação a ser feita na api.
   3.2. Criar IS_LINKED_TO com descendentes
        - A equipe fará em seguida, após 3.1.

ref. #422

**Comment by camilaseasky** [comment]
Foi feita a retirada do menu temporariamente.

**Comment by camilaseasky** [comment]
Atualizada a versão do front e do back com a implementação do menu dos cards de workpackModel do dashboard.

**Comment by vdcordeiro** [comment]
Parece que só faltou a ordenação:
![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/00201d42-c23a-4263-8d19-9650537b0a56)

**Comment by vdcordeiro** [comment]
Outro problema detectado com essa release: Os contadores de workpacks do painel estão repetindo os cards dos modelos:
![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/d1cac17d-ff73-44f3-8022-7fc3a4f113c2)

**Comment by camilaseasky** [comment]
Isso é porque estes modelos estão em níveis diferentes da hierarquia (foram reutilizados). Então estes workpacks contados não são 'irmãos'. Estamos ordenando os cards por níveis.

**Comment by vdcordeiro** [comment]
Eu sei... mas está errado né?

**Comment by vdcordeiro** [comment]
Esse problema não foi resolvido:
![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/908b80e7-8f5b-4acb-91f4-6ff679d7e63e)

**Comment by msantosmarcos** [comment]
resolvido.
