### ISSUE TITLE
erro ao carregar o avatar

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#465]
O endpont que carrega o avatar esta caindo por time-out, além de existir um outro endpont para listar offices, que tb cai por time-out, conforme vídeo e imagem abaixo:

https://github.com/sep-es-br/openpmo-web/assets/41967259/fca4a9d0-f074-4a3d-8966-95f131ad886d

![image](https://github.com/sep-es-br/openpmo-web/assets/41967259/9daeb357-3880-405c-ab8e-5574e54b6b91)

**Comment by vdcordeiro** [comment]
Resolvido
