### ISSUE TITLE
Erro ao editar o modelo de relatório

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#466]
Ao editar o modelo de relatório na área de gestão que é vermelha, muda para a cor azul, conforme vídeo abaixo:

https://github.com/sep-es-br/openpmo-web/assets/41967259/e5f521a0-74f0-4b43-9f19-1e3a0cc7e61e

**Comment by camilaseasky** [comment]
Favor puxar somente nova versão do front.

**Comment by msantosmarcos** [comment]
resolvido.
