### ISSUE TITLE
Erro após o logon

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#467]
Erro ao trocar de usuário, conforme vídeo abaixo:

https://github.com/sep-es-br/openpmo-web/assets/41967259/7f663add-ea0c-47c3-b01b-14423b3a18c3

![image](https://github.com/sep-es-br/openpmo-web/assets/41967259/daaaf68c-e307-44cb-bf27-d60f9ce7f714)

**Comment by vdcordeiro** [comment]
O problema não foi resolvido na última versão do dia 6/9.
Para ser algum problema com o salvamento/recuperação da última página visitada. (melhoria #424)
- A mensagem de erro não ocorre quando usamos janela anônima. Nesse caso, ao retornar, sempre volta para a página inicial (offices). De acordo com a melhoria #424 isso está errado, pois essa informação estará no banco, associada ao usuário. Independe se a janela é anonima ou não.
- Em janelas não anônimas ao retornar à aplicação, após simplesmente ter fechado a aba do navegador e abrir outra, a aplicação não retorna à última página visitada, mas sim à página que estava na última vez que fez logoff. O salvamento da informação deve ser feito ao carregar um novo workpack/plano/escritório e não apenas no logoff.
- Em janelas não anônimas, ao retornar à aplicação após um logoff, trocando ou não o usuário, o erro e a mensagem ocorrem. Parece que a aplicação tenta carregar um plano de id 0(zero), não consegue e cai na página de novo plano.

**Comment by vdcordeiro** [comment]
Coloquei como critical, pois precisamos resolver antes de liberar a versão para a produção.

**Comment by camilaseasky** [comment]
Corrigido o problema. Retornamos a implementação do retorno para o ultimo workpack/plan/office. Podem puxar a versão nova do front.

**Comment by vdcordeiro** [comment]
Verificado
