### ISSUE TITLE
Lentidão: Requisições multiplicadas

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#470]
Ao carregar um workpack, ao menos um endpoint (não verifiquei se acontece com outros) é acionado diversas vezes.

https://github.com/sep-es-br/openpmo-web/assets/41954965/5d7430a4-c71d-45b3-ae01-c8f766b459ac

**Comment by efeguri** [comment]
Conforme reunião em 19/09/2023 sobre o problema apresentado no video acima, não conseguimos reproduzir o erro acima, mesmo com a teoria de alterar para o mobile as requisições não foram multiplicadas. Solicitamos que se conseguir reproduzir o erro para podermos analisar.

**Comment by vdcordeiro** [comment]
Verificado que o comportamento ocorre quando é feito o redimensionamento da página pelo usuário, com o chaveamento para a versão mobile. Embora indesejável, como este é um cenário eventual e raro de acontecer na prática, o impacto para o sistema é irrelevante. Por isso estou fechando esta issue, mesmo sem solução.
