### ISSUE TITLE
Diário: permissão negada ao inserir informação no diário

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#471]
Ao inserir uma informação no diário de uma entrega, o sistema diz que o usuário não possui permissão, conforme imagem abaixo:
Usuáro: Ricardo Lechenacoski Silva;
id: 38943
obs.: Este problema voltou a acontecer.
![WhatsApp Image 2023-09-11 at 14 36 25](https://github.com/sep-es-br/openpmo-web/assets/41967259/91282abf-d2b0-41c0-81df-9741c2ed204f)

**Comment by icarosbmartins** [comment]
Você poderia reproduzir o bug novamente e nos enviar a requisição com os parâmetros que estão sendo passados para o back?

**Comment by msantosmarcos** [comment]
![WhatsApp Image 2023-09-12 at 16 29 28](https://github.com/sep-es-br/openpmo-web/assets/41967259/a7854b7d-1028-4870-afb8-9b05ae47da2c)
![WhatsApp Image 2023-09-12 at 16 28 57](https://github.com/sep-es-br/openpmo-web/assets/41967259/445c1bf0-e60e-4520-935f-b6509cd7a4f1)
![WhatsApp Image 2023-09-12 at 16 28 22 (1)](https://github.com/sep-es-br/openpmo-web/assets/41967259/060b7fc5-f814-4f39-90f8-283ce3863b76)
![WhatsApp Image 2023-09-12 at 16 28 22](https://github.com/sep-es-br/openpmo-web/assets/41967259/f0faf524-dc4c-445b-8595-b6a01d53abcd)

**Comment by msantosmarcos** [comment]
resolvido.

**Comment by msantosmarcos** [comment]
Camila, o usuário relatou que esse problema passou a acontecer quando o mesmo importou um projeto para esse subprograma.
![WhatsApp Image 2023-09-18 at 11 52 23](https://github.com/sep-es-br/openpmo-web/assets/41967259/77ff16b4-ecdc-4690-88f7-9eca1e326fbf)

**Comment by msantosmarcos** [comment]
resolvido
