### ISSUE TITLE
O sistema esta travando e só retorna após reiniciar o contanier.

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#474]
A princípio o sistema esta travando(em média três vezes ao dia) para os usuários, porém continua com um processamento alto e parece estar se comunicando com o banco de dados.
Após reiniciar o sistema, o processamento volta ao normal e torna se acessível para os usuários.

obs.: O último deploy foi realizado hoje (13/09/2023 às 10:00)

observamos também que ao utilizar a ferramenta de monitoramento ctop(monitoramento de containers) o número de threads que API utiliza tem aumentado excessivamente, chegando a dobrar a carga total de processamento da máquina, após realizar um consulta simples de workpacks.

segue abaixo o log de hoje e imagem do erro:

![WhatsApp Image 2023-09-13 at 11 18 41](https://github.com/sep-es-br/openpmo-web/assets/41967259/925b2490-f76e-4118-9f95-de8bcfeb2198)

[LOG_OpenPMO_API_Producao_20230913_1120.txt](https://github.com/sep-es-br/openpmo-web/files/12598658/LOG_OpenPMO_API_Producao_20230913_1120.txt)

**Comment by vdcordeiro** [comment]
O restart do container da API tem ocorrido na produção, diversas vezes, e de forma automática durante o dia, deixando a aplicação fora do ar por alguns minutos a cada restart. Em geral, a aplicação começa a ficar lenta com a utilização e o container da API chega a consumir 12GB de memória (tudo disponível), com umas 500 trheads na fila, até que acaba restartando sozinho.

Acredito que isso ocorra em decorrência dos recálculos do dashboard, disparados a cada edição nas entregas e marcos críticos.

**Comment by msantosmarcos** [comment]
resolvido
