### ISSUE TITLE
Impossível desfavoritar workpack sem permissão

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#476]
Depois que um usuário perde a permissão de acesso a um workpack que estava favoritado, ele não consegue mais desfavoritar, embora apareça a mensagem oferecendo essa possibilidade.

https://github.com/sep-es-br/openpmo-web/assets/41954965/7420c63f-b90c-43ed-808f-36f4004a7d24

Observe ainda que o breadcrumb foi montado incorretamente no retorno do usuário.

**Comment by msantosmarcos** [comment]
resolvido.
