### ISSUE TITLE
Gráfico de EVA não esta sendo exibido

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#477]
Fui no workpackModel e coloquei a EVA para ser exibida nos workpacks, no entanto não apareceu nos workpacks abaixo do projeto.

OBS.: tem linha de base

https://github.com/sep-es-br/openpmo-web/assets/41967259/f44f202d-d09b-489e-8cd6-dcf2ea72315b

**Comment by icarosbmartins** [comment]
Houve um erro no cálculo dos _dashboards_ e agora foi corrigido. No entanto, os _dashboards_ presentes no banco precisam ser recalculados para que a mudança tenha efeito. Isso pode ser feito por meio da requisição `POST /dashboards/purge` em um momento que o sistema não estiver sendo muito utilizado.

**Comment by msantosmarcos** [comment]
resolvido
