### ISSUE TITLE
Lentidão ao criar workpack

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#478]
Lentidão ao criar etapa, conforme vídeo abaixo:

obs.: duração de 13s pra criar

https://github.com/sep-es-br/openpmo-web/assets/41967259/b8eca5b0-6e26-42eb-b1e6-023e5872ded3

**Comment by vdcordeiro** [comment]
Alterado o título, pois o problema ocorre na criação de qualquer workpack.

**Comment by msantosmarcos** [comment]
problema continua, agora pouco mais de 20s

**Comment by msantosmarcos** [comment]
resolvido
