### ISSUE TITLE
Erro ao criar marco crítico

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#479]
Erro ao criar marco crítico, conforme vídeo abaixo:

obs.: o usuário só tem permissão em um projeto.

https://github.com/sep-es-br/openpmo-web/assets/41967259/c9c55ef5-e8bb-4164-982d-72b7354bc2dc

**Comment by camilaseasky** [comment]
Esse é o mesmo problema da criação da etapa. Na verdade o problema está no save do workpack. Estamos investigando.
