### ISSUE TITLE
Domínio tem múltiplos níveis mas seletor só exibe um nível

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#48]
Configurei um domínio com 3 níveis: Região, Município e Bairro. Ao utilizá-lo numa propriedade do tipo localidade, na criação/edição de um modelo de workpack, o metadado "Default value" exibe todos em um único nível.
![image](https://user-images.githubusercontent.com/41954965/108781426-9c946c80-7548-11eb-8fdf-5e32abd892b0.png)

**Comment by vrcristo1980** [comment]
Acordamos que essa alteração será implementada na próxima release.

**Comment by camilaseasky** [comment]
Alteração implementada e disponível para testes.

**Comment by msantosmarcos** [comment]
resolvido.
