### ISSUE TITLE
Lentidão excessiva ao expandir EAP

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#483]
Lentidão excessiva ao expandir EAP, conforme vídeo abaixo:

https://github.com/sep-es-br/openpmo-web/assets/41967259/ac02a873-0ed6-496c-8387-d74947e95e53

**Comment by vdcordeiro** [comment]
O "Expandir tudo" da EAP **do portfólio** está dando "erro de negócio". Nos demais workpacks, o expandir funciona bem, e rápido.
https://github.com/sep-es-br/openpmo-web/assets/41954965/ec92f12d-5985-42d3-bb2d-84e089434664

**Comment by vdcordeiro** [comment]
Resolvido
