### ISSUE TITLE
Projetos não estão sendo apresentados

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#486]
O usuário relatou que o problema aconteceu após o mesmo importar um projeto para o subprograma abaixo:

https://www.loom.com/share/45c510b1e1e74156b636287d3814881f?sid=726a1161-bc3b-42f3-9701-a283880618aa

![WhatsApp Image 2023-09-18 at 11 52 23](https://github.com/sep-es-br/openpmo-web/assets/41967259/06266c5b-41e9-4cb9-8b78-b05ccffd13d8)

**Comment by camilaseasky** [comment]
Esse 'importar' é consumir um projeto compartilhado?
Vamos precisar do id do workpack consumido e do dump do banco.

**Comment by vdcordeiro** [comment]
Usuário recortou o projeto 36794 do programa "Mudanças Climáticas" e tentou colar dentro do subprograma 11843: 
Portfólio: Realiza+
Eixo: Eixo 2
Área Temática: AMA
Programa: Mudanças Climáticas
Subprograma: Eixo Prevenção

**Comment by icarosbmartins** [comment]
Houve um erro na funcionalidade de recortar e colar. Nós corrigimos o erro, mas o vínculo vai precisar ser criado via script.

```sql
match (w:Workpack), (p:Plan)
where id(w)=36794 and id(p)=182
create (w)-[:BELONGS_TO{linked:false}]->(p)
```

**Comment by msantosmarcos** [comment]
resolvido.
