### ISSUE TITLE
Cronograma: Edição de custos com 2 CCs

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#487]
Na edição de custos com 2 CCs pelos cards do cronograma, o clique no campo de realizado deveria acionar o popup de CCs.
O popup, no entanto, é exibido ao clicar mais acima e no campo de custo estimado.
Além disso, os campos de custos aceitam a seleção do valor e a sobreposição via [ctrl]+[C].

https://github.com/sep-es-br/openpmo-web/assets/41954965/5893f2cf-516d-40d0-a79f-c60f789a0628

**Comment by vdcordeiro** [comment]
verificado

**Comment by vdcordeiro** [comment]
Na verdade, ainda é possível selecionar e alterar o campo através da tecla [tab]:

**Comment by camilaseasky** [comment]
Ajustado. Fazer o pull do front.

**Comment by vdcordeiro** [comment]
Verificado
