### ISSUE TITLE
Ocorrência: Plano de resposta não recarrega após editar ocorrência

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#489]
Após editar uma ocorrência que possui plano de resposta, a lista de planos não recarrega. É necessário forçar um refresh para a lista de planos carregar corretamente.

https://github.com/sep-es-br/openpmo-web/assets/41954965/f67a7819-bbf4-4135-83d4-497fe4871024

**Comment by msantosmarcos** [comment]
resolvido.
