### ISSUE TITLE
Filtros não funcionam

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#490]
Testei o filtro nas partes interessadas de um workpack.
Não funcionou quando só forcei a ordenação pelo nome, deixando sem regras. Deveria exibir todos, porém ordenados por nome, o que por sinal, já deveria fazer por default no filtro "Todos".
Testei também aplicar a regra Nível = Editar. Também não trouxe ninguém, quando todos os usuários da lista tinham nível de edição na permissão.

Precisamos que a fábrica refaça os testes sobre os filtros, encontre os bugs e os corrija, pois acredito que deve haver ainda muitos outros bugs nesses filtros, pois toda vez que tento utilizá-los encontro erros e não consigo usar;

**Comment by msantosmarcos** [comment]
Icaro, esta apresentando um erro ao filtrar por nível.

Deveria exibir todos, porém ordenados por nome, o que por sinal, já deveria fazer por default no filtro "Todos".

https://github.com/sep-es-br/openpmo-web/assets/41967259/cfce7043-5e56-44af-8de9-610912317e08

**Comment by da0hn** [comment]
Filtro utilizando `permissionLevel` no [commit](https://github.com/sep-es-br/openpmo-api/commit/54bfed12f439884cb21ee4d58065d4dd01e8a179)

O frontend também foi atualizado.

**Comment by msantosmarcos** [comment]
resolvido
