### ISSUE TITLE
Menu de plano quebrou

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#492]
Durante uma sessão de treinamento (ambiente de treinamento) após a criação de workpacks por diversos usuários, o menu parou de funcionar e passou a não carregar, conforme abaixo. Os demais menus e métodos de navegação funcionam corretamente.

https://github.com/sep-es-br/openpmo-web/assets/41954965/d87ffecc-19dd-438f-8ae8-006464623457

**Comment by camilaseasky** [comment]
Isso é por causa daquele projeto que perdeu o relacionamento com o plano do issue 486. Precisam recriar o relacionamento para o menu funcionar.

**Comment by vdcordeiro** [comment]
São ambientes diferentes. A issue #486 aconteceu no ambiente de produção. Essa aqui (#492) aconteceu no ambiente de treinamento. Outro banco de dados.
Depois que o Ícaro colocou como fixed, já rodei outro deploy e o problema persiste. O dump do ambiente de treinamento já foi enviado, mas não recebemos nenhum script específico para corrigir o banco de treinamento.

**Comment by vdcordeiro** [comment]
Verificado na última release.

**Comment by vdcordeiro** [comment]
Verificado na última release.
