### ISSUE TITLE
Programa não esta sendo exibido

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#493]
Na data de ontem, 20/09/2023, o Cultura ES, um dos 03 programas da ECEL sumiu.
O painel de controle indica que são 03, mas ele não parece quando clico em programas.

https://github.com/sep-es-br/openpmo-web/assets/41967259/d14ef8b7-3ded-464d-b870-eccc77774410

**Comment by msantosmarcos** [comment]
Identificamos que a property:name,  estava triplicada e tinha perdido o relacionamento IS_DRIVEN_BY  com propertyModel. Como era um problema crítico resolvemos direto no banco. No entanto temos que identificar a origem do problema.

**Comment by icarosbmartins** [comment]
Não conseguimos reproduzir esse bug. Fizemos vários testes com o workpack e com as properties, mas todos bem sucedidos. Depois disso, buscamos no banco properties que não possuem relacionamento IS_DRIVEN_BY com propertyModel, e não houve retorno. Acreditamos que esse problema já foi corrigido na semana anterior no ajuste do save do workpack e que novos testes precisariam ser feitos.

**Comment by vdcordeiro** [comment]
Fechando por enquanto. Caso torne a aparecer, reabrimos.
