### ISSUE TITLE
Relatório: erro ao gerar relatório de entregas

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#494]
Ao gerar o relatório de entregas o processo esta sendo finalizado por time-out, verificamos que o parâmetro de scope esta com todos os id's dos workpacks, quando o certo seria passar o workpack pai.

 conforme vídeo abaixo:

https://github.com/sep-es-br/openpmo-web/assets/41967259/a42c298f-c3b0-4b37-b672-6d1c48caefc6

**Comment by camilaseasky** [comment]
O combinado é que seriam enviados todos os ids dos workpacks. A alteração que fizemos em relação ao escopo foi na tela de persons. Vc está selecionando o plano como escopo e esse plano tem mais de 4000 workpacks pendurados... Dependendo de como estiver sua query vai demorar muito mesmo.

**Comment by camilaseasky** [comment]
Subi a versão do front que envia somente o id do patriarca, caso todos os itens estejam selecionados.

**Comment by vdcordeiro** [comment]
Com a nova versão porém, o parâmetro de escopo não carrega.

**Comment by camilaseasky** [comment]
Identificamos properties sem vínculo com a propertyModel nas seguintes situações:
1. Properties que não têm vínculo com nada (provavelmente este erro ocorreu qdo colocamos aquela versão do save do workpack com deep 0). Essas devem ser excluídas:

 match (p:Property) 
where not ((p)--()) 
detach delete p

2. Properties que estão vinculadas com um costAccount, mas não estão vinculadas com uma propertyModel. Essas aqui são properties que estavam vinculadas com uma propertyModel do workpackModel de COST que não foi copiada no modelo de costAccount default que criamos via script. Assim, elas não tinham uma propertyModel correspondente no costAccountModel. Portanto devem ser excluídas também.

match (c:CostAccount)--(p:Property) 
where not ((p)--(:PropertyModel))
detach delete p

3. Properties que estão vinculadas com workpacks, mas que não estão vinculadas com uma propertyModel. Este caso que está fazendo dar erro na busca do escopo. Não conseguimos reproduzir esse erro. De qualquer forma para resolver o problema teremos que executar os scripts a seguir restaurando o vínculo com a propertyModel correspondente:

match (p:Property), (pm:PropertyModel)
where id(p)=134630 and id(pm)=166
merge (p)-[:IS_DRIVEN_BY]->(pm)

match (p:Property), (pm:PropertyModel)
where id(p)=56688 and id(pm)=159
merge (p)-[:IS_DRIVEN_BY]->(pm)

match (p:Property), (pm:PropertyModel)
where id(p)=56851 and id(pm)=160
merge (p)-[:IS_DRIVEN_BY]->(pm)

match (p:Property), (pm:PropertyModel)
where id(p)=154105 and id(pm)=129
merge (p)-[:IS_DRIVEN_BY]->(pm)

match (p:Property), (pm:PropertyModel)
where id(p)=203497 and id(pm)=130
merge (p)-[:IS_DRIVEN_BY]->(pm)

match (p:Property), (pm:PropertyModel)
where id(p)=282692 and id(pm)=122
merge (p)-[:IS_DRIVEN_BY]->(pm)

match (p:Property), (pm:PropertyModel)
where id(p)=310412 and id(pm)=775
merge (p)-[:IS_DRIVEN_BY]->(pm)

match (p:Property) 
where id(p) in [224348,224354,224358,224362] 
detach delete p

**Comment by msantosmarcos** [comment]
feito.
