### ISSUE TITLE
Erro - Menu não carrega mais(quebrado)

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#497]
Após aplicar a nova release o menu foi quebrado, conforme vídeo abaixo:

https://github.com/sep-es-br/openpmo-web/assets/41967259/9d3181ae-0c2d-488b-afb3-ed06286b1428

**Comment by da0hn** [comment]
Não consegui reproduzir o erro criando um novo Workpack filho do mesmo projeto.

**Comment by msantosmarcos** [comment]
resolvido
