### ISSUE TITLE
Erros ao movimentar workpacks

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#498]
Durante um processo de reorganização do portfólio, com o objetivo de eliminar o nível de "Eixo" da estrutura, tivemos 2 erros. 1 ao colar um workpack recortado e outro ao excluir um workpack vazio. Passos para reproduzir (ambiente de homologação):

0. Na área de administração do escritório PMO-ES, modelo de plano "Modelo de Gestão 23-26", dentro do portfólio, painel MODELOS, botão [+] > Reutilizar > Área Temática. Ficou assim:
![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/c3fa5965-2f9a-44cb-8064-700330f7c48a)

1. Na área gerencial (menu azul), entrei em cada eixo do portfólio Realiza+, lista de áreas temáticas, para cada área temática:
   1.1. Recortei a área temática;
   1.2. Colei na raiz do portfólio (aba áreas temáticas);
ERRO >>>> Esse procedimento funcionou para todas, exceto uma, INFRA, localizada no Eixo 2. Dá erro **400 Bad Request** no **POST**:
`https://hom.pmo.es.gov.br/openpmo/workpack/228/paste-to/109?idPlanFrom=182&idParentFrom=187&idPlanTo=182&idParentTo=2572&idWorkpackModelFrom=109
`
`erro: "workpack.paste.error"`
https://github.com/sep-es-br/openpmo-web/assets/41954965/37fa6b6e-6550-44b4-a87a-912af2c1f8fe

2. Em seguida, tentei excluir o Eixo 1, do qual foi possível mover todas as áreas temáticas. A mensagem de confirmação é exibida desativada juntamente com o spinner e nenhuma requisição é enviada ao backend. Aparentemente, o front está desativando a tela e exibindo o spinner antes da hora da exclusão. deveria ser somente após o clique no sim.
https://github.com/sep-es-br/openpmo-web/assets/41954965/1f444946-a3f7-48f2-ad5c-5c8fa439da1c

**Comment by icarosbmartins** [comment]
Identificamos que existia um milestone filho de um outro milestone. Além disso, na hierarquia dos workpack models, não existia um workpack model para este milestone filhos. Então, retiramos o `IS_IN` e fizemos os milestones serem irmãos, filhos do organizer acima do milestone. Após isso, o recortar e colar funcionou.


```sql
match (m:Milestone)-[i:IS_IN]->(m2:Milestone)
where id(m)=46683 
delete i
```

```sql
match (w:Workpack), (m:Milestone)
where id(w)=46651 and id(m)=46683 
create (m)-[:IS_IN]->(w)
```

Esses workpacks foram criados via script ou pelo front?
Houve alguma modificação no workpack model para que ele pudesse ter workpack models filhos?

**Comment by vdcordeiro** [comment]
Após a correção, consegui movimentar a área temática INFRA para a raiz do portfólio. Depois consegui com sucesso excluir todos os 3 eixos, que já estavam vazios.
Por último, entrei na área de administração e excluí o modelo de workpack **Eixo**, uma vez que não seria mais utilizado. O objetivo era impedir exibição da guia Eixo na interface de gerenciamento (menu azul). A mensagem abaixo é exibida.
![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/c8fe1b58-0a89-4579-84b0-02c3fd50e439)
Ao clicar em [sim], dá o erro abaixo:
![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/e1d25d5d-2310-4d6b-abe3-af1caa45fc7e)
![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/5625ad45-2cd7-4322-8b69-ffa9ddf637cc)

Observe que o modelo filho do Eixo é **Área Temática**, que também é filho de **Portfólio**. Nesse caso somente o modelo **Eixo** deveria ser excluído, uma vez que seu filho **Área Temática** tem outro pai.

Após a exclusão, a aplicação parou de funcionar completamente por alguns minutos. Nenhuma página carregava. Depois de algum tempo, após sair e entrar novamente a aplicação voltou a funcionar, mas o modelo *Eixo* não foi apagado.

**Comment by vdcordeiro** [comment]
Resolvido, porém a mensagem que continua sendo exibida não reflete a real situação.
