### ISSUE TITLE
Erro nos itens de paginação

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#499]
O item de paginação esta se perdendo na troca de workpacks, conforme vídeo abaixo:

obs.: Só acontece no ambiente de treinamento

https://github.com/sep-es-br/openpmo-web/assets/41967259/73a6f87e-46ea-4be9-8817-8e20e16b78d7

**Comment by camilaseasky** [comment]
O que aconteceu? Foi atualizado o front? Continua com o mesmo erro?
