### ISSUE TITLE
Menu Lateral: Botão de expandir sobrepõe o texto

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#500]
![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/1bd409c5-5219-415f-a7ed-84e3ff08860f)

Esse problema já ocorreu no passado e já havia sido corrigido. Com as últimas revisões do menu, retirada do menu suspenso, esse defeito regrediu.

**Comment by msantosmarcos** [comment]
resolvido.
