### ISSUE TITLE
Não é possível checar a entrega como escopo completo

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#502]
Não é possível checar a entrega como escopo completo, só é possível checar excluindo o cronograma, conforme vídeo abaixo:

https://github.com/sep-es-br/openpmo-web/assets/41967259/6527a1b1-a2e9-44d8-a546-43d61f10474a

**Comment by camilaseasky** [comment]
Quando temos uma entrega com cronograma, ela vai ficar como completa quando o cronograma estiver completo. Isso não pode ser feito diretamente no checkbox. Essa foi a regra estabelecida.

**Comment by vdcordeiro** [comment]
> Quando temos uma entrega com cronograma, ela vai ficar como completa quando o cronograma estiver completo. 

Você testou isso?

**Comment by camilaseasky** [comment]
Sim. O sistema inclusive sobe a hiearquia para verificar se ao completar aquela entrega o projeto onde ela está também ficou completo.

**Comment by vdcordeiro** [comment]
Dando erro ao informar 100% no realizado:

https://github.com/sep-es-br/openpmo-web/assets/41954965/2ab9ad3a-a2ca-4860-9a5d-f6cfb85482d1

**Comment by vdcordeiro** [comment]
O problema dos vídeos acima parou de ocorre após a última publicação hoje.
A conclusão do escopo, no entanto não ocorre, mesmo com os 100% concluídos no cronograma.

https://github.com/sep-es-br/openpmo-web/assets/41954965/6de787c0-a09f-41a1-976c-8c9a0f6232b0
