### ISSUE TITLE
Relatório: Todo o escopo é exibido para usuário restrito

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#506]
Na emissão do relatório, todo o escopo do plano é exibido, ainda que o usuário não tenha acesso. Deveria aparecer como no menu. somente o que ele pode ver. Embora ele só possa selecionar os itens que ele tem acesso, isso confunde o usuário e é contra-intuitivo, pois precisa saber que tem que localizar na árvore os workpacks permitidos.

![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/e27bbcd6-dba2-47c1-b79e-5f75488349ad)

**Comment by camilaseasky** [comment]
![image](https://github.com/sep-es-br/openpmo-web/assets/30134914/257acd30-d840-49f6-bafa-05f3c280bd1f)
Na documentação estava definido assim:
3.Scope: o escopo (abrangência) pretendido para o relatório 

   3.1. Campo de seleção múltipla, apresentando a árvore de workpacks do plano (inclusive). 
   3.2. Somente plano e workpacks onde o usuário tem permissão mínima de read estarão habilitados para seleção.
   3.3. A (des)seleção de um item da árvore (des)seleciona automaticamente todos os seus descendentes.
   3.4. Por default, todos os itens passíveis de seleção estarão selecionados.

**Comment by vdcordeiro** [comment]
Realmente não me lembrava dessa especificação. Temos porém dois pontos não atendidos na especificação:
1. No caso do ítem 3.2, embora os workpaks sem edição não possam ser selecionados, isso não fica claro visualmente. O usuário precisa clicar em cada um para descobrir. Os itens desabilitados deveriam ficar mais apagados, como é padrão nesses casos.
2. O item 3.4 não foi atendido.

**Comment by vdcordeiro** [comment]
Porque os traços [-] abaixo não aparecem para o usuário restrito?
![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/9209b735-f1eb-4d3b-a2de-22680d87ec9a)

E porque passou a demorar mais para carregar o escopo do usuário restrito?

No usuário restrito fica assim:
![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/4900d8e6-5705-46b6-bc98-f721c0272286)

**Comment by vdcordeiro** [comment]
Esta issue for alterada para melhoria, pois vamos rever a especificação para que, na apresentação do escopo, sejam exibidos somente aqueles workpacks permitidos ao usuário, assim como é feito para o menu lateral.
Essa medida tem a finalidade de melhorar o desempenho e tornar mais intuitiva e rápida (menos cliques) a emissão dos relaórios.

**Comment by vdcordeiro** [comment]
Resolvido
