### ISSUE TITLE
Ciclo 06: Ícones de informação nas EAP e listas de subelementos.

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#511]
Adicionar ícones de informação ![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/aa3b429f-593e-4f19-9284-fd08d313ebec) e ![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/b77f41a4-dea4-4e57-9ec8-0cb8b49bf7fd) dos workpacks nas EAPs e listas de subelementos.

Ao passar o mouse por cima do ícone, será exibida em popup a informação (journal entry tipo information) mais recente associada diretamente àquele workpack.

Quando a informação mais recente tiver mais de 30 dias de "idade", o ícone ![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/aa3b429f-593e-4f19-9284-fd08d313ebec) é exibido.
Quando a informação mais recente tiver 30 dias ou menos de "idade", o ícone ![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/b77f41a4-dea4-4e57-9ec8-0cb8b49bf7fd) é exibido.
Caso não tenha nenhuma informação associada ao workpack, nenhum ícone é exibido.

Exemplos:
![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/fc2eb678-1b9d-4cb1-816b-57ecc6339dd8)

![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/61c0e2db-981b-4cd9-ab5f-a850b5b576b7)

![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/af9a2d68-facc-4850-b5bc-5e471b70c25f)

**Comment by vdcordeiro** [comment]
Devido aos downloads presentes nos popups, foi adicionado corretamente um botão (X) para fechar o popup. Assim, o comportamento de fechamento se dá apenas se clicar no (X). Desta forma, para abrir o popup deve ser necessário clicar no ícone (!), pois da forma como está, ao se passar o mouse sem querer sobre o ícone (!), já abre uma popup que não se fecha sozinha. Damos o trabalho extra e até irritante ao usuário de ficar fechando as popups que ele nem queria abrir.

**Comment by msantosmarcos** [comment]
resolvido.
