### ISSUE TITLE
Erro na carga do menu do plano em produção

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#515]
![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/f8d9419e-80a4-484c-a359-839e7df7459d)
![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/6c826a9d-c811-4222-a1af-471fe6ce412a)

**Comment by camilaseasky** [comment]
Esse erro está ocorrendo porque existe um workpack que perdeu o relacionamento belongs_to com o plano.

match (workpack:Workpack)
where not exists((workpack)-[:BELONGS_TO]->(:Plan))
match (workpack)-[:IS_IN*]->(parent:Workpack)
match (workpack)<-[:IS_IN*]-(children:Workpack)
match (parent)-[:BELONGS_TO]->(plan)
return workpack, parent, children, plan
--------------
deve ser executado o script abaixo para recriar o relacionamento:

match (workpack:Workpack)
where id(workpack)=702
match (plan:Plan)
where id(plan)=182
create (workpack)-[:BELONGS_TO{linked:false}]->(plan)

**Comment by vdcordeiro** [comment]
Procedimento executado na produção e o menu voltou a carregar corretamente, no entanto, a causa do problema não foi identificada nem corrigida.
Não foi a primeira vez que esse tipo de relacionamento é perdido e provavelmente não será a última sem a correção da causa.
Como se trata de um problema intermitente, se faz necessário um trabalho de logging e uma inspeção minuciosa do código.

Vamos manter essa issue aberta até que a causa desse problema seja identificada e resolvida.

**Comment by vdcordeiro** [comment]
Na última semana um problema semelhante foi causado não pela falta do BELONGS_TO, mas pelo excesso. O Programa "Mulher Viver +" (id: 645) estava com 3 relacionamentos BELONGS_TO com o plano. Isso impedia que os usuários EDIT e READ conseguissem sequer visualizar o programa e seus descendentes na aplicação. Usuários admin conseguiam abrir o programa, mas o breadcrumb não carregava.

**Comment by vdcordeiro** [comment]
Resolvido após a refatoração
