### ISSUE TITLE
Entrega não apresenta sinalizadores nem dashboard, embora possua cronograma

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#517]
![card sem cronograma](https://github.com/sep-es-br/openpmo-web/assets/41954965/9d2312df-98f9-4558-99a6-d5a4f4b22564)

**Comment by camilaseasky** [comment]
Por favor anexar o banco que contém essa entrega para que possamos analisar.

**Comment by vdcordeiro** [comment]
É o mesmo da #515.

**Comment by camilaseasky** [comment]
Talvez o cálculo do dashboard desse workpack tenha sido interrompido nas "derrubadas" de container... Basta fazer alguma alteração no cronograma (mesmo que seja fake) que ele já vai calcular.

**Comment by vdcordeiro** [comment]
resolvido
