### ISSUE TITLE
Subetapa "virou" Etapa ao recortar e colar

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#519]
O workpack "Aracruz" (ID: 1141906) era uma subetapa da Etapa "Implantação do Programa Morar Legal".
`Portfólio: Realiza+ > Eixo: Eixo 2: +Des. com sustentabilidade > Área Temática: Infraestrutura > Programa: Infraestrutura Urbana > Projeto: Morar Legal > Etapa: Implantação do Programa Morar Legal`
![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/c08a0691-2660-4152-bd6e-4fe94789e5f7)

No dia 09/11/2023 um usuário recortou esse workpack e tentou colar dentro da etapa "Implantação do Programa Morar Legal" de outro projeto:
![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/925f7782-5660-4335-beb7-a9d3c7bd849d)
Como se pode ver na imagem acima, ao invés de colar a subetapa dentro da etapa pretendida, a aplicação converteu a subetapa em etapa e a colou no projeto, ao lado da etapa que deveria ser a sua "mãe".

**Comment by camilaseasky** [comment]
O que deve ter acontecido é que o usuário colocou a subetapa na listagem de etapas, pois como o tipo de workpackModel é o mesmo (organizer), o workpack vai aparecer na lista de opções para colar. Conforme o que foi definido na documentação da OS2 não é validado o nome do workpackModel, somente o padrão.

**Comment by vdcordeiro** [comment]
Se foi isso, então porque não é possível copiar de volta como subetapa?

**Comment by camilaseasky** [comment]
O workpackModel da subEtapa tem 2 models filhos e o da etapa tem 3 models filhos. Assim, um workpack com o model de subEtapa pode ser colado e vinculado ao model da Etapa, pois ele não vai ter workpacks filhos que não tenham um model filho correspondente no novo model. Porém, depois que o workpack subEtapa foi colado e vinculado ao model de Etapa, ele passa a ter um model de etapa e este possui 3 models filhos. Assim, não poderá mais ser colado como subEtapa, pois não terá um dos models filhos correspondentes. 
Resumindo, a validação verifica o tipo do model e quantos filhos ele tem. Se a quantidade de filhos for menor ou igual a quantidade de filhos onde ele deverá ser colado, é permitido, senão, não será permitido.

**Comment by vdcordeiro** [comment]
```
"Assim, não poderá mais ser colado como subEtapa, pois não terá um dos models filhos correspondentes.
Resumindo, a validação verifica o tipo do model e quantos filhos ele tem. Se a quantidade de filhos for menor ou igual a quantidade de filhos onde ele deverá ser colado, é permitido, senão, não será permitido."
```
É sempre importante entendermos a finalidade das regras especificadas. Essa restrição tem a finalidade de evitar qualquer perda de informação ao mover um workpack de um local para outro. Nesse caso, a forma como foi implementada a restrição acabou gerando esse _deadlock_. Se o workpack alvo da movimentação não possui descendentes compatíveis com o tal submodelo que não estaria presente no destino, não haverá perda alguma de informação. A verificação na origem não pode se dar pelo modelo, mas sim pelo próprio workpack (e seus filhos). Nesse exemplo, deveria ser proibido recortar/colar uma etapa como subetapa se aquela etapa contivesse subetapas criadas, e não se o modelo tivesse submodelos.

**Comment by vdcordeiro** [comment]
Para simplificar e evitar futuros problemas, vamos restringir o copy&paste a mesmos workpack models na origem e no destino.

**Comment by camilaseasky** [comment]
Já implementamos essa validação. Está na última versão disponibilizada para teste.

**Comment by vdcordeiro** [comment]
Resolvido
