### ISSUE TITLE
Valores realizados não são atualizados no Painel

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#521]
No treinamento ocorrido no dia 16/11/23, após o salvamento da linha de base e preenchimento do escopo e custo realizados, os valores realizados não foram refletidos nos cálculos do dashboard.

https://github.com/sep-es-br/openpmo-web/assets/41954965/bf23dd1e-8d17-4565-9c9d-3ce2c654b420

**Comment by vdcordeiro** [comment]
Diferente dos outros treinamentos, ontem criamos e utilizamos os centros de custos **na entrega** (antes estávamos criando no projeto).

**Comment by camilaseasky** [comment]
Fizemos testes aqui e os valores do dashboard estão sendo atualizados, seja quando o centro de custo está no projeto ou quando está na própria entrega. Por favor verifiquem se a chave abaixo está setada no arquivo de properties que estiver sendo utilizado no build.
# Dashboards
app.dashboards.enable=true

**Comment by vdcordeiro** [comment]
OK
