### ISSUE TITLE
Os dashbords de custo, escopo e cronograma não estão sendo exibidos

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#522]
Após a execução do endpoint: "POST /dashboards/purge", a aplicação não esta exibindo os dashboards de custo, escopo e cronograma no ambiente de homologação, conforme imagem abaixo:

![image](https://github.com/sep-es-br/openpmo-web/assets/41967259/78952803-273b-4fc9-94c1-c6d8fe416654)

**Comment by vdcordeiro** [comment]
Resolvido. Era um problema no deploy.
