### ISSUE TITLE
upload e download de arquivo no diário

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#523]
1) Upload: Ao tentar efetuar upload de qualquer tipo de arquivo com o menu afixado o sistema não o faz, no entanto se desafixar o menu o upload é efetuado com sucesso. Nota-se também uma lentidão ao digitar o nome da informação em questão.

2) Download: Ao efetuar o download o arquivo esta sem a extensão impossibilitando abri-lo na máquina do usuário.

Conforme vídeo abaixo: 

https://github.com/sep-es-br/openpmo-web/assets/41967259/5f9bd40b-8e53-4c14-8040-2b3e497609d5

**Comment by camilaseasky** [comment]
Versão do front com a correção já está disponível para pull.

**Comment by msantosmarcos** [comment]
resolvido.
