### ISSUE TITLE
Erro ao colar projeto

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#526]
Não esta sendo possível recortar e colar um determinado projeto, conforme vídeo abaixo:

https://github.com/sep-es-br/openpmo-web/assets/41967259/a5f76bfa-303c-41b3-9eab-41c090928cb0

**Comment by camilaseasky** [comment]
Este problema não ocorre na nossa versão do back.

**Comment by msantosmarcos** [comment]
resolvido
