### ISSUE TITLE
erro ao acessar plano

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#528]
https://github.com/sep-es-br/openpmo-web/assets/41967259/2c200d8e-f31e-4257-8782-52106a568a88

**Comment by camilaseasky** [comment]
Esse erro é devido á uma alteração que foi feita no back/front aqui, mas o back acabou não sendo atualizado com essa versão. Subi a atualização na branch viewPlanFix. Por favor fazer o merge.

**Comment by msantosmarcos** [comment]
resolvido
