### ISSUE TITLE
Marco Crítico

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#529]
Existe marcos críticos com data futura marcados como concluídos.
O estranho é que existe uma regra de não deixar o usuário marcar o marco como concluído com data futura.
Como foi possível isso acontecer.

https://github.com/sep-es-br/openpmo-web/assets/41967259/1b462ec4-3d93-42fe-8df0-ae043387ad77

**Comment by camilaseasky** [comment]
Quando o flag de concluído está marcado, a data pode ser alterada sem qualquer tipo de validação. Esses marcos críticos tinham uma data passada e provavelmente estavam como concluídos. Depois disso a data foi alterada para uma data futura, mas o flag de concluído não foi desmarcado. Essas ações estão registradas no journal dos marcos críticos.
Disponibilizei uma versão que não permite mais alterar a data se o flag de concluído estiver marcado.
Assim, evitaremos esse problema.
Os marcos críticos que estão concluidos com data futura até agora, deverão ser alterados para não concluídos via script.
A seguir, vamos observar se teremos esse tipo de situação novamente.

**Comment by msantosmarcos** [comment]
resolvido
