### ISSUE TITLE
Ordenação do menu lateral

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#530]
No nível de subetapa o menu não esta ordenando.

![image_2024_01_19T14_09_17_721Z](https://github.com/sep-es-br/openpmo-web/assets/41967259/9dcaab56-ff99-4eda-af04-8a4f417e91d8)

**Comment by camilaseasky** [comment]
Esse problema não acontece na nossa versão. Provavelmente deve ser resultado das alterações feitas na versão do back de vcs.

**Comment by msantosmarcos** [comment]
resolvido
