### ISSUE TITLE
Linha de base

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#532]
Ao aprovar a linha de base,  o cronograma não esta sendo exibido.

![WhatsApp Image 2024-01-19 at 12 14 30](https://github.com/sep-es-br/openpmo-web/assets/41967259/be9835cd-42f8-468d-8e22-401359911cf6)
![WhatsApp Image 2024-01-19 at 12 06 29](https://github.com/sep-es-br/openpmo-web/assets/41967259/169907b1-a4cb-4b14-a942-92ef0409905e)

**Comment by camilaseasky** [comment]
Problema já foi resolvido na versão que está em teste.
