### ISSUE TITLE
Projeto no caminho errado

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#534]
Quando acessamos um projeto no perfil do usuário esta sendo apresentado o caminho errado no bradcrump, conforme vídeo abaixo:

https://github.com/sep-es-br/openpmo-web/assets/41967259/0330b190-8f18-4f8f-a039-0f178545b8b0

**Comment by msantosmarcos** [comment]
Camila, isso não é bug. pq?

**Comment by camilaseasky** [comment]
Disponibilizada a versão do FRONT na branch release_refactor com esse ajuste.

**Comment by msantosmarcos** [comment]
resolvido.
