### ISSUE TITLE
Desviando para o plano na versão mobile

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#535]
Na versão mobile, após selecionado um workpack, ao abrir o menu novamente, a seleção é desviada para o plano.

Em alguns casos (como no exemplo do vídeo) ocorre na primeira vez. Em outros casos é preciso abrir e fechar o menu algumas vezes para repetir o problema.

 

https://github.com/sep-es-br/openpmo-web/assets/41954965/5c719fc6-63c4-4e79-b5ab-9dc157b1365c

**Comment by camilaseasky** [comment]
Versão do FRONT disponibilizada com a correção.

**Comment by vdcordeiro** [comment]
Resolvido
