### ISSUE TITLE
Editar pemissão

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#537]
Ao editar a permissão de um person alterando o nível de permissão para "nenhum" o sistema registra como "somente leitura", conforme vídeo abaixo:

https://github.com/sep-es-br/openpmo-web/assets/41967259/fd06314c-f096-4bbd-8317-7937f251aca8

obs.: esse comportamento já foi demonstrado para a Camila

**Comment by camilaseasky** [comment]
Versão do FRONT disponibilizada com a correção.

**Comment by msantosmarcos** [comment]
resolvido
