### ISSUE TITLE
Cronograma: Erro no front ao abrir um step

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#543]
O erro ocorre quando tentamos editar o step a partir da visão não detalhada do cronograma.

https://github.com/sep-es-br/openpmo-web/assets/41954965/578d0ee9-c06b-4f0c-a17b-7d78792a428b

**Comment by camilaseasky** [comment]
Disponibilizada versão do FRONT com a correção do bug.

**Comment by vdcordeiro** [comment]
Resolvido
