### ISSUE TITLE
Erro ao carregar programas

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#544]
O erro abaixo é exibido na requisição https://pmo.es.gov.br/openpmo/workpack/**parent**

Como consequência:
- O programa **"Mulher Viver +"** (ID: 645) não é exibido no menu nem na EAP;
- Nenhum programa aparece na listagem de programas desta área;
- A única forma de acessar o programa é pelo popup menu do painel de controle.

![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/da271951-c749-499f-8071-105152f17387)

**Comment by camilaseasky** [comment]
Erro corrigido. Por favor fazer o pull do FRONT e BACK RELEASE_OS6

**Comment by msantosmarcos** [comment]
resolvido
