### ISSUE TITLE
Breadcrumb não segue padrão nos relatórios

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#545]
O breadcrumb na parte de relatórios não está seguindo o padrão de comportamento dos demais breadcrumbs do sistema.

![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/e63dcf9a-7953-419a-8227-fdd8853f6101)

![image](https://github.com/sep-es-br/openpmo-web/assets/41954965/151594eb-c92b-44bf-b9e4-ec316dc1e4b1)

**Comment by camilaseasky** [comment]
corrigido. Favor fazer a atualização do FRONT.

**Comment by msantosmarcos** [comment]
resolvido
