### ISSUE TITLE
Filtros do journal não se aplicam

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#546]
O filtro de escopo nunca é aplicado;
O botão "Ver Tudo" não funciona.

https://github.com/sep-es-br/openpmo-web/assets/41954965/11c1765c-cf76-405e-9c17-4288d9875153

https://github.com/sep-es-br/openpmo-web/assets/41954965/78881352-56c2-4030-94fa-e500dc3ec25e

**Comment by camilaseasky** [comment]
Disponibilizada a versão do FRONT e BACK com a correção do problema.

**Comment by msantosmarcos** [comment]
resolvido
