### ISSUE TITLE
Relatório

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#548]
Não esta sendo possível alterar nome e descrição do relatório, conforme vídeo abaixo:

https://github.com/sep-es-br/openpmo-web/assets/41967259/1b65dd32-3345-47b3-a4fd-75eecfde52d8

**Comment by camilaseasky** [comment]
Atualizar versão do front para correção do problema.

**Comment by msantosmarcos** [comment]
Resolvido
