### ISSUE TITLE
Inconsitência ao gravar properties group

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#549]
Ao criar um grupo de propriedades com múltiplos valores o sistema esta gravando no banco de forma inconsistente.

No banco esta sento gravado quatro nós para o SelectionModel, sendo que seria apenas um nós (selection) com todos valores gravados para esse projeto, conforme vídeo abaixo:

https://github.com/sep-es-br/openpmo-web/assets/41967259/116ebcfa-fb22-4e96-a07b-4bc2e32a0917

**Comment by camilaseasky** [comment]
precisamos de mais detalhes e exemplos por favor.

**Comment by msantosmarcos** [comment]
resolvido.
