### ISSUE TITLE
Usuário alterando a própria permissão

### ISSUE THREAD

**Issue by alanrodrigo** [sep-es-br/openpmo-web#55]
Usuário não deve ser capaz de excluir ou alterar sua própria permissão 

https://www.loom.com/share/b4b7f9b1ce554efc84a7d75e5f1fdc82

**Comment by camilaseasky** [comment]
Foi implementada a validação para permitir que somente usuários admin acessem as permissions do office.

**Comment by alanrodrigo** [comment]
Testado!
