### ISSUE TITLE
Parte interessada no esta sendo apresentada

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#550]
A Parte interessada(Andrea Paoliello de Freitasno) não esta sendo apresentada para o programa: Melhoria da Qualidade da Educação
id: 246

https://github.com/sep-es-br/openpmo-web/assets/41967259/546cfa04-4d52-422c-a944-f8da4d552fc4

**Comment by camilaseasky** [comment]
já tentou setar o toggle do inativo? pois pode ter vencido a data ou estar inativo e daí ele não aparece.

**Comment by msantosmarcos** [comment]
resolvido.
