### ISSUE TITLE
Dashboard - Inconsistência no cálculo do Custo Realizado 

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#551]
Ao alterar a data de referência  para um mês posterior o sistema não esta somando o valor deste mês ao custo realizado no dashboard de entrega, conforme vídeo abaixo:

https://github.com/sep-es-br/openpmo-web/assets/41967259/0e5f6a81-0e6d-4381-8341-f3c8ad2ce527

**Comment by camilaseasky** [comment]
Foi disponibilizada a versão do back e do front para corrigir este problema na RELEASE_OS6. Lembrando que meses posteriores ao mês atual não serão incluídos nos valores quando estes meses forem selecionados no parâmetro.

**Comment by msantosmarcos** [comment]
resolvido.
