### ISSUE TITLE
Duplicidade de projetos ao adicionar permissão

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#552]
Duplicidade de projetos ao adicionar permissão em pessoas no módulo administrativo, conforme vídeo abaixo:

https://github.com/sep-es-br/openpmo-web/assets/41967259/5e57c527-a71c-4168-9fc7-0bd3e1194cd5

obs.: Acontece somente com alguns usuários.

**Comment by camilaseasky** [comment]
por favor enviar o dump do banco com essa situação

**Comment by msantosmarcos** [comment]
enviado para o skype da Camila

**Comment by camilaseasky** [comment]
Ajuste commitado na release_OS6.

**Comment by msantosmarcos** [comment]
resolvido.
