### ISSUE TITLE
Erro ao editar card do mês no cronograma

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#553]
Ao tentar editar o card do mês no cronograma o sistema não apresenta a tela de edição do card do mês,

obs.: Esta acontecendo somente no ambiente de homologação.

No ambiente de produção conseguimos visualizar a tela de edição no entanto, ao editar a data o mesmo não salva a alteração.

 conforme vídeo abaixo:

https://github.com/sep-es-br/openpmo-web/assets/41967259/1d25d845-5c9f-4dcb-b189-0829e789c436

https://github.com/sep-es-br/openpmo-web/assets/41967259/3f920761-e1d6-4b03-bdab-a7f129795892

**Comment by camilaseasky** [comment]
Versão do front e do back com o ajuste.
