### ISSUE TITLE
Inconsistência na navegação

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#554]
Conforme o vídeo em anexo, o projeto ES Destino Náutico (código) está com um equívoco na apresentação dos dados, onde está registrado como uma "etapa", porém quando é selecionada está constando com uma "subetapa", não sendo possível a inserção de riscos no mesmo.

[Video Screen1719252541421 (1).webm](https://github.com/sep-es-br/openpmo-web/assets/41967259/e705800f-91da-477e-9b61-51d206fe0a43)

**Comment by camilaseasky** [comment]
Isso está acontecendo devido a um erro de atualização do idWorkpackModel quando o workpack era recortado e colado. O problema já foi resolvido não permitindo que sejam recortados e colados workpacks em workpackModels diferentes. Porém ficaram com erro alguns workpacks que já haviam sido recortados/colados anteriormente. Por favor executar o script que foi colocado no arquivo update_idModel.sql na pasta scripts. Com isso o problema de navegação não acontecerá mais.

**Comment by msantosmarcos** [comment]
aonde ficar essa pasta scripts?

**Comment by jpfariaa** [comment]
Boa tarde, Camila.

O script está incompleto, não está sendo executado corretamente, era pra ser desta forma? pois não está sendo executado.

```
MATCH (w:Workpack{deleted:false})-[ii:IS_INSTANCE_BY]->(wm:WorkpackModel)
      WHERE id(wm) <> w.idWorkpackModel set w.idWorkpackModel return id(w)
```

Alteramos aqui, para essa versão, mesmo assim, executando o nosso, o problema persiste:

```
MATCH (w:Workpack{deleted:false})-[ii:IS_INSTANCE_BY]->(wm:WorkpackModel)
      WHERE id(wm) <> w.idWorkpackModel set w.idWorkpackModel = id(w) return id(w)
```

**Comment by jpfariaa** [comment]
Boa tarde, Camila.

O script que você enviou aparentemente não está executando corretamente. O script está incompleto.

**Comment by camilaseasky** [comment]
Desculpe, deve ter perdido no copiar e colar. Subi a versão corrigida.

**Comment by msantosmarcos** [comment]
resolvido.
