### ISSUE TITLE
Cadastro inconsistente no Projeto

### ISSUE THREAD

**Issue by jpfariaa** [sep-es-br/openpmo-web#555]
Após a inclusão de um item na seção "Acompanhamento de Projetos" do projeto "Pró Docência" e o salvamento das alterações, o item adicionado não foi exibido ao atualizar a página.

https://github.com/sep-es-br/openpmo-web/assets/43326836/64063736-a70c-402d-85a3-639c3949e72e

**Comment by camilaseasky** [comment]
Por favor enviar o banco que tenha essa alteração, pois nos testes que fiz aqui está gravando e retornando a propriedade normalmente.

**Comment by msantosmarcos** [comment]
Enviei no seu Skype.

**Comment by camilaseasky** [comment]
Problema corrigido. Por favor puxar atualização do back na branch RELEASE_OS6.

**Comment by msantosmarcos** [comment]
resolvido
