### ISSUE TITLE
Falha no toggle de exibição dos riscos fechados na Etapa

### ISSUE THREAD

**Issue by jpfariaa** [sep-es-br/openpmo-web#556]
Como mostra no vídeo abaixo, ao acessar a etapa "Implantação do Sistema Integrado de Gestão Previdenciária" e acessar os riscos, o "Exibir Fechado" não está funcionando.

https://github.com/sep-es-br/openpmo-web/assets/43326836/08c5a071-03cf-49ac-92af-5544e0919957

**Comment by camilaseasky** [comment]
Por favor enviar o banco que tenha esses riscos. Testei aqui com outro projeto e está trazendo o risco fechando quando seta o toggle exibir fechado.

**Comment by msantosmarcos** [comment]
Enviei no seu Skype.

**Comment by camilaseasky** [comment]
Todos os riscos deste workpack estão com status OPEN e todos estão sendo exibidos na listagem. Quando o toggle de exibir fechados é marcado, continuam sendo exibidos os mesmos riscos, pois não tem nenhum fechado. Qual é o problema?
