### ISSUE TITLE
Projeto Melhorias Infra - PCES

### ISSUE THREAD

**Issue by jpfariaa** [sep-es-br/openpmo-web#557]
Solicito restore do projeto  Melhorias Infra - PCES que deveria estar dentro do Eixo Infraestrutura no Estado Presente não está aparecendo no Open.
 
No relatório de 03/07/204 o Projeto está constando no sistema.

https://github.com/sep-es-br/openpmo-web/assets/43326836/20eb2556-0866-4bb2-8334-4ec9195a0c5e

Segue o caminho que o projeto está no OpenPMO:

![Imagem do WhatsApp de 2024-07-05 à(s) 09 49 46_413d692c](https://github.com/sep-es-br/openpmo-web/assets/43326836/09d951a7-cbd6-4d78-8a20-4339c3963bc9)

**Comment by camilaseasky** [comment]
Vou precisar do dump correspondente por favor.

**Comment by msantosmarcos** [comment]
banco enviado via skype

**Comment by camilaseasky** [comment]
O projeto perdeu a referência com o plano. Por favor executar o script a seguir para refazer o relacionamento.

MATCH (w:Workpack), (p:Plan)
          WHERE id(w)=6813 AND id(p)=182 
          CREATE (w)-[:BELONGS_TO{linked: false}]->(p)

**Comment by jpfariaa** [comment]
Após executar o script o projeto em questão voltou a aparecer no OpenPMO, obrigado!

![image](https://github.com/sep-es-br/openpmo-web/assets/43326836/3450a702-ca6d-424a-bc6c-2778749c4b85)
