### ISSUE TITLE
A propriedade "Transversalidade" do Projeto

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#558]
A propriedade "Transversalidade" do Projeto não esta apresentando o seus respectivos valores gravados, conforme vídeo abaixo:

Favor verificar o mesma  propriedade na Entrega.

https://github.com/sep-es-br/openpmo-web/assets/41967259/09fb41e3-51e0-4fdf-a524-5ed4b6eb628c

**Comment by camilaseasky** [comment]
Estávamos com problemas na gravação das propriedades do tipo grupos. Isso foi resolvido na issue 555. No vídeo não mostra gravando os valores, salvando e consultando novamente. Por favor tentar fazer isso para testarmos se o erro já foi resolvido.

**Comment by camilaseasky** [comment]
por favor verificar se ficou ok.

**Comment by msantosmarcos** [comment]
resolvido.
