### ISSUE TITLE
Linha de base perdida(ou corrompida) após edições no projeto

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#559]
O projeto "Fortalecimento da EJA" (ID 18664) foi criado e linha de base salva em 17/01/2024, com 2 etapas. 2 subetapas, 6 entregas e diversos marcos críticos. No ambiente de homologação é possível verificar a situação original do projeto, ainda correto.
De lá para cá, diversas alterações foram realizadas, inclusive com a exclusão e inclusão de novas etapas e entregas. Esperava-se que nos gráficos do painel do projeto, a "barra cinza", que representa a linha de base, se mantivesse idêntica, uma vez que a LB original continua vigente, mas isso não acontece.
https://1drv.ms/v/s!AlMY2LIMIiYCpHsNuz63vMeUf_kq?e=cYslMz

**Comment by camilaseasky** [comment]
Se tiverem o banco antes das alterações e o banco depois das alterações, por favor enviar.

**Comment by camilaseasky** [comment]
O problema era que a seleção dos valores da baseline não estava considerando workpacks que já tivessem sido deletados na master. Foi corrigido e o commit feito na branch RELEASE_OS6 do back.

**Comment by msantosmarcos** [comment]
resolvido.
