### ISSUE TITLE
Propriedades de projetos perdidas 

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#560]
Varios projetos do programa "Gestão Moderna e Eficiente" (ID 12241) tiveram os valores de suas propriedades perdidos. Não sabemos qual ação gerou a perda dos relacionamentos, mas isso não pode ser impedimento para a correção do problema. 
A equipe da fábrica de software deve implementar medidas para reproduzir o erro ou registrar em log as ações futuras que possam provocar novos erros como este e assim corrigí-los. O mesmo vale para o bug #516, que já vem ocorrendo há 9 meses, sem qualquer solução.

**Comment by camilaseasky** [comment]
Que tipo de propriedades perderam os valore? 
Vcs teriam a versão do banco quando as propriedades ainda estavam com seus valores e a versão do banco depois que perderam para que possamos analisar?

**Comment by vdcordeiro** [comment]
Mais um projeto com propriedades perdidas:
![image](https://github.com/user-attachments/assets/5a9a775a-4e49-4e7e-9f8f-830938ef18cd)

**Comment by vdcordeiro** [comment]
Uma característica comum aos dois projetos: **ambos possuem linha de base rejeitada**.

**Comment by vdcordeiro** [comment]
Conseguimos repetir este defeito com pelo menos duas ações:
- Criação de um risco no projeto
- Adição de um usuário como parte interessada 
   - em nosso teste atribuímos ao usuário incluído a função de "Ponto Focal" e a permissão "Edit" ao papel "Cidadão".

**Comment by camilaseasky** [comment]
Corrigido no back branch RELEASE_OS6

**Comment by msantosmarcos** [comment]
resolvido.
