### ISSUE TITLE
Projeto cancelado 

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#561]
Projeto cancelado continua sendo exibido na lista e no menu, mesmo após o cancelamento da linha de base, conforme vídeo abaixo:

https://github.com/user-attachments/assets/95c1ab76-4edb-4ed8-98d4-1a87f7d65b8a

**Comment by camilaseasky** [comment]
A aprovação da baseline de cancelamento não estava alterando a situação do projeto para cancelado. O código foi ajustado, porém será necessário executar o script a seguir para setar o flag nos projetos e workpacks filhos do projeto que estiver vinculado a uma baseline de cancelamento ativa.
MATCH (b:Baseline)<-[:IS_BASELINED_BY]-(p:Project)<-[:IS_IN*]-(child:Workpack) where b.cancelation = true and b.status ='APPROVED' and b.active = true and p.canceled = false  set p.canceled = true

**Comment by camilaseasky** [comment]
Atualizar a versão do front e back da branch RELEASE_OS6

**Comment by msantosmarcos** [comment]
resolvido
