### ISSUE TITLE
Erro 500 no compartilhamento de projeto com um escritório

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#563]
Dá um erro 500 ao savar o compartilhamento. 

https://github.com/user-attachments/assets/5bbfe900-4dde-4886-97a3-f54ecb5011e9

O erro só ocorre ao compartilhar com um escritório específico.
O compartilhamento com "Todos" funciona corretamente.

**Comment by camilaseasky** [comment]
Ajuste feito e disponibilizado nos projetos de front e back da branch RELEASE_OS6.

**Comment by vdcordeiro** [comment]
Embora o erro na página citada acima tenha sido corrigido, o restante do caso de uso (que estava impossibilitado de ser testado devido ao erro anterior) passou a apresentar erro.
Após o compartilhamento bem-sucedido, temos novo Erro 500 ao consumir o projeto compartilhado no escritório consumidor.

**Comment by msantosmarcos** [comment]
1 - Camila, ao efetuar os testes constatei que ao alterar a propriedade órgão no projeto consumido não esta sendo populada com a lista de órgãos dos escritório original.
2 - O projeto compartilhado como somente leitura está podendo ser editado a partir do escritório consumidor

**Comment by msantosmarcos** [comment]
resolvido.
