### ISSUE TITLE
Linha de base

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#564]
Linha de base do projeto "Capacita Esporte"  não esta sendo exibido para efetuar aprovação, conforme imagem e vídeo abaixo:

[Capaciata Esporte - linha de base.pdf](https://github.com/user-attachments/files/17029811/Capaciata.Esporte.-.linha.de.base.pdf)

https://github.com/user-attachments/assets/8dcb8ad9-bdcc-4b3c-9b41-aa203aa2ffff

**Comment by camilaseasky** [comment]
Atualizadas as versões do front e back na branch RELEASE_OS6

**Comment by msantosmarcos** [comment]
resolvido.
