### ISSUE TITLE
Propagação do centro de custo

### ISSUE THREAD

**Issue by alanrodrigo** [sep-es-br/openpmo-web#60]
Centros de custo não devem ser propagados para workpacks filhos

loom.com/share/f251d042f5534f35a9174b7f7a9d7d17

**Comment by vrcristo1980** [comment]
@alanrodrigo - a regra de propagação consta na documentação
Cost Assignment irá trazer todos os custos associados aos workpacks dos elementos ascendentes
https://totemti.atlassian.net/wiki/spaces/OPMO/pages/1342275909/Manter+Pacote+de+Trabalho+-+Entrega

**Comment by vdcordeiro** [comment]
Resolvido com a desabilitação dos CCs herdados.
