### ISSUE TITLE
Breadcrumb não reinicia ao selecionar novo item no menu

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#61]
Naveguei no menu de estratégias e o breadcrumb foi criado com os passos da minha navegação. Depois, cliquei no item de menu Organizações e o passo Organizações foi acumulado ao caminho traçado anteriormente na estratégia.
O breadcrumb deveria construir um novo caminho, pois Organizações estão no mesmo nível de Estratégias.
https://www.loom.com/share/13aa184298294f7798a240f769587b23

**Comment by vdcordeiro** [comment]
O comportamento descrito inicialmente foi corrigido para o refresh, mas continua ocorrendo algo semelhante ao editar centro de custo:
![image](https://user-images.githubusercontent.com/41954965/110535942-9fbe5980-80ff-11eb-8625-5732f93978d8.png)

**Comment by vdcordeiro** [comment]
O mesmo ocorre ao editar cronograma

**Comment by alanrodrigo** [comment]
Corrigido!

**Comment by vdcordeiro** [comment]
O mesmo ocorre ainda ao editar parte interessada.
![image](https://user-images.githubusercontent.com/41954965/111536390-f3a4f000-8748-11eb-87aa-e643ea4cd2a6.png)

**Comment by vdcordeiro** [comment]
Resolvido

**Comment by vdcordeiro** [comment]
Resolvido
