### ISSUE TITLE
Ajustes de design

### ISSUE THREAD

**Issue by alanrodrigo** [sep-es-br/openpmo-web#65]
**Layout dos cards:**
- **Largura fixa: 280px (apenas no desktop) mobile deve ser responsivo**
![image](https://user-images.githubusercontent.com/42146539/110536281-0c395880-8100-11eb-9dfd-ee3a5d49bb95.png)

- Remover sombreamento
- Borda: 1px, cor: #D4D4D4
- Cor da fonte do ID: #888E96

![image](https://user-images.githubusercontent.com/42146539/109694546-b1d15280-7b69-11eb-8a79-a235b6e2f8ae.png)

**Paineis**
- Reduzir espaçamento entre painéis: 15px
- Reduzir espaçamento entre titulo do painel e card: 15px
- Alinhar titulo e conteúdo
- Tamanho do ícone recolher/expandir: 1.3rem

![image](https://user-images.githubusercontent.com/42146539/109696338-b4cd4280-7b6b-11eb-8632-3820231631e5.png)  ![image](https://user-images.githubusercontent.com/42146539/109696591-fd84fb80-7b6b-11eb-8612-6aa8de5db81f.png)

**Labels**
- Reduzir espaçamento das labels: _.p-inputtext{ margin-top: **-8px;**}_
![image](https://user-images.githubusercontent.com/42146539/109698114-cca5c600-7b6d-11eb-852a-357a6264679b.png)

**Títulos páginas**

![image](https://user-images.githubusercontent.com/42146539/109698688-6cfbea80-7b6e-11eb-9239-0d8cf1c065ca.png)

**Cards Organizations**
Conforme acordado em reunião em 02/03/2021, optamos por retirar o "full name" para evitar que a altura do card seja alterada caso ultrapasse mais de duas linhas

![image](https://user-images.githubusercontent.com/42146539/109700098-214a4080-7b70-11eb-8f6a-e0ad408e67fa.png)

**Mobile**
Ajustar mensagens de notificação
![image](https://user-images.githubusercontent.com/42146539/109700709-e563ab00-7b70-11eb-88ab-4d3588ec5611.png)

Ajustar espaçamento
![image](https://user-images.githubusercontent.com/42146539/109700764-f6142100-7b70-11eb-8190-031aba8e38fa.png)
![image](https://user-images.githubusercontent.com/42146539/109700805-062c0080-7b71-11eb-80e2-e8793e282267.png)

Botão com largura total
![image](https://user-images.githubusercontent.com/42146539/109700864-1512b300-7b71-11eb-84b9-c20640d4bff3.png)

**Comment by alanrodrigo** [comment]
Largura fixa: 280px (apenas no desktop) mobile deve ser responsivo

**Comment by alanrodrigo** [comment]
Corrigido!

**Comment by vdcordeiro** [comment]
No cronograma, formatação do valor do avanço físico realizado está faltando o ponto/vírgula separador de milhar.
![image](https://user-images.githubusercontent.com/41954965/111483471-90e53180-8713-11eb-94e5-65c1372ca6ee.png)

**Comment by vdcordeiro** [comment]
Resolvido
