### ISSUE TITLE
Scroll menu breadcrumb

### ISSUE THREAD

**Issue by alanrodrigo** [sep-es-br/openpmo-web#66]
Quando o breadcrumb atingir o limite da página, não utilizar scroll.
![image](https://user-images.githubusercontent.com/42146539/109798625-c52bfe80-7bf9-11eb-98e3-a945e44303a8.png)

Inserir reticências conforme exemplo a baixo:
![image](https://user-images.githubusercontent.com/42146539/109798764-eb519e80-7bf9-11eb-846d-2a3384a8a338.png)

**Comment by camilaseasky** [comment]
Funcionalidade já implementada e disponível para testes.

**Comment by alanrodrigo** [comment]
Funcionalidade testada!
