### ISSUE TITLE
Breadcrumb com passos em branco

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#70]
Ao navegar na WBS, os workpacks projeto e entrega ficaram sem os nomes no breadcrumb
![image](https://user-images.githubusercontent.com/41954965/111472029-54f89f00-8708-11eb-8335-df22b46959eb.png)

**Comment by msantosmarcos** [comment]
demanda resolvida

**Comment by msantosmarcos** [comment]
demanda resolvida

**Comment by vdcordeiro** [comment]
O nome ainda não aparece em um dos projetos.
Observado que o breadcrumb está exibindo o nome do template, quando deveria exibir o nome do modelo do workpack no breadcrumb.
![Captura de Tela 2021-03-19 às 10 00 20](https://user-images.githubusercontent.com/41954965/111788980-72ac3c80-889f-11eb-9945-a0207632f2fb.png)

**Comment by vdcordeiro** [comment]
Resolvido
