### ISSUE TITLE
Login sem permissão

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#71]
Sempre que um usuário sem nenhuma permissão faz login no OpenPMO, ele é direcionado de volta à página de login e é exibida uma mensagem de erro, informando que ele não tem acesso ao sistema.
Isso ainda não está bom, pois o usuário fica "preso" nessa página, sem conseguir dar logout, ou caso queira utilizar alguma outra credencial.
Como melhoria, poderíamos desviá-lo para a página offices, sem os menus offices e wbs, e no centro, no lugar da lista de escritórios, exibir a mensagem informando que ele não tem acesso.
Caso queira sair ou trocar de idioma, ele terá disponível o menu user no canto inferior esquerdo. Um link adicional para o logout deve ser exibido na mensagem, para facilitar a sua saída.

**Comment by camilaseasky** [comment]
Funcionalidade implementada e disponível para testes.
