### ISSUE TITLE
Stakeholders devem inativar fora do período

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#72]
As datas de início e fim de cada role do stakeholder tinha um propósito: tornar aquela role inativa em qualquer data fora do intervalo. Se todas as roles de um stakeholder estiverem inativas, seja por data, seja por inativação manual, o stakeholder estará inativo. Isso poderá ser observado alterando a chave "Show Inactive"na listagem de stakeholders.

Como esta regra não foi devidamente documentada no ciclo 1, fica aqui registrado como melhoria para aplicação no ciclo 2.

**Comment by msantosmarcos** [comment]
feito.
