### ISSUE TITLE
Erro ao excluir workpack e workpackModel

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#75]
Não estamos conseguindo deletar um workpack e workpackModel, sendo que este não possui workpack filhos. Conforme vídeo abaixo:

https://www.loom.com/share/f26b4404145d4b6f95fa6ae33ae96164

**Comment by msantosmarcos** [comment]
Teste refeito, e o problema persiste.

**Comment by camilaseasky** [comment]
Por favor nos informar qual workpackModel/workpack no ambiente de homologação de vcs está com este problema, para verificarmos.

**Comment by vdcordeiro** [comment]
O problema ocorre quando apagamos um plano com workpacks dentro. O sistema permite a deleção, mas apaga apenas o plano, deixando os seus workpacks órfãos de plano. Como os workpacks ainda ficam vinculados aos seus workpack models, fica impossível apagar o workpack model e, consequentemente o plan model e o escritório.

**Comment by camilaseasky** [comment]
corrigido nesta versão.

**Comment by vdcordeiro** [comment]
O problema persiste. Foi possível apagar o plano e os seus workpacks ficaram órfãos, impossibilitando apagar os models.

**Comment by camilaseasky** [comment]
Ajustado e atualizado.

**Comment by msantosmarcos** [comment]
resolvido.
