### ISSUE TITLE
Possibilitar criar a "Entrega" dentro do modelo de Portifólio

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#76]
Não esta sendo apresentado na lista de modelos a opção "Entrega"

https://www.loom.com/share/b17ae158915b4b1eb267c437464e5efa

**Comment by camilaseasky** [comment]
A regra exige que o workpackModel tenha algum workpackModel do tipo project em seus ascendentes para que seja possível criar uma entrega dentro dele.

**Comment by vdcordeiro** [comment]
Fizemos o mesmo teste com a criação de um workpack model do tipo projeto como ascendente e mesmo assim a opção "Entrega" não é exibida. Veja na imagem:

![Captura de Tela 2022-02-17 às 16 51 09](https://user-images.githubusercontent.com/41954965/154559969-2affca6f-d928-44e0-8af1-d1e7424f0d83.png)

**Comment by msantosmarcos** [comment]
demanda executada.
