### ISSUE TITLE
Erro a cadastrar domínio

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#77]
Ao cadastrar um domínio e inserir o nome da propriedade, após salvar as opções de  LOCALIDADE RAÍZ desaparece.

https://www.loom.com/share/9abf981cf3074acb8d8a36548e79e1cb

**Comment by msantosmarcos** [comment]
Teste refeito, e o problema persiste.

**Comment by camilaseasky** [comment]
Testei no ambiente de vcs e não está ocorrendo o erro. Ao salvar, é exibido um card com a localidade raiz dentro do dominio.

**Comment by vdcordeiro** [comment]
Aparece a localidade raiz logo ao criar, mas não é possível criar outras localidades dentro da raiz. Além disso, depois que saímos do domínio criado e entramos de novo, a localidade raiz desaparece.

**Comment by msantosmarcos** [comment]
demanda executada.

**Comment by camilaseasky** [comment]
Corrigido nesta atualização.
