### ISSUE TITLE
Erro ao cadastrar um novo administrator

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#78]
Erro ao cadastrar um novo administrator, conforme vídeo abaixo:

https://www.loom.com/share/39bd8243200244f88e7a4494fe426dc3

**Comment by msantosmarcos** [comment]
Teste refeito, e o problema persiste.

**Comment by vdcordeiro** [comment]
Um problema é que o botão [Save] está subindo muito cedo, antes de preencher a tela com o nome e sobrenome. Se aguardarmos, alguns segundos (não sei porque a demora, pois o usuário já foi encontrado), o salvamento acontece, porém não aparece na lista de administradores, mas esse já é outro problema:
Na lista, o nome do recurso chamado pelo front (administrator**s**) está errado. o correto segundo a API é administrator (no singular).
![Captura de Tela 2022-02-04 às 12 16 43](https://user-images.githubusercontent.com/41954965/152555467-2acc9a56-e9f1-4b78-a1dc-461b0bfa2403.png)
![Captura de Tela 2022-02-04 às 12 17 40](https://user-images.githubusercontent.com/41954965/152555485-4de0c8ca-dc78-4041-80d3-989f6e6b7aec.png)

**Comment by camilaseasky** [comment]
Na verdade ao clicar em pesquisar, será carregada uma lista para que seja selecionado o servidor, pois podemos ter vários com o mesmo nome. Testei no ambiente de vcs e está carregando a lista, porém não está salvando devido a outro problema que já foi corrigido na nova versão que será disponibilizada.
