### ISSUE TITLE
Falha na reutilização de um determinado workpack model

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#80]
Fizemos uma reutilização (cópia) de um determinado workpack model e funcionou corretamente. No entanto, tudo que foi cadastrado na origem foi replicado para a réplica (isso no workpack). Isso não pode acontecer, uma vez criada a cópia a mesma não pode ter vínculo nenhum com sua origem.

**Comment by msantosmarcos** [comment]
Teste refeito, e o problema persiste.

**Comment by camilaseasky** [comment]
Por favor passar o id do workpackModel que foi reutilizado e do novo que foi criado pela reutilização dele para que possamos verificar.

**Comment by camilaseasky** [comment]
Já foi corrigido.

**Comment by msantosmarcos** [comment]
o problema persiste.

**Comment by msantosmarcos** [comment]
Resolvida.
