### ISSUE TITLE
Falha na ordenação dos organizadores

### ISSUE THREAD

**Issue by alanrodrigo** [sep-es-br/openpmo-web#82]
Ao alterar o numero de ordenação de um workpack organizador, não é feita a reordenação:

https://www.loom.com/share/a0d30483cd344aadb86bf53ae6823f78

**Comment by camilaseasky** [comment]
Por favor verificar no workpackModel se está selecionado no input ordenar por a propriedade numero de ordenação.

**Comment by msantosmarcos** [comment]
Está selecionado no workpackmodel, ainda sim não esta ordenando.

**Comment by camilaseasky** [comment]
corrigido nesta versão. Por favor verificar se está selecionado a property de ordenação no order by do planModel.

**Comment by vdcordeiro** [comment]
Verificado
