### ISSUE TITLE
Erro ao cadastrar stakeholder

### ISSUE THREAD

**Issue by alanrodrigo** [sep-es-br/openpmo-web#83]
Ao tentar cadastrar um stakeholder o seguinte erro é apresentado:

https://www.loom.com/share/0744e14fa67040b398fa76bc11452f06

**Comment by msantosmarcos** [comment]
Teste refeito, e o problema persiste.

**Comment by camilaseasky** [comment]
Eu acessei o ambiente de vcs e adicionei o Alan como stakeholder no porfolio do escritorio SEP. Não tive nenhum problema.
Poderíamos fazer juntos?

**Comment by msantosmarcos** [comment]
demanda executada.
