### ISSUE TITLE
Farois dos marcos críticos não funcionam

### ISSUE THREAD

**Issue by alanrodrigo** [sep-es-br/openpmo-web#87]
Ao alterar o status de um marco crítico para concluído por exemplo, o icone da bandeira deve ficar em azul conforme protótipo:
![image](https://user-images.githubusercontent.com/42146539/150546068-1244c473-0a20-4e8b-ba7d-ef366671a5aa.png)

https://www.loom.com/share/5ba5d0e0a6274ff19cfb618168bbf238

**Comment by camilaseasky** [comment]
Essa funcionalidade ainda não estava implementada. Estará na próxima versão que liberarmos juntamente com os dashboard e os ajustes nos elementos visuais.
