### ISSUE TITLE
Impossibilidade de acesso ao menu administração

### ISSUE THREAD

**Issue by alanrodrigo** [sep-es-br/openpmo-web#89]
Após alterar o endereço de e-mail do acesso cidadão, não esta sendo mais possível acessar o menu de administração dos escritórios, mesmo tendo perfil de administrador

https://www.loom.com/share/4afdbeb65cfe4227a0d788220cc16906

**Comment by msantosmarcos** [comment]
DEMANDA RESOLVIDA
