### ISSUE TITLE
Botões de salvar fixos no final da página

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/openpmo-web#9]
Na versão inicial o botão de salvar flutuava até área visível da tela, que não ocorre na versão atual, forçando o usuário rolar a tela até o final para encontrar o botão. 
Não foi solicitada a alteração desse comportamento. Portanto o comportamento do botão até área visível teria que ser mantido.

**Comment by vdcordeiro** [comment]
Esta Issue foi parcialmente resolvida. Segue o comportamento do botão, conforme sistema original.

Sempre que a página é alterada e está pronta para ser salva, isto é, todas as validações de entrada foram realizadas com sucesso, o botão surge a partir da borda inferior, flutuando sobre o conteúdo da página e pára a uns 70 pixels da borda inferior da área visível. Se o usuário clica no botão ou desfaz as alterações a ponto de retornar à situação anterior ou invalidar alguma entrada, o botão é recolhido de volta e some pela borda inferior da área visível.

Conforme implementado até agora, o botão aparece mediante qualquer alteração, ainda que inválida, e não é mais recolhido, ainda que se retorne à situação original.

Obs.: O sistema original efetuava as validações de campos durante o preenchimento, exibindo mensagens localizadas nos campos incorretos. O sistema agora está efetuando as validações apenas no salvamento e exibindo as mensagens de validação de campo no alto da tela, como as demais, uma mudança indesejada e não solicitada. Esse problema foi reportado na issue #26 e está relacionado ao comportamento do botão salvar.

**Comment by msantosmarcos** [comment]
demanda resolvida
