### ISSUE TITLE
Nome truncado no card/list Administradores

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#93]
Na página de listagem de administradores, os nomes dos administradores estão aparecendo truncados. O padrão do sistema é ser exibido o _name_ e o _fullname_ na tooltip.

![image](https://user-images.githubusercontent.com/41954965/157469617-911c8a13-17da-49c6-a900-fc4b3ef35617.png)

**Comment by camilaseasky** [comment]
Ajustado. Vai na proxima atualização.

**Comment by vdcordeiro** [comment]
Os nomes continuam truncados

**Comment by camilaseasky** [comment]
Ajustado. Estará disponível para testes no final da tarde.

**Comment by vdcordeiro** [comment]
O problema persiste

**Comment by camilaseasky** [comment]
Ajustado e atualizado.

**Comment by msantosmarcos** [comment]
O problema persiste.

**Comment by msantosmarcos** [comment]
resolvido.
