### ISSUE TITLE
Página de um único painel não deve recolher 

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#94]
A página Administradores possui um único painel. Conforme acordo, nesses casos não exibiremos controles para recolhimento/expansão.
![image](https://user-images.githubusercontent.com/41954965/157472454-9477325d-27c6-4fcd-a34c-8f5c82187e13.png)

**Comment by camilaseasky** [comment]
Ajustado. Vai na atualização.

**Comment by vdcordeiro** [comment]
Ainda é possível recolher.
