### ISSUE TITLE
Mouse pointer sem função na página Administradores

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#95]
Na página Administradores, ao passar o mouse pelos cards, é exibido o mouse pointer, mas não há ação ao clicar no card, apenas no menu do card.
Isso dá a falsa impressão de que é possível "abrir" o cartão.
A imagem do mouse deve ser mantida como a seta.

**Comment by camilaseasky** [comment]
Ajustado. Vai na atualização.

**Comment by vdcordeiro** [comment]
Testado na versão do Web App 1.2.4.
O mouse pointer resolveu, mas agora ao clicar no cartão desvia para a página Offices.

**Comment by camilaseasky** [comment]
Ajustado. Estará disponível para testes no final da tarde.

**Comment by camilaseasky** [comment]
ajustado e atualizado

**Comment by msantosmarcos** [comment]
resolvido.
