### ISSUE TITLE
Botão Salvar sobe antes da hora ao incluir Administrador

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#96]
Na página de inclusão de administrador, logo após pesquisar o usuário (por nome ou CPF) e antes que a seleção seja feita, o botão _Salvar_ é exibido, permitindo o seu clique. Se o usuário clicar no botão antes de selecionar o novo administrador, o botão some e não aparece mais, nem mesmo após a seleção do novo administrador, o que inviabiliza aquela ação.

O botão _Salvar_ deve subir somente após a seleção do novo administrador pretendido.

![image](https://user-images.githubusercontent.com/41954965/157486905-6b173b25-7d86-404c-8022-bb2c5db63358.png)

**Comment by camilaseasky** [comment]
Resolvido. Vamos atualizar e avisamos.

**Comment by msantosmarcos** [comment]
demanda executada
