### ISSUE TITLE
Fullname de administradores ficando nulos

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#97]
Alguns administradores estão aparecendo com a propriedade **_fullname_** = _**null**_. 
Isso parece ocorrer com os administradores originais, inseridos a partir da instalação (application.properties).
Mesmo após vários logins essa propriedade não é preenchida.
![image](https://user-images.githubusercontent.com/41954965/157490588-cc4a3766-91ec-482a-a857-64b5bcb2e45a.png)
Além disso, note que no request acima o campo _**administrator**_ está retornando **_false_** para um usuário que é certamente um administrador. Isso parece não gerar problemas aqui, mas vale investigar.

**Comment by camilaseasky** [comment]
Não estamos conseguindo simular essa situação no nosso ambiente. Só está acontecendo com o servidor Vagner Dargan Cordeiro pelo que vi. Essa person foi criada pelo admin via arquivo de configuração? Poderia mandar um print da person no banco?

**Comment by camilaseasky** [comment]
Resolvido. Porém como o problema estava na criação das persons, aqueles que já haviam sido criados devem ser excluídos para que sejam criados novamente da maneira correta. A criação da person do admin pelo application properties acontece no momento que este se loga no sistema.

**Comment by msantosmarcos** [comment]
demanda resolvida.
