### ISSUE TITLE
Id do serviço de autenticação não é registrado

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/openpmo-web#98]
Quando um usuário é criado no openPMO, é estabelecido um relacionamento [IS_AUTHENTICATED_BY] entre o seu Person e o serviço de autenticação. Nesse relacionamento, previmos a propriedade **_id_**, que deve conter a chave única daquele usuário no serviço de autenticação. Veja diagrama de classes abaixo.
![image](https://user-images.githubusercontent.com/41954965/157498652-286b0d9a-93b2-4699-8417-84bfc025ff96.png)
No caso do Acesso Cidadão, essa chave está na propriedade **_sub_**.
![image](https://user-images.githubusercontent.com/41954965/157499217-0ef10193-a22a-494e-a276-42e66d1e012b.png)

O OpenPMO não está registrando essa propriedade no banco de dados. Veja abaixo:
![image](https://user-images.githubusercontent.com/41954965/157500124-6bf936fb-974e-4964-850e-1c7b2684b011.png)

Aparentemente o sistema está utilizando o email como chave, o que vai dar problema, pois esse email pode ser alterado no Acesso Cidadão pelo próprio usuário em qualquer momento. Quando isso ocorrer, ele deverá perder acesso ao OpenPMO ou até ser criado um novo usuário para a mesma pessoa, caso seja adicionada por outro usuário.

**Comment by icaromartinss** [comment]
Por favor, excluir todas as `Person`s do banco após atualizar o ambiente. Depois, sair e logar novamente no sistema.

**Comment by vdcordeiro** [comment]
Resolvido
